<div id="user" class="page-user">
    <div class="head">
        <img class="avatar" src="" alt=""/>
        <div class="auth"></div>
        <div class="info">
            <h2 class="name">James Dog</h2>
            <p class="signature">
                站在设计师背后，很不道德，you can you up, no can no bb
            </p>
            <div class="meta">
                <i class="icon glyphicon glyphicon-envelope"></i>
            </div>
        </div>
    </div>
    <div class="body"></div>
    <div class="foot"></div>
</div>
