<?$this->placeholder->block('title')->set($this->escaper->escapeHtml($post->title))?>

<div class="news-info" data-nodetype="<?=$post->type?>">
    <span class="title"> <?=$post->title?></span>
    <div class="meta">
        <span class="item author"><?=$post->name?></span>
        <span class="item time"><?=$this->tag->datetime($post->created)?></span>
    </div>
    <div class="content">
        <?=$post->body->und[0]->value?>
    </div>
    <!-- 广告位：文章下方广告 -->
    <div id="baidu_dup_924039" class="baidu-ad"></div>
    <script type="text/javascript">(BAIDU_DUP=window.BAIDU_DUP||[]).push(['fillAsync','924039','baidu_dup_924039']);</script>
	<div class="desktop" style="margin: 0px auto;width: 6em;font-size: 12px;color: #ccc;padding-bottom: 5px;cursor: pointer;"
		onclick="document.location.href = 'http://wallstreetcn.com/redirect.html?url=' + encodeURI(document.location.href.replace(document.location.hostname,'wallstreetcn.com'))">桌面版</div>
</div>
