<div id="main-content">
    <div id="leftbar">
        <div class="content">
            <div class="user box">
                <img class="avatar" src="" alt=""/>
                <button class="custom-button size-fluid type-blue">登陆</button>
            </div>
            <div id="left-market-list" class="nano" data-hover="unfold">
                <nav class="nano-content">
                <a class="market item" data-hover="related-info" data-trend="rise">
                    <span class="custom-row">
                        <span class="custom-span-1 name">黄金</span>
                        <span class="custom-span-2 diff">+0.99</span>
                    </span>
                    <span class="custom-row">
                        <span class="custom-span-1 value">1261.09</span>
                        <span class="custom-span-2 diff-pct">+0.68%</span>
                    </span>
                </a>
                <a class="market item" data-hover="related-info" data-trend="rise">
                    <span class="custom-row">
                        <span class="custom-span-1 name">布油</span>
                        <span class="custom-span-2 diff">+0.69</span>
                    </span>
                    <span class="custom-row">
                        <span class="custom-span-1 value">109.75</span>
                        <span class="custom-span-2 diff-pct">+0.57%</span>
                    </span>
                </a>
                <a class="market item" data-hover="related-info" data-trend="fall">
                    <span class="custom-row">
                        <span class="custom-span-1 name">标普500</span>
                        <span class="custom-span-2 diff">-0.48</span>
                    </span>
                    <span class="custom-row">
                        <span class="custom-span-1 value">1950.56</span>
                        <span class="custom-span-2 diff-pct">-0.49%</span>
                    </span>
                </a>
                <a class="market item" data-hover="related-info" data-trend="rise">
                    <span class="custom-row">
                        <span class="custom-span-1 name">欧元/美元</span>
                        <span class="custom-span-2 diff">+0.005</span>
                    </span>
                    <span class="custom-row">
                        <span class="custom-span-1 value">1.3538</span>
                        <span class="custom-span-2 diff-pct">+0.04%</span>
                    </span>
                </a>
                <a class="market item" data-hover="related-info" data-trend="fall">
                    <span class="custom-row">
                        <span class="custom-span-1 name">美元利率</span>
                        <span class="custom-span-2 diff">-0.014</span>
                    </span>
                    <span class="custom-row">
                        <span class="custom-span-1 value">2.651</span>
                        <span class="custom-span-2 diff-pct">-0.53%</span>
                    </span>
                </a>
                <a class="market item" data-hover="related-info" data-trend="rise">
                    <span class="custom-row">
                        <span class="custom-span-1 name">黄金</span>
                        <span class="custom-span-2 diff">+0.99</span>
                    </span>
                    <span class="custom-row">
                        <span class="custom-span-1 value">1261.09</span>
                        <span class="custom-span-2 diff-pct">+0.68%</span>
                    </span>
                </a>
                <a class="market item" data-hover="related-info" data-trend="rise">
                    <span class="custom-row">
                        <span class="custom-span-1 name">布油</span>
                        <span class="custom-span-2 diff">+0.69</span>
                    </span>
                    <span class="custom-row">
                        <span class="custom-span-1 value">109.75</span>
                        <span class="custom-span-2 diff-pct">+0.57%</span>
                    </span>
                </a>
                <a class="market item" data-hover="related-info" data-trend="fall">
                    <span class="custom-row">
                        <span class="custom-span-1 name">标普500</span>
                        <span class="custom-span-2 diff">-0.48</span>
                    </span>
                    <span class="custom-row">
                        <span class="custom-span-1 value">1950.56</span>
                        <span class="custom-span-2 diff-pct">-0.49%</span>
                    </span>
                </a>
                <a class="market item" data-hover="related-info" data-trend="rise">
                    <span class="custom-row">
                        <span class="custom-span-1 name">欧元/美元</span>
                        <span class="custom-span-2 diff">+0.005</span>
                    </span>
                    <span class="custom-row">
                        <span class="custom-span-1 value">1.3538</span>
                        <span class="custom-span-2 diff-pct">+0.04%</span>
                    </span>
                </a>
                <a class="market item" data-hover="related-info" data-trend="fall">
                    <span class="custom-row">
                        <span class="custom-span-1 name">美元利率</span>
                        <span class="custom-span-2 diff">-0.014</span>
                    </span>
                    <span class="custom-row">
                        <span class="custom-span-1 value">2.651</span>
                        <span class="custom-span-2 diff-pct">-0.53%</span>
                    </span>
                </a>
                <a class="market item" data-hover="related-info" data-trend="rise">
                    <span class="custom-row">
                        <span class="custom-span-1 name">黄金</span>
                        <span class="custom-span-2 diff">+0.99</span>
                    </span>
                    <span class="custom-row">
                        <span class="custom-span-1 value">1261.09</span>
                        <span class="custom-span-2 diff-pct">+0.68%</span>
                    </span>
                </a>
                <a class="market item" data-hover="related-info" data-trend="rise">
                    <span class="custom-row">
                        <span class="custom-span-1 name">布油</span>
                        <span class="custom-span-2 diff">+0.69</span>
                    </span>
                    <span class="custom-row">
                        <span class="custom-span-1 value">109.75</span>
                        <span class="custom-span-2 diff-pct">+0.57%</span>
                    </span>
                </a>
                <a class="market item" data-hover="related-info" data-trend="fall">
                    <span class="custom-row">
                        <span class="custom-span-1 name">标普500</span>
                        <span class="custom-span-2 diff">-0.48</span>
                    </span>
                    <span class="custom-row">
                        <span class="custom-span-1 value">1950.56</span>
                        <span class="custom-span-2 diff-pct">-0.49%</span>
                    </span>
                </a>
                <a class="market item" data-hover="related-info" data-trend="rise">
                    <span class="custom-row">
                        <span class="custom-span-1 name">欧元/美元</span>
                        <span class="custom-span-2 diff">+0.005</span>
                    </span>
                    <span class="custom-row">
                        <span class="custom-span-1 value">1.3538</span>
                        <span class="custom-span-2 diff-pct">+0.04%</span>
                    </span>
                </a>
                <a class="market item" data-hover="related-info" data-trend="fall">
                    <span class="custom-row">
                        <span class="custom-span-1 name">美元利率</span>
                        <span class="custom-span-2 diff">-0.014</span>
                    </span>
                    <span class="custom-row">
                        <span class="custom-span-1 value">2.651</span>
                        <span class="custom-span-2 diff-pct">-0.53%</span>
                    </span>
                </a>
                </nav>
            </div>
        </div>
        <div class="sidebar" data-hover="unfold">
            <div class="chart">

            </div>
            <h3 class="side-title">
                <button class="custom-button link type-blue">相关新闻</button>
            </h3>
            <ul class=" side-list with-dot">
                <li class="news">
                <a class="title" href="">6月汇丰中国制造业PMI初值创7个月新高 黄金微涨</a>
                </li>
                <li class="news">
                <a class="title" href="">全球第二大产糖国新规：原糖进口税猛增167%</a>
                </li>
                <li class="news">
                <a class="title" href="">证监会积极推动A股入MSCI，上交所认为大盘T+0条件成熟</a>
                </li>
            </ul>
            <h3 class="side-title">
                <button class="custom-button link type-blue">实时新闻</button>
            </h3>
            <div id="left-side-livenews" class="nano livenews-list size-sm">
                <ul class="content nano-content">
                    <li>
                    <a class="news" href="">
                        <span class="time">18:12</span>
                        <span class="title"> | 国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）</span>
                    </a>
                    </li>
                    <li>
                    <a class="news" href="">
                        <span class="time">18:09</span>
                        <span class="title"> | 受”以房养老”展开试点消息提振，养老概念股早盘大幅上涨。其中，概念股龙头桑乐金目前涨9.4%，盘中触及涨停</span>
                    </a>
                    </li>
                    <li>
                    <a class="news" href="">
                        <span class="time">17:53</span>
                        <span class="title"> | 香港恒生指数开盘上涨0.49%</span>
                    </a>
                    </li>
                    <li>
                    <a class="news" href="">
                        <span class="time">17:45</span>
                        <span class="title"> | 中国央行公开市场今日将通过28天期正回购操作回笼180亿元人民币。</span>
                    </a>
                    </li>
                    <li>
                    <a class="news" href="">
                        <span class="time">17:38</span>
                        <span class="title"> | 国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）</span>
                    </a>
                    </li>
                    <li>
                    <a class="news" href="">
                        <span class="time">18:12</span>
                        <span class="title"> | 国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）</span>
                    </a>
                    </li>
                    <li>
                    <a class="news" href="">
                        <span class="time">18:09</span>
                        <span class="title"> | 受”以房养老”展开试点消息提振，养老概念股早盘大幅上涨。其中，概念股龙头桑乐金目前涨9.4%，盘中触及涨停</span>
                    </a>
                    </li>
                    <li>
                    <a class="news" href="">
                        <span class="time">17:53</span>
                        <span class="title"> | 香港恒生指数开盘上涨0.49%</span>
                    </a>
                    </li>
                    <li>
                    <a class="news" href="">
                        <span class="time">17:45</span>
                        <span class="title"> | 中国央行公开市场今日将通过28天期正回购操作回笼180亿元人民币。</span>
                    </a>
                    </li>
                    <li>
                    <a class="news" href="">
                        <span class="time">17:38</span>
                        <span class="title"> | 国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）</span>
                    </a>
                    </li>
                    <li>
                    <a class="news" href="">
                        <span class="time">18:12</span>
                        <span class="title"> | 国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）</span>
                    </a>
                    </li>
                    <li>
                    <a class="news" href="">
                        <span class="time">18:09</span>
                        <span class="title"> | 受”以房养老”展开试点消息提振，养老概念股早盘大幅上涨。其中，概念股龙头桑乐金目前涨9.4%，盘中触及涨停</span>
                    </a>
                    </li>
                    <li>
                    <a class="news" href="">
                        <span class="time">17:53</span>
                        <span class="title"> | 香港恒生指数开盘上涨0.49%</span>
                    </a>
                    </li>
                    <li>
                    <a class="news" href="">
                        <span class="time">17:45</span>
                        <span class="title"> | 中国央行公开市场今日将通过28天期正回购操作回笼180亿元人民币。</span>
                    </a>
                    </li>
                    <li>
                    <a class="news" href="">
                        <span class="time">17:38</span>
                        <span class="title"> | 国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）</span>
                    </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div id="wrapper">
        <div id="main">

        </div>
        <div id="rightbar">
            <h2 class="side-title">
                头条新闻
                <button id="show-sidebar" class="custom-button type-blue link pull-right">实时新闻</button>
            </h2>

            <ul id="side-topnews" class=" side-list with-dot">
                <li class="news">
                <a class="title" href="">将股纳入新兴市场指数意味着什么？120亿美元入场，证监会积</a>
                </li>
                <li class="news">
                <a class="title" href="">全球第二大产糖国新规：原糖进口税猛增167%</a>
                </li>
                <li class="news">
                <a class="title" href="">中央出手救市落空？官媒抨击房地产唱空者“别有用心”</a>
                </li>
                <li class="news">
                <a class="title" href="">日媒：中国大幅减持日债恐为向日施压</a>
                </li>
                <li class="news">
                <a class="title" href="">南非史上最长罢工结束 铂金钯金双双下挫</a>
                </li>
            </ul>
            <!--  -->
            <div class="side-ad">
                <img src="img/side-img-1.jpg" alt=""/>
            </div>
            <!--  -->
            <div class="row">
                <div class="col-sm-12">

                </div>
            </div>
            <ul class="custom-nav-tabs custom-row">
                <li class="col-custom-6 active"><a data-toggle="tab" href="#side-day-rank-news">日排行</a></li>
                <li class="col-custom-6 "><a data-toggle="tab" href="#side-week-rank-news">周排行</a></li>
            </ul>
            <ul class="tab-content">
                <li class="tab-pane active" id="side-day-rank-news">
                <ul class="side-list with-number">
                    <li class="news">
                    <span class="number">1</span>
                    <a class="title" href="">什么都怪房地产？别把中国经济想得太简单</a>
                    </li>
                    <li class="news">
                    <span class="number">2</span>
                    <a class="title" href="">德国放弃从美国运回黄金说明了什么？</a>
                    </li>
                    <li class="news">
                    <span class="number">3</span>
                    <a class="title" href="">微刺激发力 汇丰中国制造业PMI创七个月新高</a>
                    </li>
                    <li class="news">
                    <span class="number">4</span>
                    <a class="title" href="">今夏全球市场焦点——美国通胀是否已现？</a>
                    </li>
                    <li class="news">
                    <span class="number">5</span>
                    <a class="title" href="">对话中国顶尖对冲基金！见闻俱乐部第2期主题沙龙火热报名中</a>
                    </li>
                    <li class="news">
                    <span class="number">6</span>
                    <a class="title" href="">干旱席卷世界最大甘蔗产区 对冲基金押宝糖价上涨</a>
                    </li>
                    <li class="news">
                    <span class="number">7</span>
                    <a class="title" href="">金属骗贷调查泼冷水 铜市六周以来首现净空头</a>
                    </li>
                    <li class="news">
                    <span class="number">8</span>
                    <a class="title" href="">伦敦房地产泡沫比中国更大</a>
                    </li>
                    <li class="news">
                    <span class="number">9</span>
                    <a class="title" href="">“超级投资者”踏空牛市 谁是美股新高的缔造者？</a>
                    </li>
                    <li class="news">
                    <span class="number">10</span>
                    <a class="title" href="">一张图看懂中国为何需要微刺激</a>
                    </li>
                </ul>
                </li>
                <li class="tab-pane " id="side-week-rank-news">
                <ul class="side-list with-number">
                    <li class="news">
                    <span class="number">1</span>
                    <a class="title" href="">什么都怪房地产？别把中国经济想得太简单</a>
                    </li>
                    <li class="news">
                    <span class="number">2</span>
                    <a class="title" href="">德国放弃从美国运回黄金说明了什么？</a>
                    </li>
                    <li class="news">
                    <span class="number">3</span>
                    <a class="title" href="">微刺激发力 汇丰中国制造业PMI创七个月新高</a>
                    </li>
                    <li class="news">
                    <span class="number">4</span>
                    <a class="title" href="">今夏全球市场焦点——美国通胀是否已现？</a>
                    </li>
                    <li class="news">
                    <span class="number">5</span>
                    <a class="title" href="">对话中国顶尖对冲基金！见闻俱乐部第2期主题沙龙火热报名中</a>
                    </li>
                    <li class="news">
                    <span class="number">6</span>
                    <a class="title" href="">干旱席卷世界最大甘蔗产区 对冲基金押宝糖价上涨</a>
                    </li>
                    <li class="news">
                    <span class="number">7</span>
                    <a class="title" href="">金属骗贷调查泼冷水 铜市六周以来首现净空头</a>
                    </li>
                    <li class="news">
                    <span class="number">8</span>
                    <a class="title" href="">伦敦房地产泡沫比中国更大</a>
                    </li>
                    <li class="news">
                    <span class="number">9</span>
                    <a class="title" href="">“超级投资者”踏空牛市 谁是美股新高的缔造者？</a>
                    </li>
                    <li class="news">
                    <span class="number">10</span>
                    <a class="title" href="">一张图看懂中国为何需要微刺激</a>
                    </li>
                </ul>
                </li>
            </ul>
            <!--  -->
            <h2 class="side-title type-blue">最新留言</h2>
            <ul class="side-comments">
                <li class="comment">
                <img class="avatar" src="" alt=""/>
                <div>
                    <a class="name" href="">smartisan</a> 评论了
                    <a class="title" href="">希尔顿酒店准备在纽约上市融资</a>
                </div>
                <p class="content">
                找中央啊！津京一体化，然后就没有问题了。但无论如何，财政纪律得重新抓，得狠抓，没有问题啊。
                </p>
                <div>
                    <span class="time">2014年06月25日 05:58</span>
                    <a class="text-blue pull-right" href="" data-action="reply">回复</a>
                </div>
                </li>

                <li class="comment">
                <img class="avatar" src="" alt=""/>
                <div>
                    <a class="name" href="">天才小熊猫</a> 评论了
                    <a class="title" href="">希尔顿酒店准备在纽约上市融资</a>
                </div>
                <p class="content">
                无言的秘密，美国收水，伊拉克开打不暴跌才怪呢。
                </p>
                <div>
                    <span class="time">2014年06月25日 06:03</span>
                    <a class="text-blue pull-right" href="" data-action="reply">回复</a>
                </div>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- main-content end -->
<div id="sidebar">
    <h2 class="side-title">
        实时新闻
        <button id="close-sidebar" class="custom-button type-blue link pull-right">头条新闻</button>
    </h2>
    <div id="side-livenews" class="nano">
        <ul class="nano-content">
            <li class="news"></li>
        </ul>
    </div>

</div>
