<div id="main-content">
    <div id="leftbar">
        <div class="content">
            <div class="user box">
                <img class="avatar" src="" alt=""/>
                <button class="custom-button size-fluid type-blue"
                        data-toggle="custom-modal"
                        data-target="#user-modal"
                        data-action="login">登陆</button>
            </div>
            <div id="left-market-list" class="nano" data-hover="unfold">
                <nav class="nano-content">
                    <a class="market item" data-hover="related-info" data-trend="rise">
                        <span class="custom-row">
                            <span class="custom-span-1 name">黄金</span>
                            <span class="custom-span-2 diff">+0.99</span>
                        </span>
                        <span class="custom-row">
                            <span class="custom-span-1 value">1261.09</span>
                            <span class="custom-span-2 diff-pct">+0.68%</span>
                        </span>
                    </a>
                    <a class="market item" data-hover="related-info" data-trend="rise">
                        <span class="custom-row">
                            <span class="custom-span-1 name">布油</span>
                            <span class="custom-span-2 diff">+0.69</span>
                        </span>
                        <span class="custom-row">
                            <span class="custom-span-1 value">109.75</span>
                            <span class="custom-span-2 diff-pct">+0.57%</span>
                        </span>
                    </a>
                    <a class="market item" data-hover="related-info" data-trend="fall">
                        <span class="custom-row">
                            <span class="custom-span-1 name">标普500</span>
                            <span class="custom-span-2 diff">-0.48</span>
                        </span>
                        <span class="custom-row">
                            <span class="custom-span-1 value">1950.56</span>
                            <span class="custom-span-2 diff-pct">-0.49%</span>
                        </span>
                    </a>
                    <a class="market item" data-hover="related-info" data-trend="rise">
                        <span class="custom-row">
                            <span class="custom-span-1 name">欧元/美元</span>
                            <span class="custom-span-2 diff">+0.005</span>
                        </span>
                        <span class="custom-row">
                            <span class="custom-span-1 value">1.3538</span>
                            <span class="custom-span-2 diff-pct">+0.04%</span>
                        </span>
                    </a>
                    <a class="market item" data-hover="related-info" data-trend="fall">
                        <span class="custom-row">
                            <span class="custom-span-1 name">美元利率</span>
                            <span class="custom-span-2 diff">-0.014</span>
                        </span>
                        <span class="custom-row">
                            <span class="custom-span-1 value">2.651</span>
                            <span class="custom-span-2 diff-pct">-0.53%</span>
                        </span>
                    </a>
                    <a class="market item" data-hover="related-info" data-trend="rise">
                        <span class="custom-row">
                            <span class="custom-span-1 name">黄金</span>
                            <span class="custom-span-2 diff">+0.99</span>
                        </span>
                        <span class="custom-row">
                            <span class="custom-span-1 value">1261.09</span>
                            <span class="custom-span-2 diff-pct">+0.68%</span>
                        </span>
                    </a>
                    <a class="market item" data-hover="related-info" data-trend="rise">
                        <span class="custom-row">
                            <span class="custom-span-1 name">布油</span>
                            <span class="custom-span-2 diff">+0.69</span>
                        </span>
                        <span class="custom-row">
                            <span class="custom-span-1 value">109.75</span>
                            <span class="custom-span-2 diff-pct">+0.57%</span>
                        </span>
                    </a>
                    <a class="market item" data-hover="related-info" data-trend="fall">
                        <span class="custom-row">
                            <span class="custom-span-1 name">标普500</span>
                            <span class="custom-span-2 diff">-0.48</span>
                        </span>
                        <span class="custom-row">
                            <span class="custom-span-1 value">1950.56</span>
                            <span class="custom-span-2 diff-pct">-0.49%</span>
                        </span>
                    </a>
                    <a class="market item" data-hover="related-info" data-trend="rise">
                        <span class="custom-row">
                            <span class="custom-span-1 name">欧元/美元</span>
                            <span class="custom-span-2 diff">+0.005</span>
                        </span>
                        <span class="custom-row">
                            <span class="custom-span-1 value">1.3538</span>
                            <span class="custom-span-2 diff-pct">+0.04%</span>
                        </span>
                    </a>
                    <a class="market item" data-hover="related-info" data-trend="fall">
                        <span class="custom-row">
                            <span class="custom-span-1 name">美元利率</span>
                            <span class="custom-span-2 diff">-0.014</span>
                        </span>
                        <span class="custom-row">
                            <span class="custom-span-1 value">2.651</span>
                            <span class="custom-span-2 diff-pct">-0.53%</span>
                        </span>
                    </a>
                    <a class="market item" data-hover="related-info" data-trend="rise">
                        <span class="custom-row">
                            <span class="custom-span-1 name">黄金</span>
                            <span class="custom-span-2 diff">+0.99</span>
                        </span>
                        <span class="custom-row">
                            <span class="custom-span-1 value">1261.09</span>
                            <span class="custom-span-2 diff-pct">+0.68%</span>
                        </span>
                    </a>
                    <a class="market item" data-hover="related-info" data-trend="rise">
                        <span class="custom-row">
                            <span class="custom-span-1 name">布油</span>
                            <span class="custom-span-2 diff">+0.69</span>
                        </span>
                        <span class="custom-row">
                            <span class="custom-span-1 value">109.75</span>
                            <span class="custom-span-2 diff-pct">+0.57%</span>
                        </span>
                    </a>
                    <a class="market item" data-hover="related-info" data-trend="fall">
                        <span class="custom-row">
                            <span class="custom-span-1 name">标普500</span>
                            <span class="custom-span-2 diff">-0.48</span>
                        </span>
                        <span class="custom-row">
                            <span class="custom-span-1 value">1950.56</span>
                            <span class="custom-span-2 diff-pct">-0.49%</span>
                        </span>
                    </a>
                    <a class="market item" data-hover="related-info" data-trend="rise">
                        <span class="custom-row">
                            <span class="custom-span-1 name">欧元/美元</span>
                            <span class="custom-span-2 diff">+0.005</span>
                        </span>
                        <span class="custom-row">
                            <span class="custom-span-1 value">1.3538</span>
                            <span class="custom-span-2 diff-pct">+0.04%</span>
                        </span>
                    </a>
                    <a class="market item" data-hover="related-info" data-trend="fall">
                        <span class="custom-row">
                            <span class="custom-span-1 name">美元利率</span>
                            <span class="custom-span-2 diff">-0.014</span>
                        </span>
                        <span class="custom-row">
                            <span class="custom-span-1 value">2.651</span>
                            <span class="custom-span-2 diff-pct">-0.53%</span>
                        </span>
                    </a>
                </nav>
            </div>
        </div>
        <div class="sidebar nano" data-hover="unfold">
            <div class="nano-content">
                <div class="chart">

                </div>
                <h3 class="side-title">
                    <button class="custom-button link type-blue">相关新闻</button>
                </h3>
                <ul class=" news-list with-dot">
                    <li class="news">
                        <a class="title" href="">6月汇丰中国制造业PMI初值创7个月新高 黄金微涨</a>
                    </li>
                    <li class="news">
                        <a class="title" href="">全球第二大产糖国新规：原糖进口税猛增167%</a>
                    </li>
                    <li class="news">
                        <a class="title" href="">证监会积极推动A股入MSCI，上交所认为大盘T+0条件成熟</a>
                    </li>
                </ul>
                <h3 class="side-title" style="margin-bottom: 15px; margin-top: 30px">
                    <button class="custom-button link type-blue">实时新闻</button>
                </h3>
                <ul id="left-side-livenews" class="livenews-list size-sm">
                    <li>
                        <a class="news" href="">
                            <span class="time">18:12</span>
                            <span class="title"> | 国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">18:09</span>
                            <span class="title"> | 受”以房养老”展开试点消息提振，养老概念股早盘大幅上涨。其中，概念股龙头桑乐金目前涨9.4%，盘中触及涨停</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">17:53</span>
                            <span class="title"> | 香港恒生指数开盘上涨0.49%</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">17:45</span>
                            <span class="title"> | 中国央行公开市场今日将通过28天期正回购操作回笼180亿元人民币。</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">17:38</span>
                            <span class="title"> | 国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">18:12</span>
                            <span class="title"> | 国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">18:09</span>
                            <span class="title"> | 受”以房养老”展开试点消息提振，养老概念股早盘大幅上涨。其中，概念股龙头桑乐金目前涨9.4%，盘中触及涨停</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">17:53</span>
                            <span class="title"> | 香港恒生指数开盘上涨0.49%</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">17:45</span>
                            <span class="title"> | 中国央行公开市场今日将通过28天期正回购操作回笼180亿元人民币。</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">17:38</span>
                            <span class="title"> | 国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">18:12</span>
                            <span class="title"> | 国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">18:09</span>
                            <span class="title"> | 受”以房养老”展开试点消息提振，养老概念股早盘大幅上涨。其中，概念股龙头桑乐金目前涨9.4%，盘中触及涨停</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">17:53</span>
                            <span class="title"> | 香港恒生指数开盘上涨0.49%</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">17:45</span>
                            <span class="title"> | 中国央行公开市场今日将通过28天期正回购操作回笼180亿元人民币。</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">17:38</span>
                            <span class="title"> | 国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）</span>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- nano-content -->
        </div>
        <!-- left sidebar end -->
    </div>
    <!-- leftbar end -->
    <div id="wrapper">
        <div id="main" class="post">
            <article>
                <h1 class="article-title">对话中国顶尖对冲基金！见闻俱乐部第2期主题沙龙火热报名中</h1>
                <div>
                    <span class="meta author">文/黄金头条</span>
                    <span class="meta time">2014年6月20号  12:24</span>
                    <div class="pull-right">
                        <span class="meta">来源：华尔街见闻</span>
                        <span class="meta comment-count icontext icontext-discuss-blue">(10)</span>
                    </div>
                </div>
                <img src="/wscn/img/img-news-lg.jpg" class="main-image" alt=""/>
                <div class="article-content">
                    <aside class="related-posts">
                        <h2 class="main-title">相关文章</h2>
                        <ul class="news-list with-dot">
                            <li class="news"><a class="title" href="">6月汇丰中国制造业PMI初值创7个月新高，黄金微涨</a></li>
                            <li class="news"><a class="title" href="">证监会积极推动A股入MSCI，上交所认为大盘T+0条件成熟</a></li>
                            <li class="news last-child"><a class="title" href="">MSCI将A股纳入市场意味着什么？</a></li>
                        </ul>
                    </aside>
                    <p>面对“政令不出中南海”的症结，约一个月前国务院总理李克强曾在常务会上批评某些地方“为官不为”，要求各部委“守土有责”。从上周开始，国务院派出8个督查组赴部分省、国务院部门和单位进行为期十天的督查，全面督查地方对稳增长、调结构、惠民生政策如何落实。</p>
                    <p>上述6月25日至7月5日动身的8个督查组有四个由部长挂帅。目前已督查或正督查的地区包括广东、湖南、湖北、河北、山东、辽宁等地，每地调研3天左右。督查主要针对《政府工作报告》部署的2014年重点工作和去年下半年以来出台的稳增长、促改革、调结构、惠民生等政策措施，涉及19个专题、60项重点内容。</p>
                    <p>知情人士向《第一财经日报》透露，按行程推算，此次督查将最大范围涉及多个地区和国务院下属机构，将是一轮比较全面的督查。“与此同时，部委的督查工作也正在展</p>
                    <p>据各地官方消息，</p>
                    <ul>
                        <li>国家发展改革委主任徐绍史任组长的第五督查组在山东省调研；</li>
                        <li>交通运输部部长杨传堂为组长、民政部副部长窦玉沛为副组长的第六督查组先督查河北省，随后赴辽宁省，曾在大连实地考察棚户区改造项目、公租房项目、养老服务中心等；</li>
                        <li>水利部部长陈雷任组长、人力资源和社会保障部副部长信长星任副组长的第七督查组先后在湖南和湖北省调研；</li>
                        <li>审计署审计长刘家义为组长、住房城乡建设部副部长齐骥为副组长的第八督查组在广东省检查，到广州、深圳、肇庆等市实地调研。</li>
                    </ul>
                </div>
                <p class="statement">
                    在各大APP商店搜索“华尔街见闻”，可下载我们的移动客户端。
                    <br/>同时欢迎关注见闻微信号：wallstreetcn
                </p>
                <div class="toolbar">
                    <span class="endorse icontext icontext-endorse-blue">(132)</span>
                    <a class="collect" href=""></a>
                    <!-- JiaThis Button BEGIN -->
                    <div class="jiathis_style_32x32">
                        <span class="text">分享</span>
                        <a class="jiathis_button_tsina"></a>
                        <a class="jiathis_button_cqq"></a>
                        <a class="jiathis_button_weixin"></a>
                        <a class="jiathis_button_evernote"></a>
                        <a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank"></a>
                    </div>
                    <script type="text/javascript" src="http://v3.jiathis.com/code/jia.js?uid=1393984262901745" charset="utf-8"></script>
                    <!-- JiaThis Button END -->
                </div>
                <div class="toolbar hidden-xxs" data-action="post">
                    <a class="prev-post">
                        <span class="icon glyphicon glyphicon-chevron-left"></span>
                        <img class="img" src="/wscn/img/img-news.jpg" alt=""/>
                        <h3 class="title">前中央军委副主席徐才厚严重违纪</h3>
                    </a>
                    <div class="separator"></div>
                    <a class="next-post">
                        <span class="icon glyphicon glyphicon-chevron-right"></span>
                        <img class="img" src="/wscn/img/img-news.jpg" alt=""/>
                        <h3 class="title">私营部门贷款持续收缩 通胀不及目标一半</h3>
                    </a>
                </div>
                <div class="toolbar visible-xxs">
                    上一篇：<a class="link" href="">前中央军委副主席徐才厚严重违纪</a>
                    <br/>
                    下一篇：<a class="link" href="">私营部门贷款持续收缩 通胀不及目标一半</a>
                </div>
            </article>
            <h2 class="main-title">更多热点</h2>
            <ul class="hot-news row">
                <li class="col-lg-4 col-xs-6">
                    <a href="" class="news">
                        <img class="img" src="/wscn/img/img-news.jpg" alt=""/>
                        <h3 class="title">操盘诀窍：5分钟读懂上市公司财报</h3>
                    </a>
                </li>
                <li class="col-lg-4 col-xs-6">
                    <a href="" class="news">
                        <img class="img" src="/wscn/img/img-news.jpg" alt=""/>
                        <h3 class="title">操盘诀窍：5分钟读懂上市公司财报</h3>
                    </a>
                </li>
                <li class="col-lg-4 col-xs-6">
                    <a href="" class="news">
                        <img class="img" src="/wscn/img/img-news.jpg" alt=""/>
                        <h3 class="title">操盘诀窍：5分钟读懂上市公司财报</h3>
                    </a>
                </li>
                <li class="col-lg-4 col-xs-6">
                    <a href="" class="news">
                        <img class="img" src="/wscn/img/img-news.jpg" alt=""/>
                        <h3 class="title">操盘诀窍：5分钟读懂上市公司财报</h3>
                    </a>
                </li>
                <li class="col-lg-4 col-xs-6">
                    <a href="" class="news">
                        <img class="img" src="/wscn/img/img-news.jpg" alt=""/>
                        <h3 class="title">操盘诀窍：5分钟读懂上市公司财报</h3>
                    </a>
                </li>
                <li class="col-lg-4 col-xs-6">
                    <a href="" class="news">
                        <img class="img" src="/wscn/img/img-news.jpg" alt=""/>
                        <h3 class="title">操盘诀窍：5分钟读懂上市公司财报</h3>
                    </a>
                </li>
            </ul>
            <h2 class="main-title">关键字阅读</h2>
            <ul class="custom-tabs">
                <li class="active"><a data-toggle="tab" href="#keyword-1">科技</a></li>
                <li><a data-toggle="tab" href="#keyword-2">华尔街</a></li>
                <li><a data-toggle="tab" href="#keyword-3">金融</a></li>
                <li><a data-toggle="tab" href="#keyword-4">沙龙</a></li>
            </ul>
            <div class="tab-content">
                <ul class="tab-pane active news-list with-dot" id="keyword-1">
                    <li class="news">
                        <a class="title" href="">中韩将签署货币直接交易协议，人民币国际化又落一子</a>
                    </li>
                </ul>
                <ul class="tab-pane news-list with-dot" id="keyword-2">
                    <li class="news">
                        <a class="title" href="">日本——“货币战”幕后真正发动者的替罪羊？</a>
                    </li>
                </ul>
                <ul class="tab-pane news-list with-dot" id="keyword-3">
                    <li class="news">
                        <a class="title" href="">韩国执政党呼吁加快韩元人民币直接兑换进程</a>
                    </li>
                </ul>
                <ul class="tab-pane news-list with-dot" id="keyword-4">
                    <li class="news">
                        <a class="title" href="">亚洲货币9月表现1997年以来最差</a>
                    </li>
                </ul>
            </div>
        </div>
        <div id="rightbar">
            <h3 class="side-title">
                <button class="custom-button link type-blue">实时新闻</button>
            </h3>
            <div id="right-side-livenews" class="nano livenews-list size-sm">
                <ul class="content nano-content">
                    <li>
                        <a class="news" href="">
                            <span class="time">18:12</span>
                            <span class="title"> | 国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">18:09</span>
                            <span class="title"> | 受”以房养老”展开试点消息提振，养老概念股早盘大幅上涨。其中，概念股龙头桑乐金目前涨9.4%，盘中触及涨停</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">17:53</span>
                            <span class="title"> | 香港恒生指数开盘上涨0.49%</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">17:45</span>
                            <span class="title"> | 中国央行公开市场今日将通过28天期正回购操作回笼180亿元人民币。</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">17:38</span>
                            <span class="title"> | 国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">18:12</span>
                            <span class="title"> | 国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">18:09</span>
                            <span class="title"> | 受”以房养老”展开试点消息提振，养老概念股早盘大幅上涨。其中，概念股龙头桑乐金目前涨9.4%，盘中触及涨停</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">17:53</span>
                            <span class="title"> | 香港恒生指数开盘上涨0.49%</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">17:45</span>
                            <span class="title"> | 中国央行公开市场今日将通过28天期正回购操作回笼180亿元人民币。</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">17:38</span>
                            <span class="title"> | 国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">18:12</span>
                            <span class="title"> | 国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">18:09</span>
                            <span class="title"> | 受”以房养老”展开试点消息提振，养老概念股早盘大幅上涨。其中，概念股龙头桑乐金目前涨9.4%，盘中触及涨停</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">17:53</span>
                            <span class="title"> | 香港恒生指数开盘上涨0.49%</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">17:45</span>
                            <span class="title"> | 中国央行公开市场今日将通过28天期正回购操作回笼180亿元人民币。</span>
                        </a>
                    </li>
                    <li>
                        <a class="news" href="">
                            <span class="time">17:38</span>
                            <span class="title"> | 国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）</span>
                        </a>
                    </li>
                </ul>
            </div>
            <!--  -->
            <div class="side-ad">
                <img src="/wscn/img/side-img-1.jpg" alt=""/>
            </div>
            <!--  -->
            <div class="row">
                <div class="col-sm-12">

                </div>
            </div>
            <ul class="custom-nav-tabs custom-row">
                <li class="col-custom-6 active"><a data-toggle="tab" href="#side-day-rank-news">日排行</a></li>
                <li class="col-custom-6 "><a data-toggle="tab" href="#side-week-rank-news">周排行</a></li>
            </ul>
            <ul class="tab-content">
                <li class="tab-pane active" id="side-day-rank-news">
                    <ul class="news-list with-number">
                        <li class="news">
                            <a class="title" href="">什么都怪房地产？别把中国经济想得太简单</a>
                        </li>
                        <li class="news">
                            <a class="title" href="">德国放弃从美国运回黄金说明了什么？</a>
                        </li>
                        <li class="news">
                            <a class="title" href="">微刺激发力 汇丰中国制造业PMI创七个月新高</a>
                        </li>
                        <li class="news">
                            <a class="title" href="">今夏全球市场焦点——美国通胀是否已现？</a>
                        </li>
                        <li class="news">
                            <a class="title" href="">对话中国顶尖对冲基金！见闻俱乐部第2期主题沙龙火热报名中</a>
                        </li>
                        <li class="news">
                            <a class="title" href="">干旱席卷世界最大甘蔗产区 对冲基金押宝糖价上涨</a>
                        </li>
                        <li class="news">
                            <a class="title" href="">金属骗贷调查泼冷水 铜市六周以来首现净空头</a>
                        </li>
                        <li class="news">
                            <a class="title" href="">伦敦房地产泡沫比中国更大</a>
                        </li>
                        <li class="news">
                            <a class="title" href="">“超级投资者”踏空牛市 谁是美股新高的缔造者？</a>
                        </li>
                        <li class="news">
                            <a class="title" href="">一张图看懂中国为何需要微刺激</a>
                        </li>
                    </ul>
                </li>
                <li class="tab-pane " id="side-week-rank-news">
                    <ul class="news-list with-number">
                        <li class="news">
                            <a class="title" href="">什么都怪房地产？别把中国经济想得太简单</a>
                        </li>
                        <li class="news">
                            <a class="title" href="">德国放弃从美国运回黄金说明了什么？</a>
                        </li>
                        <li class="news">
                            <a class="title" href="">微刺激发力 汇丰中国制造业PMI创七个月新高</a>
                        </li>
                        <li class="news">
                            <a class="title" href="">今夏全球市场焦点——美国通胀是否已现？</a>
                        </li>
                        <li class="news">
                            <a class="title" href="">对话中国顶尖对冲基金！见闻俱乐部第2期主题沙龙火热报名中</a>
                        </li>
                        <li class="news">
                            <a class="title" href="">干旱席卷世界最大甘蔗产区 对冲基金押宝糖价上涨</a>
                        </li>
                        <li class="news">
                            <a class="title" href="">金属骗贷调查泼冷水 铜市六周以来首现净空头</a>
                        </li>
                        <li class="news">
                            <a class="title" href="">伦敦房地产泡沫比中国更大</a>
                        </li>
                        <li class="news">
                            <a class="title" href="">“超级投资者”踏空牛市 谁是美股新高的缔造者？</a>
                        </li>
                        <li class="news">
                            <a class="title" href="">一张图看懂中国为何需要微刺激</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!--  -->

        </div>
    </div>
</div>