<?
$this->placeholder->block('title')->set($post->title . "-华尔街见闻");
$description = $post->summary ? $post->summary : $post->title;
$description = strip_tags($description);
$this->placeholder->block('description')->set(
    $description . "。华尔街见闻——中国最专业的金融资讯平台；直播外汇、期货、黄金、债券、证券等金融领域的实时新闻。华人投资者可以在这里获得最快速、最精准、最深入的全球财经资讯和市场行情。"
);
$this->placeholder->block('keywords')->set($post->title . ",外汇,期货,大宗商品,贵金属,黄金,股市,行情,数据,金融,理财");
?>
<div id="main-content">
<aside id="leftbar">
    <div class="sharebar">
        <span class="collect" data-toggle="collect" data-active=""
              data-post-id="<?= $post->id ?>" data-url="/stars/<?= $post->id ?>"
              data-message="登录后收藏" data-text="收藏" data-active-text="取消收藏" >
            <span class="fa fa-star"></span>
        </span>
        <a class="discuss" href="#comments">
            <span class="fa fa-comment"></span>
            评论
            <? if ($post->commentCount > 0): ?>
                （<span class="ws-counter"><?= $post->commentCount ?></span>）
            <? endif ?>
        </a>

        <div class="read-times">
            <strong id="js-read-times-text"><?= $post->count ?></strong>
            <script>
                function _postCounter(num) {
                    var counterOld;
                    try {
                        counterOld = parseInt(<?=$post->count?>);
                    } catch (e) {
                        counterOld = 0;
                    }
                    try {
                        num = parseInt(num);
                    } catch (e) {
                        num = 0;
                    }
                    document.getElementById('js-read-times-text').innerText = counterOld + num;
                }
            </script>
            <?= $this->tag->CounterRank('posts', $post->id, '_postCounter') ?>
            <div class="text">浏览数</div>
        </div>
        <h3 class="jiathis-title">
            分享到
        </h3>
        <!-- JiaThis Button BEGIN -->
        <div class="jiathis_style_32x32">
            <a class="jiathis_button_tsina">
                <span class="fa fa-weibo"></span>
                微博
            </a>
            <a class="jiathis_button_cqq">
                <span class="fa fa-qq"></span>
                QQ
            </a>
            <a class="jiathis_button_weixin">
                <span class="fa fa-weixin"></span>
                微信
            </a>
            <a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank">
                <span class="fa fa-plus"></span>
                其它
            </a>
        </div>
        <!--<script type="text/javascript" src="http://v3.jiathis.com/code/jia.js?uid=1393984262901745" charset="utf-8"></script>-->
        <!-- JiaThis Button END -->
    </div>
</aside>
<!-- leftbar end -->
<div id="wrapper">
<div id="main" class="page-article">
    <article>
        <h1 class="article-title"><?= $post->title ?></h1>
        <input class="admin-control-post" type="hidden" value="<?= $post->id ?>">

        <div class="meta">
            <span class="item author">文 /
                <? if ($post->user): ?>
                    <a href="/news?uid=<?= $post->user->id ?>"
                       target="_blank"><?= $post->user->screenName ? : $post->user->username ?></a>
                <? else: ?>
                    华尔街见闻
                <?endif ?>
            </span>
            <span class="item time"><?= $this->tag->datetime($post->createdAt) ?></span>
            <span class="item">
                <span class="fa fa-comment" style="vertical-align: 1px"></span>
                <span class="ws-counter"><?= $post->commentCount > 0 ? : 0 ?></span>
            </span>

            <div class="pull-right">
                <? if ($post->sourceName): ?>
                    <span class="item">来源：<a href="<?= $post->sourceUrl ?>"
                                             target="_blank"><?= $post->sourceName ?></a></span>
                <? endif ?>

            </div>
        </div>
        <? if ($post->imageId): ?>
            <img class="main-image lazy" src="<?=$this->url->getStatic('/wscn/img/default.png')?>" alt=""
                 data-original="<?=
                 $post->thumbnail->imageWidth > 640 || $post->thumbnail->imageHeight > 350 ?
                     $this->tag->thumb($post->image, 'c_fill,h_350,w_640') : $this->tag->thumb($post->image)?>"/>
        <? endif ?>
        <div class="article-content">
            <?= $post->getContentHtml() ?>
        </div>
        <p class="statement">
            在各大APP商店搜索“华尔街见闻”，可下载我们的移动客户端。
            <br/>同时欢迎关注见闻微信号：wallstreetcn
        </p>

        <div class="toolbar">
            <span class="collect" data-toggle="collect" data-active=""
                  data-post-id="<?= $post->id ?>" data-url="/stars/<?= $post->id ?>"
                  data-message="登录后收藏" data-text="" data-active-text="" >

                <span class="fa fa-star"></span>
            </span>
            <span style="margin: 0 15px; float: left;">|</span>
            <a class="endorse">
                <span class="fa fa-thumbs-up"></span>
                132
            </a>
            <!-- JiaThis Button BEGIN -->
            <div class="jiathis_style_32x32">
                <span class="title">分享到 </span>
                <a class="jiathis_button_tsina">
                    <span class="fa fa-weibo"></span>
                    <span class="text">新浪微博</span>
                </a>
                <a class="jiathis_button_weixin">
                    <span class="fa fa-weixin"></span>
                    <span class="text">微信朋友圈</span>
                </a>
                <a class="jiathis_button_cqq">
                    <span class="fa fa-qq"></span>
                    <span class="text">腾讯 QQ</span>
                </a>
                <a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jtico jtico_jiathis"
                   target="_blank">
                    <span class="fa fa-plus"></span>
                </a>
            </div>
            <script type="text/javascript">
                <?
                    $summary4share = preg_replace('/\n+/', ' ', strip_tags($post->summary));

                    $title4share = $post->title.' ';
                    $titleLength = mb_strlen($title4share, 'utf-8');
                    $summaryLength = mb_strlen($summary4share, 'utf-8');
                    $wscnWeiboAccount = '@华尔街见闻';
                    $wscnWeiboAccountLength = mb_strlen($wscnWeiboAccount, 'utf-8');
                    $lengthLimit = 114;
                    if($titleLength + $summaryLength + $wscnWeiboAccountLength > $lengthLimit) {
                        $summaryRealLength = $lengthLimit - $titleLength - $wscnWeiboAccountLength;
                        $summary4share = \Eva\EvaEngine\Text\Substring::substrCn($summary4share, $summaryRealLength);
                    }
                    $summary4share .= $wscnWeiboAccount;
                ?>
                var jiathis_config = {
                    summary: "<?=$summary4share?>",
                    title: "<?=$title4share?>",
                    pic: "<?=$this->tag->thumb($post->image)?>",
                    appkey: {
                        <?
                            $appKeysCount = count($appKeys4share);
                            $appKeysIteratorI = 0;
                        ?>
                        <?foreach($appKeys4share as $_name => $_v):?>
                        "<?=$_name?>": "<?=$_v?>"<?= ++$appKeysIteratorI < $appKeysCount ? ',' :'' ?>
                        <?endforeach;?>
                    },
                    shortUrl: false
                }
            </script>
            <script type="text/javascript" src="http://v3.jiathis.com/code/jia.js?uid=1393984262901745"
                    charset="utf-8"></script>
            <!-- JiaThis Button END -->
        </div>
        <? if ($relatedPosts): ?>
            <div class="related-posts">
                <h2 class="side-title">相关新闻</h2>
                <ul class="news-list with-dot">
                    <? foreach ($relatedPosts as $connectedPost): ?>
                        <li class="news">
                            <a href="<?= $this->tag->PostUrl($connectedPost) ?>"><?= $connectedPost['title'] ?></a>
                        </li>
                    <? endforeach ?>
                </ul>
            </div>
        <? endif ?>

        <? if ($post->tags): ?>
            <nav class="tags">
                <h2 class="title">关键词阅读:</h2>
                <? foreach ($post->tags as $key => $tag): ?>
                    <a class="tag" href="/news/?tid=<?= $tag->id ?>"><?= $tag->tagName ?></a>
                <? endforeach ?>
            </nav>
        <? endif ?>

    </article>

    <div id="comments">
        <? if ($post->commentStatus == 'open'): ?>
            <? $this->partial('partial/comment', array('uniqueKey' => 'post_' . $post->id)); ?>
        <? endif ?>
    </div>

</div>
<div id="rightbar">

    <h2 class="side-title">实时行情</h2>
    <!-- Start: Wallstreetcn.com sidebar widget -->
    <div id="js-wscn-sidebar-wrapper" class="hidden-xxs"></div>
    <script src="http://markets.static.wallstreetcn.com/embed/sidebar.js" type='text/javascript'></script>
    <script type='text/javascript'>
        (function () {
            var parentId = 'js-wscn-sidebar-wrapper';
            var iframeId = 'js-wscn-sidebar-iframe';
            var options = /*options*/{
                "chart": {
                    "interval": "5"
                },
                "theme": "gray",
                "height": "430",
                "width": "300",
                "active": 0,
                "tabs": [
                    {
                        "name": "综合",
                        "symbols": [
                            "XAUUSD",
                            "UKOil",
                            "SPX500",
                            "000001",
                            "EURUSD",
                            "USDJPY",
                            "US10Year"
                        ]
                    },
                    {
                        "name": "外汇",
                        "symbols": [
                            "EURUSD",
                            "GBPUSD",
                            "USDJPY",
                            "USDCHF",
                            "AUDUSD",
                            "USDCAD",
                            "USDollarIndex"
                        ]
                    },
                    {
                        "name": "期货",
                        "symbols": [
                            "XAUUSD",
                            "XAGUSD",
                            "UKOil",
                            "USOil",
                            "Copper",
                            "CORN",
                            "WHEAT"
                        ]
                    },
                    {
                        "name": "股指",
                        "symbols": [
                            "SPX500",
                            "NAS100",
                            "US30",
                            "JPN225INDEX",
                            "hkg33index",
                            "UK100",
                            "eustx50index"
                        ]
                    }
                ]
            }
            /*endOptions*/
            var sidebar = new WallstreetCN.embed.Sidebar(parentId, options, iframeId);
            sidebar.render();
        })();
    </script>
    <!-- End: Wallstreetcn.com sidebar widget -->
    <!--  -->
    <div class="side-ad">
        <img src="<?=$this->url->getStatic('/wscn/img//ad/side-ad.png')?>" alt=""/>
    </div>
    <!--  -->
    <h2 class="side-title" style="margin-bottom: 0;">热门阅读</h2>
    <!--  -->
    <? $pager = $this->tag->component(
        'post',
        array('status' => 'published', 'cid' => 2, 'limit' => 6, 'has_image' => 1, 'order' => '-sort_order')
    );
    $posts = $pager->items; ?>
    <ul class="hot-news">
        <? foreach ($posts as $hotpost): ?>
            <li>
                <a href="<?= $hotpost->getUrl() ?>" class="news">
                    <img class="lazy img" src="<?=$this->url->getStatic('/wscn/img/default.png')?>"
                         data-original="<?=
                         $hotpost->image ? $this->tag->thumb(
                             $hotpost->image,
                             'c_fill,h_115,w_193'
                         ) : '/img/article.jpg' ?>" alt=""/>
                    <strong class="title"><?= $hotpost->title ?></strong>
                </a>
            </li>
        <? endforeach ?>
    </ul>
</div>
</div>
</div>
