<div id="main-content">
    <aside id="leftbar">

    </aside>
    <div id="wrapper">
        <div id="main">
            <ul class="tab-pane news-list with-img active" id="main-news">
                <li class="news">
                    <div class="row">
                        <div class="col-lg-4 col-sm-5 col-xs-5">
                            <a class="cover-img" href="#">
                                <img class="img " src="/wscn/img/img-news.jpg" alt=""/>
                                <div class="cover">
                                    <span class="endorse icontext icontext-endorse-white">(123)</span>
                                    <span class="discuss icontext icontext-discuss-white">(89)</span>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-8 col-sm-7 col-xs-7">
                            <a class="title" href="#">乌克兰局势缓和：反对派加入停火协议</a>
                            <div>
                                <span class="meta author">文 / 维尔京</span>
                                <span class="meta time visible-lg-inline-block">2014年06月24日 12:16</span>
                                    <span class="meta pull-right visible-lg-inline-block">
                                        <a class="share" href=""></a>
                                        <a class="collect" href=""></a>
                                    </span>
                                <span class="meta time hidden-lg pull-right">3分钟前</span>
                            </div>
                            <p class="summary visible-lg visible-xs">
                                周一，在于乌克兰政府首次面对面谈判后，乌克兰亲俄派宣布停火，时间自周一至周五。上周五，乌克兰总统波罗申科公布一系列和平计划，同时宣布为期一周的停火协议。</p>
                        </div>
                        <p class="summary col-sm-12 hidden-lg hidden-xs">
                            周一，在于乌克兰政府首次面对面谈判后，乌克兰亲俄派宣布停火，时间自周一至周五。上周五，乌克兰总统波罗申科公布一系列和平计划，同时宣布为期一周的停火协议。
                        </p>
                    </div>
                </li>
                <!--  -->
                <li class="news">
                    <div class="row">
                        <div class="col-lg-4 col-sm-5 col-xs-5">
                            <a class="cover-img" href="#">
                                <img class="img " src="/wscn/img/img-news.jpg" alt=""/>
                                <div class="cover">
                                    <span class="endorse icontext icontext-endorse-white">(123)</span>
                                    <span class="discuss icontext icontext-discuss-white">(89)</span>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-8 col-sm-7 col-xs-7">
                            <a class="title" href="#">乌克兰局势缓和：反对派加入停火协议</a>
                            <div>
                                <span class="meta author">文 / 维尔京</span>
                                <span class="meta time visible-lg-inline-block">2014年06月24日 12:16</span>
                                    <span class="meta pull-right visible-lg-inline-block">
                                        <a class="share" href=""></a>
                                        <a class="collect" href=""></a>
                                    </span>
                                <span class="meta time hidden-lg pull-right">3分钟前</span>
                            </div>
                            <p class="summary visible-lg visible-xs">
                                周一，在于乌克兰政府首次面对面谈判后，乌克兰亲俄派宣布停火，时间自周一至周五。上周五，乌克兰总统波罗申科公布一系列和平计划，同时宣布为期一周的停火协议。</p>
                        </div>
                        <p class="summary col-sm-12 hidden-lg hidden-xs">
                            周一，在于乌克兰政府首次面对面谈判后，乌克兰亲俄派宣布停火，时间自周一至周五。上周五，乌克兰总统波罗申科公布一系列和平计划，同时宣布为期一周的停火协议。
                        </p>
                    </div>
                </li>
                <!--  -->
                <li class="news">
                    <div class="row">
                        <div class="col-lg-4 col-sm-5 col-xs-5">
                            <a class="cover-img" href="#">
                                <img class="img " src="/wscn/img/img-news.jpg" alt=""/>
                                <div class="cover">
                                    <span class="endorse icontext icontext-endorse-white">(123)</span>
                                    <span class="discuss icontext icontext-discuss-white">(89)</span>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-8 col-sm-7 col-xs-7">
                            <a class="title" href="#">乌克兰局势缓和：反对派加入停火协议</a>
                            <div>
                                <span class="meta author">文 / 维尔京</span>
                                <span class="meta time visible-lg-inline-block">2014年06月24日 12:16</span>
                                    <span class="meta pull-right visible-lg-inline-block">
                                        <a class="share" href=""></a>
                                        <a class="collect" href=""></a>
                                    </span>
                                <span class="meta time hidden-lg pull-right">3分钟前</span>
                            </div>
                            <p class="summary visible-lg visible-xs">
                                周一，在于乌克兰政府首次面对面谈判后，乌克兰亲俄派宣布停火，时间自周一至周五。上周五，乌克兰总统波罗申科公布一系列和平计划，同时宣布为期一周的停火协议。</p>
                        </div>
                        <p class="summary col-sm-12 hidden-lg hidden-xs">
                            周一，在于乌克兰政府首次面对面谈判后，乌克兰亲俄派宣布停火，时间自周一至周五。上周五，乌克兰总统波罗申科公布一系列和平计划，同时宣布为期一周的停火协议。
                        </p>
                    </div>
                </li>
            </ul>
            <!--  -->
        </div>
        <!-- main end -->
        <div id="rightbar">
            <!--  -->
            <div class="side-ad">
                <img src="/wscn/img/side-img-1.jpg" alt=""/>
            </div>
            <!--  -->
            <ul class="custom-nav-tabs custom-row">
                <li class="col-custom-6 active">
                    <a data-toggle="tab" href="#side-day-rank-news"><strong>日排行</strong></a>
                </li>
                <li class="col-custom-6 ">
                    <a data-toggle="tab" href="#side-week-rank-news"><strong>周排行</strong></a>
                </li>
            </ul>
            <ul class="tab-content">
                <li class="tab-pane active" id="side-day-rank-news">
                    <ul class="news-list with-number">
                        <li class="news">
                            <a class="title" href="">
                                <strong>金属骗贷调查泼冷水，铜市六周以来首现净空头</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>伦敦房地产泡沫比中国更大</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>“超级投资者”踏空牛市 谁是美股新高的缔造者？</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>什么都怪房地产？别把中国经济想得太简单</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>德国放弃从美国运回黄金说明了什么？</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>微刺激发力 汇丰中国制造业PMI创七个月新高</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>今夏全球市场焦点——美国通胀是否已现？</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>对话中国顶尖对冲基金！见闻俱乐部第2期主题沙龙火热报名中</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>干旱席卷世界最大甘蔗产区 对冲基金押宝糖价上涨</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>一张图看懂中国为何需要微刺激</strong>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="tab-pane " id="side-week-rank-news">
                    <ul class="news-list with-number">
                        <li class="news">
                            <a class="title" href="">
                                <strong>什么都怪房地产？别把中国经济想得太简单</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>德国放弃从美国运回黄金说明了什么？</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>微刺激发力 汇丰中国制造业PMI创七个月新高</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>今夏全球市场焦点——美国通胀是否已现？</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>对话中国顶尖对冲基金！见闻俱乐部第2期主题沙龙火热报名中</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>干旱席卷世界最大甘蔗产区 对冲基金押宝糖价上涨</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>金属骗贷调查泼冷水，铜市六周以来首现净空头</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>伦敦房地产泡沫比中国更大</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>“超级投资者”踏空牛市 谁是美股新高的缔造者？</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>一张图看懂中国为何需要微刺激</strong>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!--  -->
            <div class="side-ad">
                <img src="/wscn/img/side-img-1.jpg" alt=""/>
            </div>
        </div>
        <!-- rightbar end -->
    </div>
</div>