<div id="user" class="page-user">
    <h2 class="form-title">欢迎加入华尔街见闻</h2>
    <div class="custom-row">
        <div class="custom-span-1">
            test
        </div>
        <div class="custom-span-2">
            <h3 class="sub-title">使用社交帐号登录</h3>
            <a class="custom-button type-weibo size-fluid">
                <i class="icontext icontext-weibo-md">微博帐号</i>
            </a>
            <a class="custom-button type-qq size-fluid">
                <i class="icontext icontext-qq-md">QQ帐号</i>
            </a>
        </div>
    </div>
</div>