<div id="search">
    <form id="search-form" action="">
        <input class="search-field" type="text"/>
        <input class="submit" type="submit" type="text"/>
    </form>
    <ul class="custom-nav-tabs">
        <li class="active"><a data-toggle="tab" href="#search-news">新闻(13690)</a></li>
        <li><a data-toggle="tab" href="#search-market">资产(30)</a></li>
        <li><a data-toggle="tab" href="#search-user">用户(5)</a></li>
        <li class="pull-right hidden-xxs">
            <label>排序：</label>
            <select>
                <option value="asc">正序</option>
                <option value="desc">倒序</option>
            </select>
        </li>
    </ul>
    <div class="tab-content">
        <ul class="tab-pane search-list active" id="search-news">
            <li class="item news">
                <img class="img hidden-xxs" src="/wscn/img/img-news.jpg" alt=""/>
                <a class="title" href="">黄金暂时承压1330下方，等待非农消息</a>
                <div>
                    <span class="meta author">文/<span class="text-blue">黄金头条</span></span>
                    <span class="meta time">2014年6月20号 12:24</span>
                </div>
                <p class="summary hidden-xxs">
                    周四(7月3日)亚市盘中，国际现货黄金价格暂时承压于1330美元/盎司下方。黄金自6月份以来维持的涨势将面临今晚非农的层层考虑，同时晚间还将公布欧洲数据。
                </p>
                <div class="toolbar hidden-xxs">
                    <span class="pull-right">
                        <a class="share" href=""></a>
                        <a class="collect" href=""></a>
                    </span>
                </div>
            </li>
        </ul>
        <ul class="tab-pane search-list" id="search-user"></ul>
        <ul class="tab-pane search-list" id="search-market"></ul>
    </div>
</div>