<div id="main-content" class="columns-2">
    <div id="main" class="page-user">
        <div class="head">
            <img class="avatar" src="" alt=""/>
            <div class="auth">
                <h3 class="title">
                    V 华尔街见闻认证
                </h3>
                <div class="info">华尔街见闻 美工</div>
                <a href="" class="handle">申请认证</a>
            </div>
            <div class="info">
                <h2 class="name">James Dog</h2>
                <p class="signature">
                    站在设计师背后，很不道德，you can you up, no can no bb
                </p>
                <div class="meta">
                    <i class="icon glyphicon glyphicon-envelope"></i>JamesNgai@hotmail.com
                </div>
                <div class="meta">
                    <i class="icon glyphicon glyphicon-map-marker"></i>上海 黄浦区
                </div>
                <div class="meta">
                    <i class="icon glyphicon glyphicon-user"></i>巨蟹座 | 华尔街见闻
                </div>
            </div>
        </div>
        <div class="body">
            <ul class="custom-nav-tabs">
                <li class="">
                    <a data-toggle="tab" href="#user-at">提到我的</a>
                </li>
                <li class="">
                    <a data-toggle="tab" href="#user-comments">个人评论</a>
                </li>
                <li class="">
                    <a data-toggle="tab" href="#user-markets">自选行情</a>
                </li>
                <li class="">
                    <a data-toggle="tab" href="#user-collect">文章收藏</a>
                </li>
                <li class="active">
                    <a data-toggle="tab" href="#user-info">个人资料</a>
                </li>
                <li class="">
                    <a data-toggle="tab" href="#user-endorse">赞</a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane" id="user-at"></div>
                <div class="tab-pane" id="user-comments"></div>
                <div class="tab-pane" id="user-markets"></div>
                <div class="tab-pane" id="user-collect"></div>
                <div class="tab-pane active" id="user-info"></div>
                <div class="tab-pane" id="user-endorse"></div>
            </div>
        </div>
        <div class="foot"></div>
    </div>

</div>
