<div id="main-content" class="columns-2">
    <div id="main" class="page-user">
        <div class="head">
            <img class="avatar" src="/wscn/img/avatar-md.png" alt=""/>
            <div class="auth">
                <h3 class="title">
                    V 华尔街见闻认证
                </h3>
                <div class="info">华尔街见闻 美工</div>
                <a href="" class="handle">申请认证</a>
            </div>
            <div class="info">
                <h2 class="name">James </h2>
                <p class="signature">
                    站在设计师背后，很不道德，you can you up, no can no bb
                </p>
                <div class="meta">
                    <i class="icon glyphicon glyphicon-envelope"></i>JamesNgai@hotmail.com
                    <span class="edit" data-action="edit">
                        <i class="icon glyphicon glyphicon-pencil"></i> 修改
                    </span>
                </div>
                <div class="meta">
                    <i class="icon glyphicon glyphicon-map-marker"></i>上海 黄浦区
                    <span class="edit" data-action="edit">
                        <i class="icon glyphicon glyphicon-pencil"></i> 修改
                    </span>
                </div>
                <div class="meta">
                    <i class="icon glyphicon glyphicon-user"></i>巨蟹座 | 华尔街见闻
                    <span class="edit" data-action="edit">
                        <i class="icon glyphicon glyphicon-pencil"></i> 修改
                    </span>
                </div>
            </div>
        </div>
        <div class="body">
            <ul class="custom-nav-tabs">
                <li class="">
                    <a data-toggle="tab" href="#user-at">提到我的</a>
                </li>
                <li class="">
                    <a data-toggle="tab" href="#user-comments">个人评论</a>
                </li>
                <li class="">
                    <a data-toggle="tab" href="#user-markets">自选行情</a>
                </li>
                <li class="">
                    <a data-toggle="tab" href="#user-collect">文章收藏</a>
                </li>
                <li class="active">
                    <a data-toggle="tab" href="#user-info">个人资料</a>
                </li>
                <li class="">
                    <a data-toggle="tab" href="#user-endorse">赞</a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane" id="user-at"></div>
                <div class="tab-pane" id="user-comments">
                    <ul class="comments">
                        <li class="comment">
                            <a class="title" href="">黄金暂时承压1330下方，等待非农消息</a>
                            <p class="summary">
                                周四(7月3日)亚市盘中，国际现货黄金价格暂时承压于1330美元/盎司下方。
                            </p>
                            <div>
                                <span class="time">2014年6月20号  12:24</span>
                                <a class="text-blue pull-right" data-action="delete">删除</a>
                            </div>
                        </li>
                        <li class="comment">
                            <a class="title" href="">彭博调查：多数黄金交易员及分析师看跌下周金价</a>
                            <p class="summary">
                                周四(7月3日)亚市盘中，国际现货黄金价格暂时承压于1330美元/盎司下方。黄金自6月份以来维持的涨势将面临今晚非农的层层考虑，同时晚间还将...
                            </p>
                            <div>
                                <span class="time">2014年6月20号  12:24</span>
                                <a class="text-blue pull-right" data-action="delete">删除</a>
                            </div>
                        </li>
                        <li class="comment">
                            <a class="title" href="">彭博调查：多数黄金交易员及分析师看跌下周金价，布伦特原油大涨，欧盟就严厉制裁俄罗斯新措施达成初步协议</a>
                            <p class="summary">
                                周四(7月3日)亚市盘中，国际现货黄金价格暂时承压于1330美元/盎司下方。黄金自6月份以来维持的涨势将面临今晚非农的层层考虑，同时晚间还将...
                            </p>
                            <div>
                                <span class="time">2014年6月20号  12:24</span>
                                <a class="text-blue pull-right" data-action="delete">删除</a>
                            </div>
                        </li>
                        <li class="comment">
                            <a class="title" href="">黄金暂时承压1330下方，等待非农消息</a>
                            <p class="summary">
                                周四(7月3日)亚市盘中，国际现货黄金价格暂时承压于1330美元/盎司下方。
                            </p>
                            <div>
                                <span class="time">2014年6月20号  12:24</span>
                                <a class="text-blue pull-right" data-action="delete">删除</a>
                            </div>
                        </li>
                        <li class="comment">
                            <a class="title" href="">彭博调查：多数黄金交易员及分析师看跌下周金价</a>
                            <p class="summary">
                                周四(7月3日)亚市盘中，国际现货黄金价格暂时承压于1330美元/盎司下方。黄金自6月份以来维持的涨势将面临今晚非农的层层考虑，同时晚间还将...
                            </p>
                            <div>
                                <span class="time">2014年6月20号  12:24</span>
                                <a class="text-blue pull-right" data-action="delete">删除</a>
                            </div>
                        </li>
                        <li class="comment">
                            <a class="title" href="">彭博调查：多数黄金交易员及分析师看跌下周金价，布伦特原油大涨，欧盟就严厉制裁俄罗斯新措施达成初步协议</a>
                            <p class="summary">
                                周四(7月3日)亚市盘中，国际现货黄金价格暂时承压于1330美元/盎司下方。黄金自6月份以来维持的涨势将面临今晚非农的层层考虑，同时晚间还将...
                            </p>
                            <div>
                                <span class="time">2014年6月20号  12:24</span>
                                <a class="text-blue pull-right" data-action="delete">删除</a>
                            </div>
                        </li>
                        <li class="comment">
                            <a class="title" href="">黄金暂时承压1330下方，等待非农消息</a>
                            <p class="summary">
                                周四(7月3日)亚市盘中，国际现货黄金价格暂时承压于1330美元/盎司下方。
                            </p>
                            <div>
                                <span class="time">2014年6月20号  12:24</span>
                                <a class="text-blue pull-right" data-action="delete">删除</a>
                            </div>
                        </li>
                        <li class="comment">
                            <a class="title" href="">彭博调查：多数黄金交易员及分析师看跌下周金价</a>
                            <p class="summary">
                                周四(7月3日)亚市盘中，国际现货黄金价格暂时承压于1330美元/盎司下方。黄金自6月份以来维持的涨势将面临今晚非农的层层考虑，同时晚间还将...
                            </p>
                            <div>
                                <span class="time">2014年6月20号  12:24</span>
                                <a class="text-blue pull-right" data-action="delete">删除</a>
                            </div>
                        </li>
                        <li class="comment">
                            <a class="title" href="">彭博调查：多数黄金交易员及分析师看跌下周金价，布伦特原油大涨，欧盟就严厉制裁俄罗斯新措施达成初步协议</a>
                            <p class="summary">
                                周四(7月3日)亚市盘中，国际现货黄金价格暂时承压于1330美元/盎司下方。黄金自6月份以来维持的涨势将面临今晚非农的层层考虑，同时晚间还将...
                            </p>
                            <div>
                                <span class="time">2014年6月20号  12:24</span>
                                <a class="text-blue pull-right" data-action="delete">删除</a>
                            </div>
                        </li>
                    </ul>
                    <div class="pagingbar">
                        <a class="button" href="">1</a>
                        <a class="button" href="">2</a>
                        <a class="button" href="">3</a>
                        <a class="button" href="">4</a>
                        <a class="button" href="">5</a>
                        <a class="button" href="">6</a>
                        <a class="button" href="">7</a>
                        <a class="button" href="">8</a>
                        <a class="button" data-action="prev-page" href="">下一页</a>
                    </div>
                </div>
                <div class="tab-pane" id="user-markets"></div>
                <div class="tab-pane" id="user-collect">
                    <ul class="news-list">
                        <li class="news">
                            <div class="clearfix">
                                <img class="img" src="/wscn/img/img-news.jpg" alt=""/>
                                <div class="content">
                                    <a class="title" href="">黄金暂时承压1330下方，等待非农消息</a>
                                    <p class="summary">
                                        因乌克兰及中东地区的地缘政治风险再次升温，打压美股及美债收益率下滑，国际金价周五临近收盘时迅速扩大涨幅逾1%,并最终收在1300美元上方。此外不少投资者周末前回补空头也是推动日内金价大涨的因素...
                                    </p>
                                </div>
                            </div>
                            <div class="clearfix">
                                <span class="time">2014年6月19号  23:24</span>
                                <span class="collect active"></span>
                            </div>
                        </li>
                        <li class="news">
                            <div class="clearfix">
                                <img class="img" src="/wscn/img/img-news.jpg" alt=""/>
                                <div class="content">
                                    <a class="title" href="">彭博调查：多数黄金交易员及分析师看跌下周金价，布伦特原油大涨，欧盟就严厉制裁俄罗斯新措施达成初步协议</a>
                                    <p class="summary">
                                        因乌克兰及中东地区的地缘政治风险再次升温，打压美股及美债收益率下滑，国际金价周五临近收盘时迅速扩大涨幅逾1%,并最终收在1300美元上方。此外不少投资者周末前回补空头也是推动日内金价大涨的因素...
                                    </p>
                                </div>
                            </div>
                            <div class="clearfix">
                                <span class="time">2014年6月19号  23:24</span>
                                <span class="collect active"></span>
                            </div>
                        </li>
                    </ul>
                    <ul class="news-list">
                        <li class="news">
                            <div class="clearfix">
                                <img class="img" src="/wscn/img/img-news.jpg" alt=""/>
                                <div class="content">
                                    <a class="title" href="">黄金暂时承压1330下方，等待非农消息</a>
                                    <p class="summary">
                                        因乌克兰及中东地区的地缘政治风险再次升温，打压美股及美债收益率下滑，国际金价周五临近收盘时迅速扩大涨幅逾1%,并最终收在1300美元上方。此外不少投资者周末前回补空头也是推动日内金价大涨的因素...
                                    </p>
                                </div>
                            </div>
                            <div class="clearfix">
                                <span class="time">2014年6月19号  23:24</span>
                                <span class="collect active"></span>
                            </div>
                        </li>
                        <li class="news">
                            <div class="clearfix">
                                <img class="img" src="/wscn/img/img-news.jpg" alt=""/>
                                <div class="content">
                                    <a class="title" href="">彭博调查：多数黄金交易员及分析师看跌下周金价，布伦特原油大涨，欧盟就严厉制裁俄罗斯新措施达成初步协议</a>
                                    <p class="summary">
                                        因乌克兰及中东地区的地缘政治风险再次升温，打压美股及美债收益率下滑，国际金价周五临近收盘时迅速扩大涨幅逾1%,并最终收在1300美元上方。此外不少投资者周末前回补空头也是推动日内金价大涨的因素...
                                    </p>
                                </div>
                            </div>
                            <div class="clearfix">
                                <span class="time">2014年6月19号  23:24</span>
                                <span class="collect active"></span>
                            </div>
                        </li>
                    </ul>
                    <ul class="news-list">
                        <li class="news">
                            <div class="clearfix">
                                <img class="img" src="/wscn/img/img-news.jpg" alt=""/>
                                <div class="content">
                                    <a class="title" href="">黄金暂时承压1330下方，等待非农消息</a>
                                    <p class="summary">
                                        因乌克兰及中东地区的地缘政治风险再次升温，打压美股及美债收益率下滑，国际金价周五临近收盘时迅速扩大涨幅逾1%,并最终收在1300美元上方。此外不少投资者周末前回补空头也是推动日内金价大涨的因素...
                                    </p>
                                </div>
                            </div>
                            <div class="clearfix">
                                <span class="time">2014年6月19号  23:24</span>
                                <span class="collect active"></span>
                            </div>
                        </li>
                        <li class="news">
                            <div class="clearfix">
                                <img class="img" src="/wscn/img/img-news.jpg" alt=""/>
                                <div class="content">
                                    <a class="title" href="">彭博调查：多数黄金交易员及分析师看跌下周金价，布伦特原油大涨，欧盟就严厉制裁俄罗斯新措施达成初步协议</a>
                                    <p class="summary">
                                        因乌克兰及中东地区的地缘政治风险再次升温，打压美股及美债收益率下滑，国际金价周五临近收盘时迅速扩大涨幅逾1%,并最终收在1300美元上方。此外不少投资者周末前回补空头也是推动日内金价大涨的因素...
                                    </p>
                                </div>
                            </div>
                            <div class="clearfix">
                                <span class="time">2014年6月19号  23:24</span>
                                <span class="collect active"></span>
                            </div>
                        </li>
                    </ul>
                    <ul class="news-list">
                        <li class="news">
                            <div class="clearfix">
                                <img class="img" src="/wscn/img/img-news.jpg" alt=""/>
                                <div class="content">
                                    <a class="title" href="">黄金暂时承压1330下方，等待非农消息</a>
                                    <p class="summary">
                                        因乌克兰及中东地区的地缘政治风险再次升温，打压美股及美债收益率下滑，国际金价周五临近收盘时迅速扩大涨幅逾1%,并最终收在1300美元上方。此外不少投资者周末前回补空头也是推动日内金价大涨的因素...
                                    </p>
                                </div>
                            </div>
                            <div class="clearfix">
                                <span class="time">2014年6月19号  23:24</span>
                                <span class="collect active"></span>
                            </div>
                        </li>
                        <li class="news">
                            <div class="clearfix">
                                <img class="img" src="/wscn/img/img-news.jpg" alt=""/>
                                <div class="content">
                                    <a class="title" href="">彭博调查：多数黄金交易员及分析师看跌下周金价，布伦特原油大涨，欧盟就严厉制裁俄罗斯新措施达成初步协议</a>
                                    <p class="summary">
                                        因乌克兰及中东地区的地缘政治风险再次升温，打压美股及美债收益率下滑，国际金价周五临近收盘时迅速扩大涨幅逾1%,并最终收在1300美元上方。此外不少投资者周末前回补空头也是推动日内金价大涨的因素...
                                    </p>
                                </div>
                            </div>
                            <div class="clearfix">
                                <span class="time">2014年6月19号  23:24</span>
                                <span class="collect active"></span>
                            </div>
                        </li>
                    </ul>
                    <div class="pagingbar">
                        <a class="button" href="">1</a>
                        <a class="button" href="">2</a>
                        <a class="button" href="">3</a>
                        <a class="button" href="">4</a>
                        <a class="button" href="">5</a>
                        <a class="button" href="">6</a>
                        <a class="button" href="">7</a>
                        <a class="button" href="">8</a>
                        <a class="button" data-action="prev-page" href="">下一页</a>
                    </div>
                </div>
                <div class="tab-pane active" id="user-info">
                    <nav class="leftbar">
                        <h3 class="title">个人资料</h3>
                        <a class="link active" href="">基本资料</a>
                        <a class="link" href="">安全密码</a>
                        <a class="link" href="">语言设置</a>
                        <a class="link" href="">账号绑定</a>
                    </nav>
                    <div class="main-content">
                        <h3 class="title">基本资料</h3>
                        <form action=""></form>
                    </div>
                </div>
                <div class="tab-pane" id="user-endorse"></div>
            </div>
        </div>
        <div class="foot"></div>
    </div>
    <div id="rightbar">
        <div class="side-ad">
            <img src="/wscn/img/side-img-1.jpg" alt="">
        </div>
        <ul class="custom-nav-tabs custom-row">
            <li class="col-custom-6 active">
                <a data-toggle="tab" href="#side-day-rank-news"><strong>日排行</strong></a>
            </li>
            <li class="col-custom-6 ">
                <a data-toggle="tab" href="#side-week-rank-news"><strong>周排行</strong></a>
            </li>
        </ul>
        <ul class="tab-content">
            <li class="tab-pane active" id="side-day-rank-news">
                <?$pager = $this->tag->component('post', array('status' => 'published', 'limit' => 10, 'order' => '-count'));$posts = $pager->items;?>
                <ul class="news-list with-number">
                    <?foreach($posts as $post):?>
                    <li class="news">
                        <a class="title" href="/node/<?=$post->id?>">
                            <strong><?=$post->title?></strong>
                        </a>
                    </li>
                    <?endforeach?>
                </ul>
            </li>
            <?$pager = $this->tag->component('post', array('status' => 'published', 'limit' => 10, 'order' => '-sort_order'));$posts = $pager->items;?>
            <li class="tab-pane " id="side-week-rank-news">
                <ul class="news-list with-number">
                    <?foreach($posts as $post):?>
                    <li class="news">
                        <a class="title" href="/node/<?=$post->id?>">
                            <strong><?=$post->title?></strong>
                        </a>
                    </li>
                    <?endforeach?>
                </ul>
            </li>
        </ul>
        <div class="side-ad">
            <img src="/wscn/img/side-img-1.jpg" alt="">
        </div>
    </div>
    <!-- rightbar end -->
</div>
