<div id="user" class="page-user">
    <h2 class="form-title">欢迎加入华尔街见闻</h2>
    <div class="custom-row">
        <div class="custom-span-1">
            <div class="row">
                <div class="col-md-8">

                    <form data-validate action="/login"  method="POST" novalidate="novalidate" role="form">
                        <label class="control-label">用户名或邮箱</label>
                        <div class="form-group has-feedback">
                            <input id="" type="text" name="identify" class="form-control" placeholder="" required>
                            <span class="glyphicon glyphicon-user form-control-feedback"></span>
                        </div>
                        <label class="control-label">密码</label>
                        <div class="form-group has-feedback">
                            <input type="password" name="password" class="form-control password-previewer" placeholder="" required>
                            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                        </div>
                        <div class="form-footer">
                            <div class="checkbox pull-left" style="width: 100px;">
                                <label>
                                    <input type="checkbox" name="remember"> 记住密码
                                </label>
                            </div>
                            <input name="__redirect" type="hidden" value="/" >
                            <button type="submit" class="custom-button pull-right">登录</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="custom-span-2">
            <h3 class="sub-title">使用社交帐号登录</h3>
            <a class="custom-button type-weibo size-fluid" href="/auth/request/weibo/oauth2" target="_blank">
                <i class="icontext icontext-weibo-md">微博帐号</i>
            </a>
            <a class="custom-button type-qq size-fluid" href="/auth/request/tencent/oauth2">
                <i class="icontext icontext-qq-md">QQ帐号</i>
            </a>
            <p>还没有帐号，<a href="/register" class="text-blue">去注册</a></p>
        </div>
    </div>
</div>
