<?$this->placeholder->block('title')->set("登录-华尔街见闻");?>
<?$this->placeholder->block('description')->set("欢迎来到华尔街见闻。华尔街见闻——中国最专业的金融资讯平台；直播外汇、期货、黄金、债券、证券等金融领域的实时新闻。华人投资者可以在这里获得最快速、最精准、最深入的全球财经资讯和市场行情。");?>
<?$this->placeholder->block('keywords')->set("登录,密码重置,新闻,资讯,外汇,期货,大宗商品,贵金属,黄金,股市,行情,数据,金融,理财");?>
<div id="auth" class="page-auth">
    <h2 class="form-title">登录华尔街见闻</h2>
    <div class="row">
        <div class="col-sm-7 col-lg-5">
            <?=$this->tag->flashOutput()?>
            <form data-validate action="/login"  method="POST" novalidate="novalidate" role="form">
                <label for="login-form-identify" class="control-label">用户名或邮箱</label>
                <div class="form-group has-feedback">
                    <input id="login-form-identify" type="text" name="identify" class="form-control" placeholder="用户名或邮箱" required
                           data-parsley-trigger="blur change"
                           data-parsley-minlength="4"
                           data-parsley-minlength-message="用户名最短4个字符"
                           data-parsley-pattern="^(?![0-9]+$)"
                           data-parsley-pattern-message="不支持纯数字用户名"
                            >
                    <span class="fa fa-user form-control-feedback"></span>
                </div>
                <a href="/session/forgot" class="pull-right">忘记密码?</a>
                <label for="login-form-password" class="control-label">密码 </label>
                <div class="form-group has-feedback">
                    <input id="login-form-password" type="password" name="password" class="form-control password-previewer" placeholder="密码" required
                           data-parsley-trigger="blur change"
                           data-parsley-minlength="6"
                           data-parsley-minlength-message="密码最短6位"
                           maxlength="26"
                           data-parsley-maxlength="26"
                           data-parsley-max-length="密码最长26位"
                            >
                    <span class="fa fa-lock form-control-feedback"></span>
                </div>
                <div class="form-footer">
                    <div class="checkbox pull-left" style="width: 100px;">
                        <label>
                            <input type="checkbox" name="remember"> 记住密码
                        </label>
                    </div>
                    <input name="__redirect" type="hidden" value="" >
                    <button type="submit" class="custom-button pull-right">登录</button>
                </div>
            </form>
        </div>
        <div class="col-sm-1 col-lg-2"></div>
        <div class="col-sm-4 col-lg-3">
            <div class="custom-span-2">
                <h3 class="sub-title">使用社交帐号登录</h3>
                <a class="custom-button type-weibo size-fluid" href="/auth/request/weibo/oauth2" target="_blank">
                    <span class="fa fa-weibo"></span>
                    微博帐号
                </a>
                <a class="custom-button type-qq size-fluid" href="/auth/request/tencent/oauth2" target="_blank">
                    <span class="fa fa-qq"></span>
                    QQ 帐号
                </a>
                <p>还没有帐号，<a href="/register" class="text-blue">去注册»</a></p>
            </div>
        </div>
    </div>
</div>
