<!-- slider -->
<div id="slider">
    <?$num=1;foreach($posts_top as $post_top):if($num>5){break;}?>
        <div>
            <a href="http://wallstreetcn.com/node/<?=$post_top->nid?>" target="_blank"><img src="<?=$this->tag->wscnThumb($post_top->file_managed_file_usage_uri, 'c_fill,w_320,h_180')?>"></a>
            <p><?=$post_top->node_title?></p>
        </div>
        <?$num=$num+1;
    endforeach;?>
</div>
<!-- slider -->

<ul class="news-list">
    <?foreach($posts as $post):?>
    <li class="news">
    <a href="http://wallstreetcn.com/node/<?=$post->nid?>" target="_blank">
        <img src="<?=$this->tag->wscnThumb($post->file_managed_file_usage_uri, 'c_fill,w_75,h_60')?>"/>
        <dl>
            <dd class="content"><?=$post->node_title?></dd>

            <dd class="source"><?=$this->tag->datetime($post->node_created)?></dd>
        </dl>
    </a>
    </li>
    <?endforeach;?>
</ul>
<br/>
<a class="news-more" data-action="show-info" href="/?page=<?=$page + 1?>">
    <span class="news-font">加载更多</span>	
</a>	
<br/><br/>
