<div id="main-content">

    <aside id="leftbar">
    <?=$this->partial("partial/sidebar", array('quotes' => $this->widget->actionHelper('widget', 'quotes')))?>
    </aside>

    <div id="wrapper">
        <div id="main" class="page-search">
            <?if($query['tid'] && !empty($tag)):?>
                <?$this->placeholder->block('title')->set($tag->tagName."新闻-华尔街见闻");?>
                <?$this->placeholder->block('intercept')->set("华尔街见闻——中国最专业的金融资讯平台；直播外汇、期货、黄金、债券、证券等金融领域的实时新闻。华人投资者可以在这里获得最快速、最精准、最深入的全球财经资讯和市场行情。以下是".$tag->tagName."相关新闻");?>
                <?$this->placeholder->block('keywords')->set($tag->tagName.",外汇,期货,大宗商品,贵金属,黄金,股市,行情,数据,金融,理财");?>
            <h2 class="search-title">
                标签为 <span class="text-blue"><?=$tag->tagName?></span> 的所有文章
            </h2>
            <?elseif($query['cid'] && !empty($category)):?>
                <?$this->placeholder->block('title')->set($category->categoryName."新闻-华尔街见闻");?>
                <?$this->placeholder->block('intercept')->set("华尔街见闻——中国最专业的金融资讯平台；直播外汇、期货、黄金、债券、证券等金融领域的实时新闻。华人投资者可以在这里获得最快速、最精准、最深入的全球财经资讯和市场行情。以下是".$category->categoryName."相关新闻");?>
                <?$this->placeholder->block('keywords')->set($category->categoryName.",外汇,期货,大宗商品,贵金属,黄金,股市,行情,数据,金融,理财");?>
            <h2 class="crumbs-title">
                <a href="/">首页</a>
                <span class="fa fa-angle-right"></span>
                <span class="sub">阅读分类 <?=$category->categoryName?></span>
            </h2>
            <?elseif($query['uid'] && !empty($author)):?>
                <?$authorTrue = $author->screenName ?: $author->username;$this->placeholder->block('intercept')->set("华尔街见闻——中国最专业的金融资讯平台；直播外汇、期货、黄金、债券、证券等金融领域的实时新闻。华人投资者可以在这里获得最快速、最精准、最深入的全球财经资讯和市场行情。以下文章来自编辑".$authorTrue);?>
                <?$this->placeholder->block('keywords')->set($author->screenName ?: $author->username.",外汇,期货,大宗商品,贵金属,黄金,股市,行情,数据,金融,理财");?>
            <h2 class="search-title">
                作者 <span class="text-blue"><?=$author->screenName ?: $author->username?></span> 的所有文章
            </h2>
            <?elseif($query['q']):?>
                <?$this->placeholder->block('title')->set($query['q']."新闻-华尔街见闻");?>
                <?$this->placeholder->block('intercept')->set("华尔街见闻——中国最专业的金融资讯平台；直播外汇、期货、黄金、债券、证券等金融领域的实时新闻。华人投资者可以在这里获得最快速、最精准、最深入的全球财经资讯和市场行情。以下是为您搜索出的".$query['q']."相关新闻");?>
                <?$this->placeholder->block('keywords')->set($query['q'].",外汇,期货,大宗商品,贵金属,黄金,股市,行情,数据,金融,理财");?>
            <form class="search-form" action="/search" novalidate="novalidate">
                <input class="search-field" type="text" value="<?=$this->escaper->escapeHtmlAttr($query['q'])?>"/>
                <button class="submit fa fa-search" type="submit"></button>
            </form>
            <h2 class="search-title">
                <span class="text-red"><?=$query['q']?></span> 的搜索结果
                <span class="pull-right">
                    约找到 <span class="text-red"><?=$pager->total_items?></span> 个结果
                </span>
            </h2>
            <?else:?>
            <h2 class="crumbs-title">
                <a href="/">首页</a>
                <span class="fa fa-angle-right"></span>
                <span class="sub">最新文章</span>
            </h2>
            <?endif?>

            <?if(0):?>
            <h6 style="line-height: 50px; color: #999;">样式一：</h6>
            <nav class="categories">
                <span class="title">阅读分类</span>
                <a class="item active" href="">头条</a>
                <a class="item" href="">编辑推荐</a>
                <span class="span"></span>
                <a class="item" href="">美国</a>
                <a class="item" href="">中国</a>
                <a class="item" href="">欧洲</a>
                <span class="span"></span>
                <a class="item" href="">市场</a>
                <a class="item" href="">经济</a>
                <a class="item" href="">央行</a>
                <a class="item" href="">公司</a>
            </nav>
            <h6 style="line-height: 50px; color: #999;">样式二：</h6>
           
            <h6 style="line-height: 50px; color: #999;">样式三：</h6>

            <h6 style="line-height: 50px; color: #999;">样式四：</h6>
            <?endif?>
            <?$posts = $pager->items;?>
            <ul class="news-list with-img" id="search-result">
                <?foreach($posts as $post):?>
                <li class="news">
                    <a href="<?=$post->getUrl()?>">
                        <img class="lazy img" src="/wscn/img/bg-img.gif" data-original="<?=$post->image ? $this->tag->thumb($post->image, 'c_fill,h_140,w_200') : '/img/article.jpg'?>" alt=""/>
                    </a>
                    <div class="content">
                        <a class="title" href="<?=$post->getUrl()?>"><?=$post->title?></a>
                        <div>
                            <span class="meta author">文 / <?=$post->user ? $post->user->username : '华尔街见闻'?></span>
                            <span class="meta time visible-lg-inline-block"><?=$this->tag->datetime($post->createdAt)?></span>
                                <span class="meta endorse pull-right">
                                    <i class="fa fa-thumbs-up"></i> 3
                                </span>
                        </div>
                        <div class="summary hidden-xxs">
                            <?if($post->summary):?>
                            <?=$post->getSummaryHtml()?>
                            <?else:?>
                            <?=\Eva\EvaEngine\Text\Substring::substrCn(strip_tags($post->getContentHtml()), 100);?>
                            <?endif?>
                        </div>
                    </div>
                </li>
                <?endforeach;?>
                <li class="center">
                    <?$this->partial("partial/paginator", array(
                    'pagerUrl' => '/news',
                    'pager' => $pager,
                    ))?>
                </li>
            </ul>
        </div>
        <div id="rightbar">
            <?if($tags):?>
            <div class="side-tags">
                <h3 class="title">
                    热门标签
                </h3>
                <?foreach($tags as $tag):?>
                <a class="tag" href="/news?tid=<?=$tag->id?>"><?=$tag->tagName?></a>
                <?endforeach?>
            </div>
            <?endif?>
        </div>
    </div><!--/wrapper-->
</div><!--/main content-->
