<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <title><?=$this->placeholder->block('title', '华尔街见闻第三方登录');?></title>
</head>
<body>
    <script>
        try {
                if(!window.opener) {
                    window.location.href = '<?=$this->url->get('/')?>';
                } else {
                    var error = <?=json_encode($error);?>;
                    var success = <?=json_encode($success);?>;
                    var token = <?=json_encode($token);?>;
                    var user = <?=json_encode($user);?>;
                    window.opener.UserLogin.getInstance().setOAuthResponse(token, user, success, error);
                }
            } catch(err) {
                console.log(err);
            }
            window.close();
        </script>
    </body>
</html>

