<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <title><?=$this->placeholder->block('title', '华尔街见闻第三方登录');?></title>
</head>
<body>
<script>
    //TODO: when opener closed
    if(!window.opener) {
    
    }
    var error = <?=json_encode($error);?>;
    var success = <?=json_encode($success);?>;
    var token = <?=json_encode($token);?>;
    var user = <?=json_encode($user);?>;
    if(success) {
            window.opener.usermanager.success(token, user);
    } else {
            window.opener.usermanager.error(error);
    }
    window.close();
</script>
</body>
</html>


