<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <title><?=$this->placeholder->block('title', '华尔街见闻第三方登录');?></title>
    <meta name="description" content="<?=$this->placeholder->block('description', '您现在所在的位置是第三方登录。华尔街见闻——中国最专业的金融资讯平台；直播外汇、期货、黄金、债券、证券等金融领域的实时新闻。华人投资者可以在这里获得最快速、最精准、最深入的全球财经资讯和市场行情。');?>">
    <meta name="keywords" content="<?=$this->placeholder->block('keywords', '第三方登录,外汇,期货,大宗商品,贵金属,黄金,股市,行情,数据,金融,理财')?>">
</head>
<body>
    <script>
        try {
                if(!window.opener) {
                    window.location.href = '<?=$this->url->get('/')?>';
                } else {
                    var error = <?=json_encode($error);?>;
                    var exception = <?=json_encode($exception);?>;
                    var token = <?=json_encode($token);?>;
                    var user = <?=json_encode($user);?>;
                    window.opener.UserLogin.getInstance().setOAuthResponse(token, user, error, exception);
                }
            } catch(err) {
                console.log(err);
            }
            window.close();
        </script>
    </body>
</html>

