<div>
    <?=$this->partial('partial/top')?>
    <div class="content-wrapper">
        <ul class="news-list">
            <?$posts = $pager->items;?>
            <?foreach($posts as $post):?>
            <li class="news">
            <a href="/node/<?=$post->id?>">
                <img src="<?=$post->image ? $this->tag->thumb($post->image, 'c_fill,h_60,w_75') : '/img/article.jpg'?>"/>
                <dl>
                    <dd class="content"><?=$post->title?></dd>

                    <dd class="source"><?=$this->tag->datetime($post->createdAt)?></dd>
                </dl>
            </a>
            </li>
            <?endforeach;?>
        </ul>
        <br/>
        <a class="news-more" data-action="show-info" href="/?page=<?=$pager->next?>">
            <span class="news-font">加载更多</span>	
        </a>	
        <br/><br/>
    </div>
    <?=$this->partial('partial/leftmenu')?>
    <?=$this->partial('partial/footer')?>
</div>
<?=$this->partial('partial/js')?>
<script type="text/javascript">
    $(document).on('click', '.news-more', function(){
            var loader = $(this);
            var link = $(this).attr('href');
            $.ajax({
                    url : link,
                    success : function(response){
                            var newpage = $(response);
                            $(".content-wrapper ul").append(newpage.find('.content-wrapper ul').html());
                            loader.attr('href', newpage.find('a.news-more').attr('href'));
                    }
            });
            return false;
    });
	
    gmu.Add2desktop({icon:'<?=$this->url->getStatic('/wscnm/img/bookmark.png')?>'}).show();
</script>
