<?
    $post = $keyword->entry;
    $this->placeholder->block('title')->set($keyword->keyword."-金融百科-华尔街见闻");
    $description = strip_tags($post->summary);
    $this->placeholder->block('description')->set($description);
    $this->placeholder->block('keywords')->set($keyword->keyword.",".$post->title.$post->getLinkedKeywords().",百科,wiki,金融术语,金融词汇,金融用语,解释,华尔街见闻");
?>
<div id="main-content" >
    <aside id="leftbar">
        <div class="sharebar">
            <a class="collect" href="">收藏</a>
<!--            <a class="discuss" href="#comments">评论-->
<!--                --><?//if($post->commentCount > 0):?>
<!--                （--><?//=$post->commentCount?><!--）-->
<!--                --><?//endif?>
<!--            </a>-->
            <!-- JiaThis Button BEGIN -->
            <div class="jiathis_style_32x32">
                <a class="jiathis_button_tsina">微博</a>
                <a class="jiathis_button_cqq">QQ</a>
                <a class="jiathis_button_weixin">微信</a>
                <a class="jiathis_button_evernote">印象笔记</a>
                <a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank">其它</a>
            </div>
            <script type="text/javascript" src="http://v3.jiathis.com/code/jia.js?uid=1393984262901745" charset="utf-8"></script>
            <!-- JiaThis Button END -->
        </div>
    </aside>
    <!-- leftbar end -->
    <div id="wrapper">
        <div id="main" class="page-article page-wiki">
            <article>
            <h1 class="article-title"><?=$post->title?></h1>
                <div>
                    <? if($post->title != $keyword->keyword): ?>
                    <span class="meta">你要查看的关键词「 <?=$keyword->keyword?> 」与「 <?=$post->title?> 」含义相同</span>
                    <? endif; ?>
<!--                    <span class="meta author">文 / --><?//=$post->user ? $post->user->username : '华尔街见闻'?><!--</span>-->
<!--                    <span class="meta time">--><?//=$this->tag->datetime($post->createdAt)?><!--</span>-->
<!--                    <div class="pull-right">-->
<!--                        --><?//if($post->sourceName):?>
<!--                        <span class="meta">来源：<a href="--><?//=$post->sourceUrl?><!--" target="_blank">--><?//=$post->sourceName?><!--</a></span>-->
<!--                        --><?//endif?>
<!--                        <a href="#comments"><span class="meta comment-count icontext icontext-discuss-blue">(--><?//=$post->commentCount > 0 ?: 0?><!--)</span></a>-->
<!--                    </div>-->
                </div>
                <?if($post->imageId):?>
                <img class="main-image lazy" src="/wscn/img/bg-img.gif" alt=""
                     data-original="<?=$post->thumbnail->imageWidth > 640 || $post->thumbnail->imageHeight > 350 ?
                     $this->tag->thumb($post->image, 'c_fill,h_350,w_640') : $this->tag->thumb($post->image)?>" />
                <?endif?>
                <div class="article-content">
<!--                    <aside class="related-posts">-->
<!--                        <h2 class="main-title">目录</h2>-->
<!--                        <ul class="news-list with-dot">-->
<!--                            <li class="news"><a class="title" href="">6月汇丰中国制造业PMI初值创7个月新高，黄金微涨</a></li>-->
<!--                            <li class="news"><a class="title" href="">证监会积极推动A股入MSCI，上交所认为大盘T+0条件成熟</a></li>-->
<!--                            <li class="news last-child"><a class="title" href="">MSCI将A股纳入市场意味着什么？</a></li>-->
<!--                        </ul>-->
<!--                    </aside>-->
                    <?=\Eva\Wiki\Utils\WikiUtil::highlight($post->getContentHtml(), array($post->title, $keyword->keyword))?>
                </div>
                <p class="statement">
                    在各大APP商店搜索“华尔街见闻”，可下载我们的移动客户端。
                    <br/>同时欢迎关注见闻微信号：wallstreetcn
                </p>
                <div class="toolbar">
                    <span class="endorse icontext icontext-endorse-blue">(132)</span>
                    <a class="collect" href=""></a>
                    <!-- JiaThis Button BEGIN -->
                    <div class="jiathis_style_32x32">
                        <span class="text">分享</span>
                        <a class="jiathis_button_tsina"></a>
                        <a class="jiathis_button_cqq"></a>
                        <a class="jiathis_button_weixin"></a>
                        <a class="jiathis_button_evernote"></a>
                        <a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank"></a>
                    </div>
                    <script type="text/javascript" src="http://v3.jiathis.com/code/jia.js?uid=1393984262901745" charset="utf-8"></script>
                    <!-- JiaThis Button END -->
                </div>


            </article>
            <h2 class="main-title">更多热点</h2>
            <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 2 ,'limit' => 6, 'has_image' => 1, 'order' => '-sort_order'));$posts = $pager->items;?>
            <ul class="hot-news row">
                <?foreach($posts as $post):?>
                <li class="col-lg-4 col-xs-6">
                    <a href="/node/<?=$post->id?>" class="news">
                        <img class="lazy full-width" src="/wscn/img/bg-img.gif" data-original="<?=$post->image ? $this->tag->thumb($post->image, 'c_fill,h_360,w_600') : '/img/article.jpg'?>" alt=""/>
                        <h3 class="title"><?=$post->title?></h3>
                    </a>
                </li>
                <?endforeach?>
            </ul>
            <h2 class="main-title">关键字阅读</h2>
            <ul class="custom-tabs">
                <li class="active"><a data-toggle="tab" href="#keyword-1">科技</a></li>
                <li><a data-toggle="tab" href="#keyword-2">华尔街</a></li>
                <li><a data-toggle="tab" href="#keyword-3">金融</a></li>
                <li><a data-toggle="tab" href="#keyword-4">沙龙</a></li>
            </ul>
            <div class="tab-content">
                <ul class="tab-pane active news-list with-dot" id="keyword-1">
                    <li class="news">
                        <a class="title" href="">中韩将签署货币直接交易协议，人民币国际化又落一子</a>
                    </li>
                </ul>
                <ul class="tab-pane news-list with-dot" id="keyword-2">
                    <li class="news">
                        <a class="title" href="">日本——“货币战”幕后真正发动者的替罪羊？</a>
                    </li>
                </ul>
                <ul class="tab-pane news-list with-dot" id="keyword-3">
                    <li class="news">
                        <a class="title" href="">韩国执政党呼吁加快韩元人民币直接兑换进程</a>
                    </li>
                </ul>
                <ul class="tab-pane news-list with-dot" id="keyword-4">
                    <li class="news">
                        <a class="title" href="">亚洲货币9月表现1997年以来最差</a>
                    </li>
                </ul>
            </div>
        </div>
        <div id="rightbar">
            <h3 class="side-title">
                <button class="custom-button type-link">最新文章</button>
            </h3>
            <ul class="news-list with-dot">
                <li class="news">
                    <a class="title" href="">
                        <strong>将股纳入新兴市场指数意味着什么？120亿美元入场，证监会积</strong>
                    </a>
                </li>
                <li class="news">
                    <a class="title" href="">
                        <strong>全球第二大产糖国新规：原糖进口税猛增167%</strong>
                    </a>
                </li>
                <li class="news">
                    <a class="title" href="">
                        <strong>中央出手救市落空？官媒抨击房地产唱空者“别有用心”</strong>
                    </a>
                </li>
                <li class="news">
                    <a class="title" href="">
                        <strong>日媒：中国大幅减持日债恐为向日施压</strong>
                    </a>
                </li>
                <li class="news">
                    <a class="title" href="">
                        <strong>南非史上最长罢工结束 铂金钯金双双下挫</strong>
                    </a>
                </li>
            </ul>
            <h2 class="main-title" style="margin-bottom: 5px;">实时行情</h2>
            <!-- Start: Wallstreetcn.com sidebar widget -->
            <div id="js-wscn-sidebar-wrapper" class="hidden-xxs" style="margin-bottom: 15px;"></div>
            <script src="http://markets.static.wallstreetcn.com/embed/sidebar.js" type='text/javascript'></script>

            <script type='text/javascript'>
                (function(){

                    // 插入的 iFrame 父节点
                    var parentId = 'js-wscn-sidebar-wrapper';
                    // iFrame 的 ID
                    var iframeId = 'js-wscn-sidebar-iframe';

                    var options = /*options*/{
                        "chart": {
                            "interval": "5"
                        },
                        "theme": "light",
                        "height": "430",
                        "width": "300",
                        "active": 0,
                        "tabs": [
                            {
                                "name": "综合",
                                "symbols": [
                                    "XAUUSD",
                                    "UKOil",
                                    "SPX500",
                                    "000001",
                                    "EURUSD",
                                    "USDJPY",
                                    "US10Year"
                                ]
                            },
                            {
                                "name": "外汇",
                                "symbols": [
                                    "EURUSD",
                                    "GBPUSD",
                                    "USDJPY",
                                    "USDCHF",
                                    "AUDUSD",
                                    "USDCAD",
                                    "USDollarIndex"
                                ]
                            },
                            {
                                "name": "期货",
                                "symbols": [
                                    "XAUUSD",
                                    "XAGUSD",
                                    "UKOil",
                                    "USOil",
                                    "Copper",
                                    "CORN",
                                    "WHEAT"
                                ]
                            },
                            {
                                "name": "股指",
                                "symbols": [
                                    "SPX500",
                                    "NAS100",
                                    "US30",
                                    "JPN225INDEX",
                                    "hkg33index",
                                    "UK100",
                                    "eustx50index"
                                ]
                            }
                        ]
                    }/*endOptions*/
                    var sidebar = new WallstreetCN.embed.Sidebar(parentId, options, iframeId);
                    sidebar.render();

                })();
            </script>
            <!-- End: Wallstreetcn.com sidebar widget -->
            <!--  -->
            <div class="side-ad">
                <img src="/wscn/img/side-img-1.jpg" alt=""/>
            </div>
            <!--  -->
            <ul class="custom-nav-tabs custom-row">
                <li class="col-custom-6 active">
                    <a data-toggle="tab" href="#side-day-rank-news"><strong>日排行</strong></a>
                </li>
                <li class="col-custom-6 ">
                    <a data-toggle="tab" href="#side-week-rank-news"><strong>周排行</strong></a>
                </li>
            </ul>
            <ul class="tab-content">
                <li class="tab-pane active" id="side-day-rank-news">
                    <ul class="news-list with-number">
                        <li class="news">
                            <a class="title" href="">
                                <strong>什么都怪房地产？别把中国经济想得太简单</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>德国放弃从美国运回黄金说明了什么？</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>微刺激发力 汇丰中国制造业PMI创七个月新高</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>今夏全球市场焦点——美国通胀是否已现？</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>对话中国顶尖对冲基金！见闻俱乐部第2期主题沙龙火热报名中</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>干旱席卷世界最大甘蔗产区 对冲基金押宝糖价上涨</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>金属骗贷调查泼冷水，铜市六周以来首现净空头</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>伦敦房地产泡沫比中国更大</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>“超级投资者”踏空牛市 谁是美股新高的缔造者？</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>一张图看懂中国为何需要微刺激</strong>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="tab-pane " id="side-week-rank-news">
                    <ul class="news-list with-number">
                        <li class="news">
                            <a class="title" href="">
                                <strong>今夏全球市场焦点——美国通胀是否已现？</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>对话中国顶尖对冲基金！见闻俱乐部第2期主题沙龙火热报名中</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>干旱席卷世界最大甘蔗产区 对冲基金押宝糖价上涨</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>什么都怪房地产？别把中国经济想得太简单</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>德国放弃从美国运回黄金说明了什么？</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>微刺激发力 汇丰中国制造业PMI创七个月新高</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>金属骗贷调查泼冷水，铜市六周以来首现净空头</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>伦敦房地产泡沫比中国更大</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>“超级投资者”踏空牛市 谁是美股新高的缔造者？</strong>
                            </a>
                        </li>
                        <li class="news">
                            <a class="title" href="">
                                <strong>一张图看懂中国为何需要微刺激</strong>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!--  -->

        </div>
    </div>
</div>
