<div id="auth" class="page-auth">
    <h2 class="form-title">欢迎加入华尔街见闻</h2>
    <div class="custom-row">
        <div class="custom-span-1">
            <div class="row">
                <div class="col-md-8">

                            <form data-validate action="/register"  method="POST" novalidate="novalidate" role="form">
                                <label>使用邮箱注册</label>
                                <div class="form-group has-feedback">
                                    <input type="email" name="email" class="form-control" placeholder="邮箱" required
                                        data-parsley-trigger="blur change"
                                        data-parsley-remote="/register/check"
                                        data-parsley-remote-options='{ method: "GET", dataType: "json"}'
                                        data-parsley-remote-message="输入的邮箱已被占用"
                                    >
                                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                                </div>
                                <div class="form-group has-feedback">
                                    <input type="text" name="username" class="form-control" placeholder="用户名" required
                                        data-parsley-trigger="blur change"
                                        data-parsley-type="alphanum"
                                        maxlength="24"
                                        data-parsley-minlength="4"
                                        data-parsley-minlength-message="用户名最短4个字符"
                                        data-parsley-maxlength="24"
                                        data-parsley-pattern="^(?![0-9]+$)"
                                        data-parsley-pattern-message="请不要使用纯数字作为用户名"
                                        data-parsley-remote="/register/check"
                                        data-parsley-remote-options='{ method: "GET", dataType: "json"}'
                                        data-parsley-remote-message="输入的用户名已被占用"
                                    >
                                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                                </div>
                                <div class="form-group has-feedback">
                                    <input type="password" name="password" class="form-control password-previewer" placeholder="密码" required
                                        data-parsley-trigger="blur change"
                                        data-parsley-minlength="6"
                                        data-parsley-minlength-message="密码最短6位"
                                        maxlength="26"
                                        data-parsley-maxlength="26"
                                        data-parsley-max-length="密码最长26位"
                                    >
                                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                                </div>
                                <div class="form-footer">
                                    <div class="checkbox pull-left" style="width: 150px;">
                                        <label>
                                            <input type="checkbox" name="agree" checked="checked" value="yes" required> 同意<a href="/page/terms" class="text-blue" target="_blank">使用条款</a>
                                        </label>
                                    </div>
                                    <button type="submit" class="custom-button pull-right">注册</button>
                                </div>

                            </form>
                </div>
            </div>
        </div>
        <div class="custom-span-2">
            <h3 class="sub-title">使用社交帐号注册</h3>
            <a class="custom-button type-weibo size-fluid" href="/auth/request/weibo/oauth2" target="_blank">
                <i class="icontext icontext-weibo-md">微博帐号</i>
            </a>
            <a class="custom-button type-qq size-fluid" href="/auth/request/tencent/oauth2" target="_blank">
                <i class="icontext icontext-qq-md">QQ帐号</i>
            </a>
            <p>已有帐号，<a href="/login" class="text-blue">去登录</a></p>
        </div>
    </div>
</div>
