<?$this->placeholder->block('title')->set("帐号注册-华尔街见闻");?>
<?$this->placeholder->block('description')->set("您现在所在的位置是帐号注册,欢迎加入华尔街见闻。华尔街见闻——中国最专业的金融资讯平台；直播外汇、期货、黄金、债券、证券等金融领域的实时新闻。华人投资者可以在这里获得最快速、最精准、最深入的全球财经资讯和市场行情。");?>
<?$this->placeholder->block('keywords')->set("华尔街见闻,外汇,期货,大宗商品,贵金属,黄金,股市,行情,数据,金融,理财");?>
<div id="auth" class="page-auth">
    <h2 class="form-title">欢迎加入华尔街见闻</h2>
    <div class="row">
        <div class="col-sm-7 col-lg-5">
            <form data-validate action="/register"  method="POST" novalidate="novalidate" role="form">
                <label for="register-form-email">邮箱</label>
                <div class="form-group has-feedback">
                    <input id="register-form-email" type="email" name="email" class="form-control" placeholder="" required
                           data-parsley-trigger="blur change"
                           data-parsley-remote="/register/check"
                           data-parsley-remote-options='{ method: "GET", dataType: "json"}'
                           data-parsley-remote-message="输入的邮箱已被占用"
                            >
                    <span class="fa fa-envelope form-control-feedback"></span>
                </div>
                <label for="register-form-username">用户名</label>
                <div class="form-group has-feedback">
                    <input id="register-form-username" type="text" name="username" class="form-control" placeholder="字母数字" required
                           data-parsley-trigger="blur change"
                           data-parsley-type="alphanum"
                           maxlength="24"
                           data-parsley-minlength="4"
                           data-parsley-minlength-message="用户名最短4个字符"
                           data-parsley-maxlength="24"
                           data-parsley-pattern="^(?![0-9]+$)"
                           data-parsley-pattern-message="请不要使用纯数字作为用户名"
                           data-parsley-remote="/register/check"
                           data-parsley-remote-options='{ method: "GET", dataType: "json"}'
                           data-parsley-remote-message="输入的用户名已被占用"
                            >
                    <span class="fa fa-user form-control-feedback"></span>
                </div>
                <label for="register-form-password">密码</label>
                <div class="form-group has-feedback">
                    <input id="register-form-password" type="password" name="password" class="form-control password-previewer" placeholder="6位以上密码" required
                           data-parsley-trigger="blur change"
                           data-parsley-minlength="6"
                           data-parsley-minlength-message="密码最短6位"
                           maxlength="26"
                           data-parsley-maxlength="26"
                           data-parsley-max-length="密码最长26位"
                            >
                    <span class="fa fa-lock form-control-feedback"></span>
                </div>
                <div class="form-footer">
                    <div class="checkbox pull-left" style="width: 150px;">
                        <label>
                            <input type="checkbox" name="agree" checked="checked" value="yes" required> 同意<a href="/page/terms" class="text-blue" target="_blank">使用条款</a>
                        </label>
                    </div>
                    <button type="submit" class="custom-button pull-right">注册</button>
                </div>

            </form>
        </div>
        <div class="col-sm-1 col-lg-2"></div>
        <div class="col-sm-4 col-lg-3">
            <div class="custom-span-2">
                <h3 class="sub-title">使用社交帐号注册</h3>
                <a class="custom-button type-weibo size-fluid" href="/auth/request/weibo/oauth2" target="_blank">
                    <span class="fa fa-weibo"></span>
                    微博帐号
                </a>
                <a class="custom-button type-qq size-fluid" href="/auth/request/tencent/oauth2" target="_blank">
                    <span class="fa fa-qq"></span>
                    QQ 帐号
                </a>
                <p>已有帐号，<a href="/login" class="text-blue">去登录»</a></p>
            </div>
        </div>

    </div>
</div>
