<style type="text/css">

		body > div {
			background-color:#f7f7f7;
			height:100%;
		}
		
		a:hover {
			text-decoration: none;
		}
		
		.btn[data-action=to-share]{
			border:none;
			cursor:pointer;
		}
		
</style>
<div>
    <?=$this->partial('partial/top_single')?>
    <div class="content-wrapper">

        <div class="news-info">
            <h2 class="title"><?=$post->title?></h2>
            <div class="meta">
                <span class="item author">文 / <?=$post->user ? $post->user->username : '华尔街见闻'?></span>
                <span class="item time"><?=$this->tag->datetime($post->createdAt)?></span>
                <div class="btn" data-action="to-share" style="">
                    <img src="/wscnm/img/whitestar.png" class="favorite"/>
                </div>
            </div>
            <div class="content">
                <?=$post->getContentHtml()?>
            </div>
            <div class="sharebar">
                <span class="item label">分享：</span>
                <a class="item btn tsina" href="http://www.jiathis.com/send/?webid=tsina&amp;url=http://<?=$this->config->wscnmobile->domain?>/node/<?=$post->id?>" target="_blank"></a>
                <a class="item btn tqq" href="http://www.jiathis.com/send/?webid=tqq&amp;url=http://<?=$this->config->wscnmobile->domain?>/node/<?=$post->id?>" target="_blank"></a>
                <a class="item btn cqq" href="http://www.jiathis.com/send/?webid=cqq&amp;url=http://<?=$this->config->wscnmobile->domain?>/node/<?=$post->id?>" target="_blank"></a>
                <a class="item btn evernote" href="http://www.jiathis.com/send/?webid=evernote&amp;url=http://<?=$this->config->wscnmobile->domain?>/node/<?=$post->id?>" target="_blank"></a>
            </div>

        </div>
		
    </div>
    <?=$this->partial('partial/footer')?>
</div>
<?=$this->partial('partial/js')?>
<script type="text/javascript" src="/wscnm/js/wscn_util.js"></script>
<script type="text/javascript">
	var redirect = WSCN_UTIL.url.parseQueryString()["redirect"];
	if(redirect && (redirect + "") == "1"){
		if(WSCN_UTIL.browser.iOS()){
			document.location.href = "wscn-zeus://www.wallstreetcn.com/detail/?id=<?=$post->id?>";
		}
		else if(WSCN_UTIL.browser.android()){
			document.location.href = "wscn-medusa://www.wallstreetcn.com/detail/?id=<?=$post->id?>";
		}
	}
</script>




