<!DOCTYPE html>
<html>
    <head>
        <title><?=$this->placeholder->block('title', '华尔街见闻移动版');?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
        <?=$this->partial('partial/head')?>
    </head>
    <body>

        <?=$this->getContent()?>

        <!--
        <script type="text/javascript" src="/wscnm/js/marketdetail.js" data-desc="depend on wscn_util.js & store.js"></script>
        <script type="text/javascript">  
            WSCN_UTIL.mobile.detectOrientation();
        </script> 

        -->


        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-19303398-2']);
            _gaq.push(['_setDomainName', '.wallstreetcn.com']);
            _gaq.push(['_trackPageview']);

            (function() {
                    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>    
        <script>
            var _hmt = _hmt || [];
            (function() {
                var hm = document.createElement("script");
                hm.src = "//hm.baidu.com/hm.js?c9477ef9d8ebaa27c94f86cc3f505fa5";
                var s = document.getElementsByTagName("script")[0]; 
                s.parentNode.insertBefore(hm, s);
            })();
        </script>
    </body>
</html>

