<div id="main-content">
<aside id="leftbar">
    <div class="sharebar">
        <a class="collect not-stared" href="" data-action="star" data-post-id="<?= $news->id ?>" data-message="登录后收藏">
            <span class="fa fa-star"></span>
            收藏
        </a>
        <a class="discuss" href="#comments">
            <span class="fa fa-comment"></span>
            评论
            <? if ($news->commentCount > 0): ?>
                （<span class="ws-counter"><?= $news->commentCount ?></span>）
            <? endif ?>
        </a>

        <div class="read-times">
            <strong>12.3K</strong>

            <div class="text">浏览数</div>
        </div>
        <h3 class="jiathis-title">
            分享到
        </h3>
        <!-- JiaThis Button BEGIN -->
        <div class="jiathis_style_32x32">
            <a class="jiathis_button_tsina">
                <span class="fa fa-weibo"></span>
                微博
            </a>
            <a class="jiathis_button_cqq">
                <span class="fa fa-qq"></span>
                QQ
            </a>
            <a class="jiathis_button_weixin">
                <span class="fa fa-weixin"></span>
                微信
            </a>
            <a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank">
                <span class="fa fa-plus"></span>
                其它
            </a>
        </div>
        <!--<script type="text/javascript" src="http://v3.jiathis.com/code/jia.js?uid=1393984262901745" charset="utf-8"></script>-->
        <!-- JiaThis Button END -->
    </div>
</aside>
<!-- leftbar end -->
<div id="wrapper">
<div id="main" class="page-article">
    <article>
        <h1 class="article-title"><?= $news->title ?></h1>

        <div class="meta">
            <a class="item author" href="">文 / <?= $news->user ? $news->user->username : '华尔街见闻' ?></a>
            <span class="item time"><?= $this->tag->datetime($news->createdAt) ?></span>
            <a class="item" href="#comments">
                <span class="fa fa-comment" style="vertical-align: 1px"></span>
                <span class="ws-counter"><?= $news->commentCount > 0 ? : 0 ?></span>
            </a>
            <div class="pull-right">
                <? if ($news->sourceName): ?>
                    <span class="item">来源：<a href="<?= $news->sourceUrl ?>"
                                             target="_blank"><?= $news->sourceName ?></a></span>
                <? endif ?>

            </div>
        </div>
        <? if ($news->imageId): ?>
            <img class="main-image lazy" src="/wscn/img/bg-img.gif" alt=""
                 data-original="<?=
                 $news->thumbnail->imageWidth > 640 || $news->thumbnail->imageHeight > 350 ?
                     $this->tag->thumb($news->image, 'c_fill,h_350,w_640') : $this->tag->thumb($news->image)?>"/>
        <? endif ?>
        <div class="article-content">
            <?= $news->getContentHtml() ?>
        </div>


        <div id="content-extra" class="article-content">
        <?if($news->text && $news->text->contentExtra):?>
        <?=$news->text->contentExtra?>
        <?endif?>

        <?if($news->text && $news->text->contentFollowup):?>
        <h3>追踪报道</h3>
        <?=$news->text->contentFollowup?>
        <?endif?>

        <?if($news->text && $news->text->contentAnalysis):?>
        <h3>市场反应</h3>
        <?=$news->text->contentAnalysis?>
        <?endif?>
        </div>

        <p class="statement">
            在各大APP商店搜索“华尔街见闻”，可下载我们的移动客户端。
            <br/>同时欢迎关注见闻微信号：wallstreetcn
        </p>

        <div class="toolbar">
            <a class="collect" href="">
                <span class="fa fa-star"></span>
            </a>
            <a class="endorse">
                <span class="fa fa-thumbs-up"></span>
                132
            </a>
            <!-- JiaThis Button BEGIN -->
            <div class="jiathis_style_32x32">
                <span class="title">分享到 </span>
                <a class="jiathis_button_tsina">
                    <span class="fa fa-weibo"></span>
                    <span class="text">新浪微博</span>
                </a>
                <a class="jiathis_button_weixin">
                    <span class="fa fa-weixin"></span>
                    <span class="text">微信朋友圈</span>
                </a>
                <a class="jiathis_button_cqq">
                    <span class="fa fa-qq"></span>
                    <span class="text">腾讯 QQ</span>
                </a>
                <a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jtico jtico_jiathis"
                   target="_blank">
                    <span class="fa fa-plus"></span>
                </a>
            </div>
            <script type="text/javascript">
                <?
                    $summary= trim(preg_replace('/\s+/', ' ', strip_tags($news->summary)));
                ?>
                var jiathis_config = {
                    summary: "<?=$summary?>",
                    title: "<?=$summary ? $news->title.'：' : $news->title?>",
                    pic: "<?=$this->tag->thumb($news->image)?>",
                    appkey: {
                        <?
                            $appKeysCount = count($appKeys4share);
                            $appKeysIteratorI = 0;
                        ?>
                        <?foreach($appKeys4share as $_name => $_v):?>
                        "<?=$_name?>": "<?=$_v?>"<?= ++$appKeysIteratorI < $appKeysCount ? ',' :'' ?>
                        <?endforeach;?>
                    },
                    shortUrl: false
                }
            </script>
            <script type="text/javascript" src="http://v3.jiathis.com/code/jia.js?uid=1393984262901745"
                    charset="utf-8"></script>
            <!-- JiaThis Button END -->
        </div>


    </article>

    <div id="comments">
        <? if ($news->commentStatus == 'open'): ?>
            <? $this->partial('partial/comment', array('uniqueKey' => 'livenews_' . $news->id)); ?>
        <? endif ?>
    </div>

</div>
<div id="rightbar">

    <h2 class="side-title">实时行情</h2>
    <!-- Start: Wallstreetcn.com sidebar widget -->
    <div id="js-wscn-sidebar-wrapper" class="hidden-xxs"></div>
    <script src="http://markets.static.wallstreetcn.com/embed/sidebar.js" type='text/javascript'></script>
    <script type='text/javascript'>
        (function () {
            var parentId = 'js-wscn-sidebar-wrapper';
            var iframeId = 'js-wscn-sidebar-iframe';
            var options = /*options*/{
                "chart": {
                    "interval": "5"
                },
                "theme": "gray",
                "height": "430",
                "width": "300",
                "active": 0,
                "tabs": [
                    {
                        "name": "综合",
                        "symbols": [
                            "XAUUSD",
                            "UKOil",
                            "SPX500",
                            "000001",
                            "EURUSD",
                            "USDJPY",
                            "US10Year"
                        ]
                    },
                    {
                        "name": "外汇",
                        "symbols": [
                            "EURUSD",
                            "GBPUSD",
                            "USDJPY",
                            "USDCHF",
                            "AUDUSD",
                            "USDCAD",
                            "USDollarIndex"
                        ]
                    },
                    {
                        "name": "期货",
                        "symbols": [
                            "XAUUSD",
                            "XAGUSD",
                            "UKOil",
                            "USOil",
                            "Copper",
                            "CORN",
                            "WHEAT"
                        ]
                    },
                    {
                        "name": "股指",
                        "symbols": [
                            "SPX500",
                            "NAS100",
                            "US30",
                            "JPN225INDEX",
                            "hkg33index",
                            "UK100",
                            "eustx50index"
                        ]
                    }
                ]
            }
            /*endOptions*/
            var sidebar = new WallstreetCN.embed.Sidebar(parentId, options, iframeId);
            sidebar.render();
        })();
    </script>
    <!-- End: Wallstreetcn.com sidebar widget -->
    <!--  -->
    <div class="side-ad">
        <img src="/wscn/img/side-img-1.jpg" alt=""/>
    </div>
    <!--  -->
    <h2 class="side-title" style="margin-bottom: 0;">热门阅读</h2>
    <!--  -->
    <? $pager = $this->tag->component(
        'post',
        array('status' => 'published', 'cid' => 2, 'limit' => 6, 'has_image' => 1, 'order' => '-sort_order')
    );
    $newss = $pager->items; ?>
    <ul class="hot-news">
        <? foreach ($newss as $hotpost): ?>
            <li>
                <a href="<?= $hotpost->getUrl() ?>" class="news">
                    <img class="lazy img" src="/wscn/img/bg-img.gif"
                         data-original="<?=
                         $hotpost->image ? $this->tag->thumb(
                             $hotpost->image,
                             'c_fill,h_115,w_193'
                         ) : '/img/article.jpg' ?>" alt=""/>
                    <strong class="title"><?= $hotpost->title ?></strong>
                </a>
            </li>
        <? endforeach ?>
    </ul>
</div>
</div>
</div>
