<div id="main-content" class="columns-2">
    <div id="main" class="page-livenews">
        <?$newsPager = $this->tag->component('post', array('status' => 'published', 'limit' => 10, 'order' => '-created_at'));$posts = $newsPager->items;?>
        <?if($posts):?>
        <div class="topbar hidden-xs hidden-xxs">
            <a href="/news" class="custom-button type-link absolute">最新文章</a>
            <div class="control-box">
                <span class="left  glyphicon glyphicon-chevron-left" data-action="left"></span>
                <span class="right glyphicon glyphicon-chevron-right" data-action="right"></span>
            </div>
            <div id="news-list" class="news-list with-dot">
                <div class="row content">
                    <?foreach($posts as $post):?>
                    <div class="col-lg-6">
                        <a class="news" href="<?=$post->getUrl()?>" target="_blank">
                            <strong><?=$post->title?></strong>
                        </a>
                    </div>
                    <?endforeach?>
                </div>
            </div>
        </div>
        <?endif?>

        <div class="checkbox-group">
            <span class="title">筛选今日新闻：</span>
            <label class="custom-checkbox">
                <input type="checkbox" name="cc">
                <i class="fa"></i>
                <span class="text">重要新闻</span>
            </label>
            <label class="custom-checkbox">
                <input type="checkbox" name="cc">
                <i class="fa"></i>
                <span class="text">中国</span>
            </label>
            <label class="custom-checkbox">
                <input type="checkbox" name="cc">
                <i class="fa"></i>
                <span class="text">美国</span>
            </label>
            <label class="custom-checkbox">
                <input type="checkbox" name="cc">
                <i class="fa"></i>
                <span class="text">外汇</span>
            </label>
            <label class="custom-checkbox">
                <input type="checkbox" name="cc">
                <i class="fa"></i>
                <span class="text">股市</span>
            </label>
            <label class="custom-checkbox">
                <input type="checkbox" name="cc">
                <i class="fa"></i>
                <span class="text">经济数据</span>
            </label>
            <span class="more active">
                更多筛选 <i class="fa"></i>
            </span>

            <label class="switch-box pull-right" data-toggle="switch">
                <span class="icon"></span>
                <span class="text">声音提醒</span>
                <input type="checkbox" name="cc">
                <span class="box"></span>
            </label>

            <div class="more-content active">
                <span class="title">
                    资产类别：
                </span>
                <label class="custom-checkbox">
                    <input type="checkbox" name="cc">
                    <i class="fa"></i>
                    <span class="text">外汇</span>
                </label>
                <label class="custom-checkbox">
                    <input type="checkbox" name="cc">
                    <i class="fa"></i>
                    <span class="text">股市</span>
                </label>
                <label class="custom-checkbox">
                    <input type="checkbox" name="cc">
                    <i class="fa"></i>
                    <span class="text">商品</span>
                </label>
                <label class="custom-checkbox">
                    <input type="checkbox" name="cc">
                    <i class="fa"></i>
                    <span class="text">债卷市场</span>
                </label>
                <hr class="hr"/>
                <span class="title">
                    地区：
                </span>
                <label class="custom-checkbox">
                    <input type="checkbox" name="cc">
                    <i class="fa"></i>
                    <span class="text">中国</span>
                </label>
                <label class="custom-checkbox">
                    <input type="checkbox" name="cc">
                    <i class="fa"></i>
                    <span class="text">美国</span>
                </label>
                <label class="custom-checkbox">
                    <input type="checkbox" name="cc">
                    <i class="fa"></i>
                    <span class="text">欧元区</span>
                </label>
                <label class="custom-checkbox">
                    <input type="checkbox" name="cc">
                    <i class="fa"></i>
                    <span class="text">英国</span>
                </label>
                <label class="custom-checkbox">
                    <input type="checkbox" name="cc">
                    <i class="fa"></i>
                    <span class="text">日本</span>
                </label>
                <label class="custom-checkbox">
                    <input type="checkbox" name="cc">
                    <i class="fa"></i>
                    <span class="text">加拿大</span>
                </label>
                <label class="custom-checkbox">
                    <input type="checkbox" name="cc">
                    <i class="fa"></i>
                    <span class="text">澳洲</span>
                </label>
                <label class="custom-checkbox">
                    <input type="checkbox" name="cc">
                    <i class="fa"></i>
                    <span class="text">瑞士</span>
                </label>
                <label class="custom-checkbox">
                    <input type="checkbox" name="cc">
                    <i class="fa"></i>
                    <span class="text">其他地区</span>
                </label>
                <hr class="hr"/>
                <span class="title">
                    宏观信息：
                </span>
                <label class="custom-checkbox">
                    <input type="checkbox" name="cc">
                    <i class="fa"></i>
                    <span class="text">重要新闻</span>
                </label>
                <label class="custom-checkbox">
                    <input type="checkbox" name="cc">
                    <i class="fa"></i>
                    <span class="text">央行</span>
                </label>
                <label class="custom-checkbox">
                    <input type="checkbox" name="cc">
                    <i class="fa"></i>
                    <span class="text">经济数据</span>
                </label>
                <hr class="hr"/>
                <span class="title">
                    其他：
                </span>
                <label class="custom-checkbox">
                    <input type="checkbox" name="cc">
                    <i class="fa"></i>
                    <span class="text">见闻早餐</span>
                </label>
            </div>
            <hr class="hr"/>
            <span class="title">您已选择：</span>
            <span class="tag">
                <i class="fa fa-times-circle"></i>
                重要新闻
            </span>
            <span class="tag">
                <i class="fa fa-times-circle"></i>
                美国
            </span>
        </div>

        <ul id="livenews-list">
            <li class="news">

            </li>
        </ul>

        <!--  -->
        <div id="livenews-box" style="display: none">
            <div class="header">
                <div class="clearfix">
                    <button class="custom-button config glyphicon glyphicon-cog" data-action="config"></button>
                    <label class="switch-box" data-toggle="switch">
                        <span class="icon"></span>
                        <span class="text">声音提醒</span>
                        <input type="checkbox" name="cc">
                        <span class="box"></span>
                    </label>
                </div>

            </div>
            <div class="body">
                <ul class="content">
                    <?$lastday = ''?>
                    <?foreach($pager->items as $item): //type-img  //type-video?>
                    <?$currentday = $this->tag->datetime($item->createdAt, 'Y-m-d')?>
                    <?if(!$lastday || $currentday !== $lastday):?>
                    <li class="date"><?=$this->tag->datetime($item->createdAt, 'Y年m月d日')?></li>
                    <?endif?>
                    <?$lastday = $currentday?>

                    <?if($item->codeType == 'markdown' || $item->codeType == 'html'):?>
                    <li class="news">
                    <span class="icon"></span>
                    <span class="time"><?=$this->tag->datetime($item->createdAt, 'H:i')?></span>
                    <div class="content">
                        <?=$item->getContentHtml()?>
                    </div>
                    <div class="footer">
                        <span class="meta">
                            <i class="icontext icontext-collect-blue"></i>
                        </span>
                        <span class="meta">
                            <i class="icontext icontext-share-blue"></i>
                        </span>
                        <span class="meta">
                            <i class="icontext icontext-discuss-blue"></i>&nbsp;32
                        </span>
                    </div>
                    </li>
                    <?else:?>
                    <?endif?>

                    <?endforeach?>
                    <li class="news type-img">
                    <span class="icon"></span>
                    <span class="time">10:35</span>
                    <div class="content">
                        黄金亚太午盘跳水，跌幅近1.20%。【工行一级资本和总资产蝉联宇宙第一大行】英国《银行家》正式公布了2014年度的全球1000家大银行排名榜单。
                        <div class="thumb"></div>
                    </div>
                    <div class="footer">
                        <span class="meta">
                            <i class="icontext icontext-collect-blue"></i>
                        </span>
                        <span class="meta">
                            <i class="icontext icontext-share-blue"></i>
                        </span>
                        <span class="meta">
                            <i class="icontext icontext-discuss-blue"></i>&nbsp;32
                        </span>
                    </div>
                    </li>
                    <li class="news type-video">
                    <span class="icon"></span>
                    <span class="time">10:35</span>
                    <div class="content">
                        阿里携7银行推无抵押贷款：最高授信1000万；为中小企业启动基于网商信用的无抵押贷款计划，最高授信可达1000万元。业内人士认为，这一业务可被看作阿里银行主营业务的雏形。
                        <div class="thumb"></div>
                    </div>
                    <div class="footer">
                        <span class="meta">
                            <i class="icontext icontext-collect-blue"></i>
                        </span>
                        <span class="meta">
                            <i class="icontext icontext-share-blue"></i>
                        </span>
                        <span class="meta">
                            <i class="icontext icontext-discuss-blue"></i>&nbsp;32
                        </span>
                    </div>
                    </li>
                    <li class="news type-data" data-trend="rise">
                    <span class="icon"></span>
                    <div class="important">
                        <i class="glyphicon glyphicon-star star active"></i>
                        <i class="glyphicon glyphicon-star star active"></i>
                        <i class="glyphicon glyphicon-star star"></i>
                    </div>
                    <div class="content">
                        <span class="time">10:35</span>
                        <img  class="flag" src="" alt=""/>
                        <h3 class="title">
                            <span class="country">英国</span>6月英国BRC同店零售销售 (年率)
                        </h3>
                        <div class="custom-row">
                            <div class="col-custom-4">
                                <span class="text">今值：</span>
                                <span class="value current">1.1%</span>
                            </div>
                            <div class="col-custom-4">
                                <span class="text">预测：</span>
                                <span class="value">1.0%</span>
                            </div>
                            <div class="col-custom-4">
                                <span class="text">前值：</span>
                                <span class="value">0.5%</span>
                            </div>
                        </div>
                        <div class="verdict">利多金银</div>
                    </div>
                    <div class="footer">
                        <span class="meta">
                            <i class="icontext icontext-collect-blue"></i>
                        </span>
                        <span class="meta">
                            <i class="icontext icontext-share-blue"></i>
                        </span>
                        <span class="meta">
                            <i class="icontext icontext-discuss-blue"></i>&nbsp;32
                        </span>
                    </div>
                    </li>
                    <li class="news type-data" data-trend="fall">
                    <span class="icon"></span>
                    <div class="important">
                        <i class="glyphicon glyphicon-star star active"></i>
                        <i class="glyphicon glyphicon-star star active"></i>
                        <i class="glyphicon glyphicon-star star active"></i>
                    </div>
                    <div class="content">
                        <span class="time">10:35</span>
                        <img  class="flag" src="" alt=""/>
                        <h3 class="title">
                            <span class="country">日本</span>5月所有产业活动指数月率
                        </h3>
                        <div class="custom-row">
                            <div class="col-custom-4">
                                <span class="text">今值：</span>
                                <span class="value current">-0.8%</span>
                            </div>
                            <div class="col-custom-4">
                                <span class="text">预测：</span>
                                <span class="value">1.0%</span>
                            </div>
                            <div class="col-custom-4">
                                <span class="text">前值：</span>
                                <span class="value">0.5%</span>
                            </div>
                        </div>
                        <div class="verdict">利空金银</div>
                    </div>
                    <div class="footer">
                        <span class="meta">
                            <i class="icontext icontext-collect-blue"></i>
                        </span>
                        <span class="meta">
                            <i class="icontext icontext-share-blue"></i>
                        </span>
                        <span class="meta">
                            <i class="icontext icontext-discuss-blue"></i>&nbsp;32
                        </span>
                    </div>
                    </li>
                </ul>
                <?$this->partial("partial/paginator", array(
                    'pagerUrl' => '/livenews',
                    'pager' => $pager,
                ))?>
            </div>
            <!-- body end -->
        </div>
    </div>
    <div id="rightbar">
        <h2 class="main-title">实时行情</h2>
        <!-- Start: Wallstreetcn.com sidebar widget -->
        <div id="js-wscn-sidebar-wrapper" class="hidden-xxs" style="margin-bottom: 15px;"></div>
        <script src="http://markets.static.wallstreetcn.com/embed/sidebar.js" type='text/javascript'></script>

        <script type='text/javascript'>
            (function(){

                // 插入的 iFrame 父节点
                var parentId = 'js-wscn-sidebar-wrapper';
                // iFrame 的 ID
                var iframeId = 'js-wscn-sidebar-iframe';

                var options = /*options*/{
                    "chart": {
                        "interval": "5"
                    },
                    "theme": "light",
                    "height": "430",
                    "width": "300",
                    "active": 0,
                    "tabs": [
                    {
                        "name": "综合",
                        "symbols": [
                        "XAUUSD",
                        "UKOil",
                        "SPX500",
                        "000001",
                        "EURUSD",
                        "USDJPY",
                        "US10Year"
                        ]
                    },
                    {
                        "name": "外汇",
                        "symbols": [
                        "EURUSD",
                        "GBPUSD",
                        "USDJPY",
                        "USDCHF",
                        "AUDUSD",
                        "USDCAD",
                        "USDollarIndex"
                        ]
                    },
                    {
                        "name": "期货",
                        "symbols": [
                        "XAUUSD",
                        "XAGUSD",
                        "UKOil",
                        "USOil",
                        "Copper",
                        "CORN",
                        "WHEAT"
                        ]
                    },
                    {
                        "name": "股指",
                        "symbols": [
                        "SPX500",
                        "NAS100",
                        "US30",
                        "JPN225INDEX",
                        "hkg33index",
                        "UK100",
                        "eustx50index"
                        ]
                    }
                    ]
                }/*endOptions*/
                var sidebar = new WallstreetCN.embed.Sidebar(parentId, options, iframeId);
                sidebar.render();

            })();
        </script>
        <!-- End: Wallstreetcn.com sidebar widget -->
        <!--  -->
        <div class="side-ad">
            <img src="/wscn/img/side-img-1.jpg" alt=""/>
        </div>
        <h2 class="main-title">财经日历</h2>
        <div id="side-fcl" class="nano fc-list type-side" data-fcl-option="time-format: HH:mm a;height: 400;autoScroll:true;refreshPrice:true;filter:fd;">
            <div class="titlebar">
                据 <a href="" data-action="scroll-fixed">下次数据</a> 公布时间还有：<span class="clock"></span>
            </div>
            <ul class="nano-content content">
                <li class="more"></li>
            </ul>
            <script type="text/template" data-template>
                <% for(var i=0; i<records.length; i++) { %>
                <% var record = records[i]; %>
                <% if (i == 0 || record.date.charAt(9) != records[i-1].date.charAt(9)) { %>
                <li class="date" data-date="<%= record.date %>"><%= record.date %></li>
                <% } %>
                <li id="<%= record.id %>" class="item" data-cid="<%= record.cid %>" data-trend="<%= record.trend %>" data-utm="<%= record.utm %>">
                <div class="custom-row">
                    <div class="col-custom-4 time"><%= record.time %></div>
                    <div class="col-custom-8 important" data-value="<%= record.importance %>"><%= record.stars %></div>
                </div>
                <div class="custom-row">
                    <span class="col-custom-4 country"><%= record.country %></span>
                    <a    class="col-custom-8 title" href=""><%= record.title %></a>
                </div>
                <div class="custom-row">
                    <div class="col-custom-4 price actual">
                        <span class="text">今值：</span>
                        <span class="value"><%= record.actual %></span>
                    </div>
                    <div class="col-custom-4 price forecast">
                        <span class="text">预测：</span>
                        <span class="value"><%= record.forecast %></span>
                    </div>
                    <div class="col-custom-4 price previous">
                        <span class="text">前值：</span>
                        <span class="value"><%= record.previous %></span>
                    </div>
                </div>
                </li>
                <% } %>
            </script>
            <div class="loader">
                <img class="indicator" src="/img/loader.gif" width="100" height="100" alt=""/>
            </div>
        </div>
        <!--finance-calendar list end-->
    </div>
    <!-- rightbar end -->
</div>
