<div id="main-content" class="columns-2 page-livenews">
    <div id="main">
        <div class="topbar">
            <a href="" class="custom-button type-link absolute">最新文章</a>
            <div class="control-box">
                <span class="left glyphicon glyphicon-chevron-left"></span>
                <span class="right glyphicon glyphicon-chevron-right"></span>
            </div>
            <div class="news-list with-dot">
                <div class="row">
                    <div class="col-sm-6">
                        <a class="news" href="">
                            <strong>什么都怪房地产？别把中国经济想得太简单</strong>
                        </a>
                    </div>
                    <div class="col-sm-6">
                        <a class="news" href="">
                            <strong>德国放弃从美国运回黄金说明了什么？</strong>
                        </a>
                    </div>
                    <div class="col-sm-6">
                        <a class="news" href="">
                            <strong>微刺激发力 汇丰中国制造业PMI创七个月新高</strong>
                        </a>
                    </div>
                    <div class="col-sm-6">
                        <a class="news" href="">
                            <strong>今夏全球市场焦点——美国通胀是否已现？</strong>
                        </a>
                    </div>
                    <div class="col-sm-6">
                        <a class="news" href="">
                            <strong>对话中国顶尖对冲基金！见闻俱乐部第2期主题沙龙火热报名中</strong>
                        </a>
                    </div>
                    <div class="col-sm-6">
                        <a class="news" href="">
                            <strong>干旱席卷世界最大甘蔗产区 对冲基金押宝糖价上涨</strong>
                        </a>
                    </div>
                    <div class="col-sm-6">
                        <a class="news" href="">
                            <strong>金属骗贷调查泼冷水，铜市六周以来首现净空头</strong>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div id="livenews-box">
            <div class="header">
                <div class="clearfix">
                    <button class="custom-button config glyphicon glyphicon-cog" data-action="config"></button>
                    <div class="custom-switch" data-toggle="switch">
                        <span class="icon"></span>
                        <span class="text">声音提醒</span>
                        <span class="key"></span>
                    </div>
                </div>
            </div>
            <ul class="body">
                <li class="date">2014年7月15号  09:30:24</li>
                <li class="news">
                    <div class="content">
                        <span class="icon"></span>
                        <span class="time">10:35</span>
                        上海高校毕业生就业签约超七成，自主创业增加上海市教委：2014年上海高校毕业生就业签约率为 72.24%，预计到8月底，总体就业率将与去年同期持平。此外，目前上海高校总共有828名毕业生选择自主创业，同比增加70.7%。
                    </div>
                    <div class="footer">
                        <span class="meta">
                            <i class="icontext icontext-collect-blue"></i>
                        </span>
                        <span class="meta">
                            <i class="icontext icontext-share-blue"></i>
                        </span>
                        <span class="meta">
                            <i class="icontext icontext-discuss-blue"></i>&nbsp;32
                        </span>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <div id="rightbar">
        <h2 class="main-title">实时行情</h2>
        <!-- Start: Wallstreetcn.com sidebar widget -->
        <div id="js-wscn-sidebar-wrapper" style="margin-bottom: 15px;"></div>
        <script src="http://markets.static.wallstreetcn.com/embed/sidebar.js" type='text/javascript'></script>

        <script type='text/javascript'>
            (function(){

                // 插入的 iFrame 父节点
                var parentId = 'js-wscn-sidebar-wrapper';
                // iFrame 的 ID
                var iframeId = 'js-wscn-sidebar-iframe';

                var options = /*options*/{
                    "chart": {
                        "interval": "5"
                    },
                    "theme": "light",
                    "height": "430",
                    "width": "300",
                    "active": 0,
                    "tabs": [
                        {
                            "name": "综合",
                            "symbols": [
                                "XAUUSD",
                                "UKOil",
                                "SPX500",
                                "000001",
                                "EURUSD",
                                "USDJPY",
                                "US10Year"
                            ]
                        },
                        {
                            "name": "外汇",
                            "symbols": [
                                "EURUSD",
                                "GBPUSD",
                                "USDJPY",
                                "USDCHF",
                                "AUDUSD",
                                "USDCAD",
                                "USDollarIndex"
                            ]
                        },
                        {
                            "name": "期货",
                            "symbols": [
                                "XAUUSD",
                                "XAGUSD",
                                "UKOil",
                                "USOil",
                                "Copper",
                                "CORN",
                                "WHEAT"
                            ]
                        },
                        {
                            "name": "股指",
                            "symbols": [
                                "SPX500",
                                "NAS100",
                                "US30",
                                "JPN225INDEX",
                                "hkg33index",
                                "UK100",
                                "eustx50index"
                            ]
                        }
                    ]
                }/*endOptions*/
                var sidebar = new WallstreetCN.embed.Sidebar(parentId, options, iframeId);
                sidebar.render();

            })();
        </script>
        <!-- End: Wallstreetcn.com sidebar widget -->
        <!--  -->
        <div class="side-ad">
            <img src="/wscn/img/side-img-1.jpg" alt=""/>
        </div>
    </div>
</div>