<?$newsPager = $this->tag->component('post', array('status' => 'published', 'limit' => 3, 'q' => $query['q'], 'order' => '-created_at'));$posts = $newsPager->items;?>
<?if($posts->count() > 0):?>
<h3 class="side-title">
    相关新闻
    <a a class="more" href="/news?q=<?=$query['q']?>">更多»</a>
</h3>
<ul class=" news-list with-dot">
    <?foreach($posts as $post):?>
    <li class="news">
    <a class="title" href="<?=$post->getUrl()?>"><?=$post->title?></a>
    </li>
    <?endforeach?>
</ul>
<?endif?>

<?$items = $pager->items;?>
<?if($items->count() > 0):?>
<h3 class="side-title" style="margin-bottom: 2px">
    实时新闻
    <a class="more" href="/livenews">更多»</a>
</h3>
<ul id="left-side-livenews" class="livenews-list size-sm">
    <?foreach($items as $item):?>
    <li class="news">
        <span class="time"><?=$this->tag->datetime($item->createdAt, 'H:i')?></span>
        <div class="content">
            <?=str_replace("\n", '<br />', strip_tags($item->getContentHtml()))?>
            <div class="sign"></div>
        </div>
    </li>
    <?endforeach?>
</ul>
<?endif?>
