<style>
    .md-preview {
        overflow:auto;
    }
</style>
<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
        <li>
        <i class="icon-home home-icon"></i>
        <a href="/admin/dashboard">Home</a>
        </li>

        <li>
        <a href="/admin/livenews/news">Live News</a>
        </li>

        <li class="active">Finance Data</li>
    </ul><!-- .breadcrumb -->

    <div class="nav-search" id="nav-search">
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                <i class="icon-search nav-search-icon"></i>
            </span>
        </form>
    </div><!-- #nav-search -->
</div>

<form id="" action="" method="POST" enctype="multipart/form-data" novalidate="novalidate">
    <div class="page-content">
        <div class="row">
            <div class="col-xs-9"><!-- PAGE CONTENT BEGINS -->
                <div class="widget-box transparent">
                    <div class="widget-header">
                        <h3>Finance Data</h3>
                        <div class="widget-toolbar no-border">
                            <button type="submit" class="btn btn-info btn-medium">
                                <i class="icon-ok"></i>
                                Publish All
                            </button>
                            <input name="__redirect" type="hidden" value="" />

                        </div>
                    </div>

                    <div class="widget-body">

                        <div class="widget-main no-padding">
                            <div class="tab-content padding-4">
                                <div class="tab-pane in active" id="livenews-tab-basic">
                                    <div class="row">
                                        <div class="col-xs-12">

                                            <div class="widget-box hide">
                                                <div class="widget-header widget-header-small header-color-blue">
                                                    <div class="widget-toolbar no-border">
                                                    </div>
                                                </div>

                                                <div class="widget-body">
                                                    <div class="widget-main no-padding">
                                                        <?=$form->render('id', array())?>
                                                        <?=$form->render('content', array(
                                                            'rows' => 6,
                                                            'placeholder' => 'News Content',
                                                            'required' => 'required',
                                                        ))?>
                                                        <?=$form->render('codeType', array(
                                                            'value' => 'json'
                                                        ))?>
                                                    </div>
                                                </div>
                                            </div><!--widget box end-->

                                            <table class="table table-striped table-bordered table-hover finance-data-reporter">
                                                <thead>
                                                    <tr>
                                                        <th>Data Name
                                                            <button id="reporter-sync" class="btn btn-xs btn-info" type="button">
                                                                <i class="icon-coffee"></i>
                                                            </button>
                                                        </th>
                                                        <th>Time</th>
                                                        <th>Importance</th>
                                                        <th>Country</th>
                                                        <th>Forecast</th>
                                                        <th>Previous</th>
                                                        <th>Actual</th>
                                                        <th> 
                                                            <button id="reporter-cleaner" class="btn btn-xs btn-danger" type="button">
                                                                <i class="icon-trash"></i>
                                                            </button>
                                                        </th>
                                                    </tr>
                                                </thead>

                                                <tbody>
                                                    <?for($i=0; $i < 5; $i++):?>
                                                    <tr class="finance-data-row">
                                                        <td>
                                                            <input type="text" class="form-control" placeholder="" data-name="title">
                                                        </td>
                                                        <td>
                                                            <input type="text" class="form-control " data-show-seconds="false" placeholder="" data-name="timestamp">
                                                        </td>
                                                        <td>
                                                            <input type="number" class="form-control input-small" placeholder="" value="1"  data-name="importance">
                                                        </td>
                                                        <td>
                                                            <select class="form-control select2 input-medium" data-name="country" >
                                                                <option value="-1">选择国家</option>
                                                                <option value="美国">美国|USD</option><option value="欧元区">欧元区|EUR</option><option value="德国">德国|EUR</option><option value="日本">日本|JPY</option><option value="法国">法国|EUR</option><option value="英国">英国|GBP</option><option value="西班牙">西班牙|EUR</option><option value="意大利">意大利|EUR</option><option value="中国">中国|CNY</option><option value="加拿大">加拿大|CAD</option><option value="中国台北">中国台北|TWD</option><option value="南非">南非|ZAR</option><option value="印度">印度|INR</option><option value="印度尼西亚">印度尼西亚|IDR</option><option value="巴西">巴西|BRL</option><option value="挪威">挪威|NOK</option><option value="新加坡">新加坡|SGD</option><option value="澳大利亚">澳大利亚|AUD</option><option value="泰国">泰国|THB</option><option value="瑞士">瑞士|CHF</option><option value="纽西兰">纽西兰|NZD</option><option value="韩国">韩国|KRW</option><option value="香港">香港|HKD</option><option value="马来西亚">马来西亚|MYR</option>
                                                            </select>
                                                        </td>
                                                        <td>
                                                            <input type="text" class="form-control" placeholder="" data-name="forecast">
                                                        </td>
                                                        <td>
                                                            <input type="text" class="form-control" placeholder="" data-name="previous">
                                                        </td>
                                                        <td>
                                                            <input type="text" class="form-control" placeholder="" data-name="actual">
                                                        </td>
                                                        <td>
                                                            <button type="button" class="btn btn-xs btn-info">
                                                                Publish
                                                            </button>
                                                        </td>
                                                    </tr>
                                                    <?endfor?>
                                                </tbody>
                                            </table>

                                            <div class="widget-box">
                                                <div class="widget-header widget-header-small">
                                                    <h5 class="lighter">Categories</h5>
                                                    <span class="widget-toolbar">
                                                        <a data-action="collapse" href="#">
                                                            <i class="icon-chevron-up"></i>
                                                        </a>
                                                    </span>
                                                </div>
                                                <div class="widget-body">
                                                    <div class="widget-main">
                                                        <div class="control-group">
                                                            <?$categories = $form->getCategories()?>
                                                            <?if($categories):?>
                                                            <?foreach($categories as $key => $category):?>
                                                            <div class="checkbox" style="display:inline-block;width:110px;">
                                                                <label>
                                                                    <?=$category->render(array(
                                                                        'class' => 'ace',
                                                                    ))?>
                                                                    <span class="lbl"> <?=$category->getLabel()?></span>
                                                                </label>
                                                            </div>
                                                            <?endforeach?>
                                                            <?endif?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div><!--widgex box-->


                                            <div class="row">
                                                <div class="col-xs-4">
                                                    <div class="form-group">
                                                        <div>
                                                            <label for="importance">Importance</label>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-xs-2">
                                                                <?=$form->render('importance', array(
                                                                    'class' => 'form-control',
                                                                ))?>
                                                            </div>
                                                            <div class="col-xs-10">
                                                                <div id="importance-slider" class="help-block" data-slider-for="#importance"></div>
                                                            </div>
                                                        </div>
                                                    </div><!--form group-->
                                                </div>
                                                <div class="col-xs-4">
                                                    <div>
                                                        <label for="day">Day</label>
                                                    </div>
                                                    <div class="input-group">
                                                        <input id="day" name="day" type="text" data-date-format="yyyy-mm-dd" class="form-control date-picker" placeholder="Day" value="<?=empty($item->createdAt) ? '' : $this->tag->datetime($item->createdAt, 'Y-m-d')?>">
                                                        <span class="input-group-addon">
                                                            <i class="icon-calendar bigger-110"></i>
                                                        </span>
                                                    </div>
                                                </div>
                                                <div class="col-xs-4">
                                                    <div>
                                                        <label for="day">Time</label>
                                                    </div>
                                                    <div class="input-group bootstrap-timepicker">
                                                        <input id="time" name="time" type="text" class="form-control time-picker" placeholder="Time" value="<?=empty($item->createdAt) ? '' : $this->tag->datetime($item->createdAt, 'H:i:s')?>">
                                                        <span class="input-group-addon">
                                                            <i class="icon-time bigger-110"></i>
                                                        </span>
                                                        <?=$form->render('createdAt', array(
                                                        ))?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div><!--col end-->
                                    </div><!--row end-->

                                </div><!--tab pane end-->


                            </div><!--tab content end-->
                        </div><!--widget main end-->
                    </div><!--widget body end-->
                </div><!--widget box end-->


            </div><!--col left end-->
            <div class="col-xs-3">
                <div class="widget-box">
                    <div class="widget-header widget-header-small">
                        <h5 class="lighter">Recent News</h5>
                        <span class="widget-toolbar">
                            <a data-action="collapse" href="#">
                                <i class="icon-chevron-up"></i>
                            </a>
                        </span>
                    </div>

                    <div class="widget-body">
                        <div id="embed-livenews" class="widget-main">

                        </div>
                    </div>
                </div><!--widgex box-->
            </div><!-- /.col right -->
        </div><!--row end-->
    </div><!-- /.page-content -->
</form>

<script type="text/javascript" src="/vendor/js/bootstrap-markdown/js/bootstrap-markdown.js"></script>
<script type="text/javascript" src="/assets/js/jquery.slimscroll.min.js"></script>
<script>
    $(document).ready(function(){
            var updateCreateTime = function(){
                    var day = $('input[name=day]').val();
                    var time = $('input[name=time]').val();
                    time = time.length == 7 ? '0' + time : time;
                    var timestamp = moment(day + ' ' + time).format('X');
                    $('input[name=createdAt]').val(timestamp);
            }
            $('input[name=day], input[name=time]').on('change', updateCreateTime);

            var slider = $( "#importance-slider" );
            slider.css('width', slider.parent().width()).css('margin-top', '10px').slider({
                    value:1,
                    range: "min",
                    min: 1,
                    max: 5,
                    step: 1,
                    slide: function( event, ui ) {
                            var val = parseInt(ui.value);
                            $(slider.attr('data-slider-for')).val(val);
                    }
            });

            $('.wysiwyg').ckeditor();


            //Markdown Editor init 
            var textCounter = function(e) {
                    var textarea = e.$textarea;
                    var counter = $(textarea.attr('data-counter-selector'));
                    var content = e.getContent();
                    var contentLength = content.length;
                    counter.html(1000 - contentLength);
                    if (contentLength > 1000) {
                            counter.removeClass('label-danger label-success').addClass('label-danger');
                        } else {
                            counter.removeClass('label-danger label-success').addClass('label-success');
                    }
            }
            var markdownEditor = {};
            $("#content").markdown({
                    autofocus:true,
                    onShow: function(e){
                            markdownEditor = e;
                            e.$textarea.css('resize','vertical');
                            textCounter(e);
                        }, 
                        onChange:function(e){
                                textCounter(e);
                        }
                });

                //Finance data reporter init
                var reporter = $('.finance-data-reporter');

                var lockEditor = function(){
                        markdownEditor.disableButtons('all');
                        markdownEditor.$textarea.attr('readonly','readonly');
                }
                var unlockEditor = function(){
                        markdownEditor.enableButtons('all');
                        markdownEditor.$textarea.removeAttr('readonly');

                }
                var setFinanceData = function() {
                        var codeType = $('input[name=codeType]').val();
                        if(codeType != 'json') {
                                return false;
                        }
                        var jsonString = markdownEditor.getContent();
                        var data = $.parseJSON(jsonString);
                        if(!data || data.length < 1) {
                                return false;
                        }
                        for(var i in data) {
                                var row = reporter.find('.finance-data-row').eq(i);
                                for(var key in data[i]) {
                                        row.find("[data-name='" + key + "']").val(data[i][key]);
                                }
                        }
                        lockEditor();
                }

                var updateFinanceData = function(){
                        var codeType = $('input[name=codeType]').val();
                        if(codeType != 'json' && markdownEditor.getContent().length > 0) {
                                if(!confirm('Finance data will overwrite news content, are you sure?')) {
                                        return false;
                                }
                        }

                        var data = [];
                        reporter.find('.finance-data-row').each(function(){
                                var row = $(this);
                                var res = {};
                                row.find("*[data-name]").each(function(){
                                        var column = $(this);
                                        res[column.attr('data-name')] = column.val();
                                });
                                if(res.title != '') {
                                        data.push(res);
                                }

                        });



                        if(data.length > 0) {
                                markdownEditor.setContent(JSON.stringify(data));
                                $('input[name=codeType]').val('json');
                            } else {
                                markdownEditor.setContent('');
                        }
                        lockEditor();
                }

                var removeFinanceData = function(){
                        if(!confirm("All finance data will be removed, are you sure?")) {
                                return false;
                        }
                        markdownEditor.setContent('');
                        $('input[name=codeType]').val('markdown');
                        unlockEditor();
                        $('#editor-switcher a[href=#report-news]').tab('show')
                }

                var initReporter = function(){
                        if(!reporter[0]) {
                                return;
                        }
                        var urlHash = window.location.hash.substr(1);
                        var newsId = $('input[name=id]').val();
                        newsId = newsId == '' ? 0 : parseInt(newsId);
                        var codeType = $('input[name=codeType]').val();
                        if(newsId > 0 && codeType == 'json' || urlHash == 'report-data') {
                                $('#editor-switcher a[href=#report-data]').tab('show')
                                setFinanceData();
                        }


                        if(newsId < 1) {
                                var timestamp = parseInt(moment().format('X'));
                                var next15Min = timestamp + (60 * 15 - timestamp % (60 * 15));
                                var nextTime = moment.unix(next15Min).format('hh:mm');
                                reporter.find('input[data-name=timestamp]').each(function(){
                                        $(this).val(nextTime);
                                });
                        }
                        reporter.find('input[data-name=timestamp]').timepicker({
                                minuteStep: 5,
                                showMeridian: false
                        });

                        //bind events at last
                        reporter.on('change', 'input, select', updateFinanceData);
                        $("#reporter-cleaner").on('click', removeFinanceData);
                }
                initReporter();

                var loadLivenews = function(){
                        $("#embed-livenews").load('/admin/livenews/news/embed', function(){
                                $(this).slimScroll({
                                        height: $(window).height() - 150,
                                        alwaysVisible : true
                                });
                                $(this).find('time').each(function(){
                                        var time = $(this);
                                        time.html(moment(time.attr("datetime") * 1000).fromNow());
                                });
                        });
                }
                loadLivenews();




        });
    </script>
