<?
$url = '/thread/'.$thread->uniqueKey.'/comments/save';
$url .= $parent ? '?parentId='.$parent->id : '';
$parentId = $parent ? $parent->id : '';
?>
<div class="ws-reply-box">
    <div class="ws-avatar">
        <img src="/wscn/img/avatar-md.png" alt="ikk">
    </div>
    <?
    echo $this->tag->form(array($url,
        'method'=>'post',
        'class'=>'ws_comment_comment_new_form ws_comment_comment_reply_form',
        'data-parent'=>$parentId))
    ?>
        <textarea class="input" name="content" rows="3"></textarea>
        <input class="submit btn btn-primary" type="submit" value="回复"/>
    </form>
</div>
