<!---- comment begin -->
<? $this->assets->collection('header')
                ->addCss('/wscn/css/comment.css') ?>
<div class="user-comments" id="comments" data-ws-thread="<?=$uniqueKey?>"></div>

<?
$this->assets->collection('footer')
            ->addJs('/wscn/js/comments.js');

$script = <<<HTML
<script type="text/javascript">
    $(function() {
        $('#comments').ws_comments();
    });
</script>

HTML;
$this->placeholder->block('script')->set($script);

?>
<!---- comment end   -->
