<?$pagerBaseQuery = $pager->query;?>
<?if($pager->total_pages > 1):?>
<div class="pagination">
    <?if($pager->current > 2):?>
    <li><a class="button" href="<?=$this->tag->uri($pagerUrl, array('page' => $pager->first), $pagerBaseQuery)?>"><i class="glyphicon glyphicon-backward"></i></a></li>
    <?endif?>
    <?if($pager->current > 1):?>
    <li><a class="button" href="<?=$this->tag->uri($pagerUrl, array('page' => $pager->before), $pagerBaseQuery)?>"><i class="glyphicon glyphicon-chevron-left"></i></a></li>
    <?endif?>
    <?if(0 && $pager->prev_skip):?>
    <li><a class="button" href="javascript:;">...</a></li>
    <?endif?>
    <?if($pager->prev_range):?>
    <?foreach($pager->prev_range as $page):?>
    <li><a class="button" href="<?=$this->tag->uri($pagerUrl, array('page' => $page), $pagerBaseQuery)?>"><?=$page?></a></li>
    <?endforeach?>
    <?endif?>
    <li><a class="button active" href="<?=$this->tag->uri($pagerUrl, array('page' => $pager->current), $pagerBaseQuery)?>"><?=$pager->current?></a></li>
    
    <?if($pager->next_range):?>
    <?foreach($pager->next_range as $page):?>
    <li><a class="button" href="<?=$this->tag->uri($pagerUrl, array('page' => $page), $pagerBaseQuery)?>"><?=$page?></a></li>
    <?endforeach?>
    <?endif?>
    <?if(0 && $pager->next_skip):?>
    <li><a class="button" href="javascript:;">...</a></li>
    <?endif?>
    <?if($pager->next && $pager->current < $pager->last):?>
    <li><a class="button" href="<?=$this->tag->uri($pagerUrl, array('page' => $pager->next), $pagerBaseQuery)?>"><i class="glyphicon glyphicon-chevron-right"></i></a></li>
    <?endif?>
    <?if($pager->current < $pager->last):?>
    <li><a class="button" href="<?=$this->tag->uri($pagerUrl, array('page' => $pager->last), $pagerBaseQuery)?>"><i class="glyphicon glyphicon-forward"></i></a></li>
    <?endif?>
</div>
<?endif?>
