<div id="main-content">

    <aside id="leftbar">
        <?=$this->partial("partial/sidebar", array('quotes' => $this->widget->actionHelper('widget', 'quotes')))?>
    </aside>
    <div id="wrapper">
        <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 4 ,'limit' => 3, 'has_image' => 1, 'order' => '-sort_order'));$posts = $pager->items;?>

        <!--  -->
        <div id="index-top-news">
            <?$posts->valid(); $post = $posts->current();?>
            <?if($post):?>
            <a class="top1 cover-img" href="<?=$post->getUrl()?>">
                <img class="lazy img" src="/wscn/img/bg-img.gif" data-original="<?=$post->image ? $this->tag->thumb($post->image, 'c_fill,h_300,w_426') : '/img/article.jpg'?>" alt=""/>
                <div class="cover">
                    <h3 class="title"><?=$post->title?></h3>
                    <!--
                    <h4 class="subtitle">MSCI将A股纳入新兴市场指数意味着什么？120亿美元入场</h4>
                    -->
                </div>
            </a>
            <?endif?>
            <?$posts->valid(); $post = $posts->current();?>
            <?if($post):?>
            <a class="top2 cover-img" href="<?=$post->getUrl()?>">
                <img class="lazy img" src="/wscn/img/bg-img.gif" data-original="<?=$post->image ? $this->tag->thumb($post->image, 'c_fill,h_149,w_212') : '/img/article.jpg'?>" alt=""/>
                <div class="cover">
                    <h3 class="title"><?=$post->title?></h3>
                </div>
            </a>
            <?endif?>
            <?$posts->valid(); $post = $posts->current();?>
            <?if($post):?>
            <a class="top3 cover-img" href="<?=$post->getUrl()?>">
                <img class="lazy img" src="/wscn/img/bg-img.gif" data-original="<?=$post->image ? $this->tag->thumb($post->image, 'c_fill,h_149,w_212') : '/img/article.jpg'?>" alt=""/>
                <div class="cover">
                    <h3 class="title"><?=$post->title?></h3>
                </div>
            </a>
            <?endif?>

            <ul class="content">
                <li class="head">
                    头条新闻
                </li>
                <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 4 ,'limit' => 3, 'has_image' => 1, 'order' => '-sort_order'));$posts = $pager->items;?>
                <?$posts->valid(); $post = $posts->current();?>
                <?if($post):?>
                <li class="news visible-xxs visible-xs">
                    <a class="title" href="<?=$post->getUrl()?>">
                        <strong><?=$post->title?></strong>
                    </a>
                </li>
                <?endif?>
                <?$posts->valid(); $post = $posts->current();?>
                <?if($post):?>
                <li class="news visible-xxs visible-xs">
                    <a class="title" href="<?=$post->getUrl()?>">
                        <strong><?=$post->title?></strong>
                    </a>
                </li>
                <?endif?>
                <?$posts->valid(); $post = $posts->current();?>
                <?if($post):?>
                <li class="news hidden-lg">
                    <a class="title" href="<?=$post->getUrl()?>">
                        <strong><?=$post->title?></strong>
                    </a>
                </li>
                <?endif?>

                <!--  -->

                <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 4 ,'limit' => 6, 'page' => 2, 'has_image' => 1, 'order' => '-sort_order'));$posts = $pager->items;?>
                <?foreach($posts as $post):?>
                <li class="news">
                    <a class="title" href="<?=$post->getUrl()?>">
                        <strong><?=$post->title?></strong>
                    </a>
                </li>
                <?endforeach?>
            </ul>
        </div>

        <div id="main" class="page-index">

            <ul class="custom-nav-tabs">
                <li class="active"><a data-toggle="tab" data-trigger="lazyload" href="#main-news">最新文章</a></li>
                <!--<li><a data-toggle="tab" href="#main-hot-news">热门排行</a></li>-->
                <li><a data-toggle="tab" data-trigger="lazyload" href="#main-recommend-news">编辑推荐</a></li>
                <!--
                <li><a data-toggle="tab" href="#main-special-news">专栏专访</a></li>
                -->
            </ul>
            <div class="tab-content">
                <ul class="tab-pane news-list with-img active" id="main-news">
                    <?$pager = $this->tag->component('post', array('status' => 'published', 'limit' => 25, 'has_image' => 1, 'order' => '-created_at'));$posts = $pager->items;?>
                    <?foreach($posts as $post):?>
                    <li class="news">
                        <a href="<?=$post->getUrl()?>">
                            <img class="lazy img" src="/wscn/img/bg-img.gif" data-original="<?=$post->image ? $this->tag->thumb($post->image, 'c_fill,h_140,w_200') : '/img/article.jpg'?>" alt=""/>
                        </a>
                        <div class="content">
                            <a class="title" href="<?=$post->getUrl()?>"><?=$post->title?></a>
                            <div>
                                <span class="meta author">文 / <?=$post->user ? $post->user->username : '华尔街见闻'?></span>
                                <span class="meta time visible-lg-inline-block"><?=$this->tag->datetime($post->createdAt)?></span>
                                <span class="meta endorse pull-right">
                                    <i class="fa fa-thumbs-up"></i> 3
                                </span>
                            </div>
                            <div class="summary hidden-xxs">
                                <?if($post->summary):?>
                                    <?=$post->getSummaryHtml()?>
                                <?else:?>
                                    <?=\Eva\EvaEngine\Text\Substring::substrCn(strip_tags($post->getContentHtml()), 100);?>
                                <?endif?>
                            </div>
                        </div>
                    </li>
                    <?endforeach;?>
                    <!--
                    <?$this->partial("partial/paginator", array(
                        'pagerUrl' => '/news',
                        'pager' => $pager,
                    ))?>
                    -->
                    <li class="news-big hide">
                        <a class="cover-img" href="">
                            <img class="img" src="/wscn/img/img-news-lg.jpg" alt=""/>
                            <div class="cover">
                                <h3 class="title">对话中国顶尖对冲基金！见闻俱乐部第2期主题沙龙火热报名中</h3>
                                <h4 class="subtitle">沪港通”有望10月正式推出，A股与港股将迎来哪些投资机会？</h4>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a class="more" href="/news?page=2">加载更多</a>
                    </li>
                </ul><!--  -->
                <ul class="tab-pane news-list with-img" id="main-recommend-news">
                    <?$pager = $this->tag->component('post', array('status' => 'published', 'limit' => 25, 'order' => '-count'));$posts = $pager->items;?>
                    <?foreach($posts as $post):?>
                    <li class="news">
                        <a href="<?=$post->getUrl()?>">
                            <img class="lazy img" src="/wscn/img/bg-img.gif" data-original="<?=$post->image ? $this->tag->thumb($post->image, 'c_fill,h_140,w_200') : '/img/article.jpg'?>" alt=""/>
                        </a>
                        <div class="content">
                            <a class="title" href="<?=$post->getUrl()?>"><?=$post->title?></a>
                            <div>
                                <span class="meta author">文 / <?=$post->user ? $post->user->username : '华尔街见闻'?></span>
                                <span class="meta time visible-lg-inline-block"><?=$this->tag->datetime($post->createdAt)?></span>
                                <span class="meta endorse pull-right">
                                    <i class="fa fa-thumbs-up"></i> 3
                                </span>
                            </div>
                            <div class="summary hidden-xxs">
                                <?if($post->summary):?>
                                <?=$post->getSummaryHtml()?>
                                <?else:?>
                                <?=\Eva\EvaEngine\Text\Substring::substrCn(strip_tags($post->getContentHtml()), 100);?>
                                <?endif?>
                            </div>
                        </div>
                    </li>
                    <?endforeach;?>
                    <li>
                    <a class="more" href="/news?page=2">加载更多</a>
                    </li>
                </ul>
                <!--  -->
                <ul class="tab-pane news-list with-img hide" id="main-special-news">main-special-news</ul>
            </div>
        </div>
        <div id="rightbar">

            <!--  -->
            <div class="side-ad" style="margin-top: 25px">
                <img src="/wscn/img/side-img-1.jpg" alt=""/>
            </div>
            <!--  -->
            <div class="custom-box">
                <ul class="custom-nav-tabs custom-row">
                    <li class="col-custom-6 active">
                        <a data-toggle="tab" href="#side-day-rank-news"><strong>日排行</strong></a>
                    </li>
                    <li class="col-custom-6 ">
                        <a data-toggle="tab" href="#side-week-rank-news"><strong>周排行</strong></a>
                    </li>
                </ul>
                <ul class="tab-content">
                    <li class="tab-pane active" id="side-day-rank-news">
                        <?$pager = $this->tag->component('post', array('status' => 'published', 'limit' => 10, 'order' => '-count'));$posts = $pager->items;?>
                        <ul class="news-list with-number">
                            <?foreach($posts as $post):?>
                            <li class="news">
                                <a class="title" href="<?=$post->getUrl()?>">
                                    <strong><?=$post->title?></strong>
                                </a>
                            </li>
                            <?endforeach?>
                        </ul>
                    </li>
                    <?$pager = $this->tag->component('post', array('status' => 'published', 'limit' => 10, 'order' => '-sort_order'));$posts = $pager->items;?>
                    <li class="tab-pane " id="side-week-rank-news">
                        <ul class="news-list with-number">
                            <?foreach($posts as $post):?>
                            <li class="news">
                                <a class="title" href="<?=$post->getUrl()?>">
                                    <strong><?=$post->title?></strong>
                                </a>
                            </li>
                            <?endforeach?>
                        </ul>
                    </li>
                </ul>
                <!--  -->
                <h2 class="main-title">最新留言</h2>
                <ul class="side-comments">
                    <li class="comment">
                        <img class="avatar" src="" alt=""/>
                        <span class="name">smartisan</span> 评论了
                        <a class="title" href="">希尔顿酒店准备在纽约上市融资</a>
                        <p class="content">
                            找中央啊！津京一体化，然后就没有问题了。但无论如何，财政纪律得重新抓，得狠抓，没有问题啊。
                        </p>
                        <div class="time">2014年06月25日 05:58</div>
                        <!--<a class="text-blue " href="" data-action="reply">回复</a>-->
                    </li>

                    <li class="comment">
                        <img class="avatar" src="" alt=""/>
                        <span class="name">天才小熊猫</span> 评论了
                        <a class="title" href="">希尔顿酒店准备在纽约上市融资</a>
                        <p class="content">
                            无言的秘密，美国收水，伊拉克开打不暴跌才怪呢。
                        </p>
                        <div class="time">2014年06月25日 03:25</div>
                    </li>
                </ul>
            </div>

        </div><!--right bar-->
    </div><!--/wrapper-->
</div><!--/main content-->

<a id="show-sidebar" class="hidden-xxs hidden-xs" href="/livenews"></a>
<!-- main-content end -->
<aside id="sidebar" class="hidden-xxs hidden-xs">
    <span id="hide-sidebar" class="fa fa-times"></span>
    <h3 class="title">
        实时新闻
        <a class="more" href="/livenews" target="_blank">更多»</a>
    </h3>
    <table id="side-livenews">
        <tbody>
        <tr class="news">
            <td class="time">18:22</td>
            <td class="content">
                <a href="">国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）</a>
            </td>
        </tr>
        <tr class="news">
            <td class="time">18:13</td>
            <td class="content">
                <a href="">汇丰分析师：德债收益率或进一步下跌，接近1%，因欧洲央行很可能进一步采取包括QE在内的宽松政策。</a>
            </td>
        </tr>
        <tr class="news">
            <td class="time">18:02</td>
            <td class="content">
                <a href="">人民币兑美元中间价报6.1589；昨日中间价报6.1571，昨日收盘报6.2220。</a>
            </td>
        </tr>
        <tr class="news">
            <td class="time">17:31</td>
            <td class="content">
                a
            </td>
        </tr>
        <tr class="news">
            <td class="time">15:22</td>
            <td class="content">人民币兑美元中间价报6.1589</td>
        </tr>
        </tbody>
    </table>
</aside>
<!-- sidebar end -->
