<div id="main-content">
    <aside id="leftbar">
    <?$this->partial("partial/sidebar", array())?>
    </aside>
    <div id="wrapper">
        <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 1 ,'limit' => 3, 'has_image' => 1, 'order' => '-sort_order'));$posts = $pager->items;?>
        <div id="main" class="page-index">
            <div class="top3-news custom-row hidden-xxs">
                <div class="custom-span-1">
                    <?$posts->valid(); $post = $posts->current();?>
                    <?if($post):?>
                    <a class="top1 cover-img" href="<?=$post->getUrl()?>">
                        <img class="lazy img" src="/wscn/img/bg-img.gif" data-original="<?=$post->image ? $this->tag->thumb($post->image, 'c_fill,h_300,w_426') : '/img/article.jpg'?>" alt=""/>
                        <div class="cover">
                            <h3 class="title"><?=$post->title?></h3>
                            <!--
                            <h4 class="subtitle">MSCI将A股纳入新兴市场指数意味着什么？120亿美元入场</h4>
                            -->
                        </div>
                    </a>
                    <?endif?>
                </div>
                <div class="custom-span-2">
                    <div class="custom-span-3">
                        <?$posts->valid(); $post = $posts->current();?>
                        <?if($post):?>
                        <a class="top2 cover-img" href="<?=$post->getUrl()?>">
                            <img class="lazy img" src="/wscn/img/bg-img.gif" data-original="<?=$post->image ? $this->tag->thumb($post->image, 'c_fill,h_149,w_212') : '/img/article.jpg'?>" alt=""/>
                            <div class="cover">
                                <h3 class="title"><?=$post->title?></h3>
                            </div>
                        </a>
                        <?endif?>
                    </div>
                    <div class="custom-span-4">
                        <?$posts->valid(); $post = $posts->current();?>
                        <?if($post):?>
                        <a class="top3 cover-img" href="<?=$post->getUrl()?>">
                            <img class="lazy img" src="/wscn/img/bg-img.gif" data-original="<?=$post->image ? $this->tag->thumb($post->image, 'c_fill,h_149,w_212') : '/img/article.jpg'?>" alt=""/>
                            <div class="cover">
                                <h3 class="title"><?=$post->title?></h3>
                            </div>
                        </a>
                        <?endif?>
                    </div>
                </div>
            </div>
            <ul class="custom-nav-tabs">
                <li class="active"><a data-toggle="tab" href="#main-news">最新文章</a></li>
                <!--<li><a data-toggle="tab" href="#main-hot-news">热门排行</a></li>-->
                <li><a data-toggle="tab" href="#main-recommend-news">编辑推荐</a></li>
                <!--
                <li><a data-toggle="tab" href="#main-special-news">专栏专访</a></li>
                -->
            </ul>
            <div class="tab-content">
                <ul class="tab-pane news-list with-img active" id="main-news">
                    <?$pager = $this->tag->component('post', array('status' => 'published', 'limit' => 25, 'has_image' => 1, 'order' => '-created_at'));$posts = $pager->items;?>
                    <?foreach($posts as $post):?>
                    <li class="news">
                        <div class="cover-img">
                            <a href="<?=$post->getUrl()?>">
                                <img class="lazy full-width" src="/wscn/img/bg-img.gif" data-original="<?=$post->image ? $this->tag->thumb($post->image, 'c_fill,h_115,w_193') : '/img/article.jpg'?>" alt=""/>
                            </a>
                            <div class="cover">
                                <span title="点赞" class="endorse" data-action="endorse">123</span>
                                <a href="<?=$post->getUrl()?>#comments" title="查看评论" class="discuss" data-action="discuss">89</a>
                            </div>
                        </div>
                        <div class="content">
                            <a class="title" href="<?=$post->getUrl()?>"><?=$post->title?></a>
                            <div>
                                <span class="meta author">文 / <?=$post->user ? $post->user->username : '华尔街见闻'?></span>
                                <span class="meta time visible-lg-inline-block"><?=$this->tag->datetime($post->createdAt)?></span>
                                <span class="meta pull-right visible-lg-inline-block"
                                      onmouseover="jiathis_share('<?=$post->title?>', 'http://wallstreetcn.com<?=$post->getUrl()?>')">
                                    <a class="share jiathis jiathis_txt jtico jtico_jiathis" target="_blank"
                                       href="http://www.jiathis.com/share/?uid=1393984262901745"></a>
                                    <a class="collect" title="收藏" data-action="collect" href=""></a>
                                </span>
                                <span class="meta time hidden-lg pull-right"><?=$this->tag->datetime($post->createdAt)?></span>
                            </div>
                            <div class="summary">
                                <?if($post->summary):?>
                                    <?=$post->getSummaryHtml()?>
                                <?else:?>
                                    <?=\Eva\EvaEngine\Text\Substring::substrCn(strip_tags($post->getContentHtml()), 100);?>
                                <?endif?>
                            </div>
                        </div>
                    </li>
                    <?endforeach;?>
                    <!--
                    <?$this->partial("partial/paginator", array(
                        'pagerUrl' => '/news',
                        'pager' => $pager,
                    ))?>
                    -->
                    <li class="news-big hide">
                        <a class="cover-img" href="">
                            <img class="img" src="/wscn/img/img-news-lg.jpg" alt=""/>
                            <div class="cover">
                                <h3 class="title">对话中国顶尖对冲基金！见闻俱乐部第2期主题沙龙火热报名中</h3>
                                <h4 class="subtitle">沪港通”有望10月正式推出，A股与港股将迎来哪些投资机会？</h4>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a class="more" href="">加载更多</a>
                    </li>
                </ul><!--  -->
                <ul class="tab-pane news-list with-img" id="main-recommend-news">
                    <?$pager = $this->tag->component('post', array('status' => 'published', 'limit' => 25, 'order' => '-count'));$posts = $pager->items;?>
                    <?foreach($posts as $post):?>
                    <li class="news">
                        <div class="cover-img">
                            <a href="<?=$post->getUrl()?>">
                                <img class="lazy full-width" src="/wscn/img/bg-img.gif" data-original="<?=$post->image ? $this->tag->thumb($post->image, 'c_fill,h_115,w_193') : '/img/article.jpg'?>" alt=""/>
                            </a>
                            <div class="cover">
                                <span title="点赞" class="endorse" data-action="endorse">123</span>
                                <a href="<?=$post->getUrl()?>#comments" title="查看评论" class="discuss" data-action="discuss">89</a>
                            </div>
                        </div>
                        <div class="content">
                            <a class="title" href="<?=$post->getUrl()?>"><?=$post->title?></a>
                            <div>
                                <span class="meta author">文 / <?=$post->user ? $post->user->username : '华尔街见闻'?></span>
                                <span class="meta time visible-lg-inline-block"><?=$this->tag->datetime($post->createdAt)?></span>
                                <span class="meta pull-right visible-lg-inline-block"
                                      onmouseover="jiathis_share('<?=$post->title?>', 'http://wallstreetcn.com<?=$post->getUrl()?>')">
                                    <a class="share jiathis jiathis_txt jtico jtico_jiathis" target="_blank"
                                       href="http://www.jiathis.com/share/?uid=1393984262901745"></a>
                                    <a class="collect" title="收藏" data-action="collect" href=""></a>
                                </span>
                                <span class="meta time hidden-lg pull-right"><?=$this->tag->datetime($post->createdAt)?></span>
                            </div>
                            <div class="summary">
                                <?if($post->summary):?>
                                <?=$post->getSummaryHtml()?>
                                <?else:?>
                                <?=\Eva\EvaEngine\Text\Substring::substrCn(strip_tags($post->getContentHtml()), 100);?>
                                <?endif?>
                            </div>
                        </div>
                    </li>
                    <?endforeach;?>
                    <li>
                        <a class="more" href="">加载更多</a>
                    </li>
                </ul>
                <!--  -->
                <ul class="tab-pane news-list with-img hide" id="main-special-news">main-special-news</ul>
            </div>
        </div>
        <div id="rightbar">
            <?$pager = $this->tag->component('post', array('status' => 'published', 'cid' => 1 ,'limit' => 6, 'page' => 2, 'has_image' => 1, 'order' => '-sort_order'));$posts = $pager->items;?>
            <ul id="side-topnews" class="">
                <li class="head">
                    头条新闻
                </li>
                <?foreach($posts as $post):?>
                <li class="news">
                <a class="title" href="<?=$post->getUrl()?>">
                    <strong><?=$post->title?></strong>
                </a>
                </li>
                <?endforeach?>
            </ul>
            <!--  -->
            <div class="side-ad">
                <img src="/wscn/img/side-img-1.jpg" alt=""/>
            </div>
            <!--  -->
            <div class="row">
                <div class="col-sm-12">

                </div>
            </div>
            <ul class="custom-nav-tabs custom-row">
                <li class="col-custom-6 active">
                <a data-toggle="tab" href="#side-day-rank-news"><strong>日排行</strong></a>
                </li>
                <li class="col-custom-6 ">
                <a data-toggle="tab" href="#side-week-rank-news"><strong>周排行</strong></a>
                </li>
            </ul>
            <ul class="tab-content">
                <li class="tab-pane active" id="side-day-rank-news">
                <?$pager = $this->tag->component('post', array('status' => 'published', 'limit' => 10, 'order' => '-count'));$posts = $pager->items;?>
                <ul class="news-list with-number">
                    <?foreach($posts as $post):?>
                    <li class="news">
                    <a class="title" href="<?=$post->getUrl()?>">
                        <strong><?=$post->title?></strong>
                    </a>
                    </li>
                    <?endforeach?>
                </ul>
                </li>
                <?$pager = $this->tag->component('post', array('status' => 'published', 'limit' => 10, 'order' => '-sort_order'));$posts = $pager->items;?>
                <li class="tab-pane " id="side-week-rank-news">
                <ul class="news-list with-number">
                    <?foreach($posts as $post):?>
                    <li class="news">
                    <a class="title" href="<?=$post->getUrl()?>">
                        <strong><?=$post->title?></strong>
                    </a>
                    </li>
                    <?endforeach?>
                </ul>
                </li>
            </ul>
            <!--  -->
            <h2 class="main-title">最新留言</h2>
            <ul class="side-comments">
                <li class="comment">
                <img class="avatar" src="" alt=""/>
                <div>
                    <a class="name" href="">smartisan</a> 评论了
                    <a class="title" href="">希尔顿酒店准备在纽约上市融资</a>
                </div>
                <p class="content">
                找中央啊！津京一体化，然后就没有问题了。但无论如何，财政纪律得重新抓，得狠抓，没有问题啊。
                </p>
                <div>
                    <span class="time">2014年06月25日 05:58</span>
                    <a class="text-blue pull-right" href="" data-action="reply">回复</a>
                </div>
                </li>

                <li class="comment">
                <img class="avatar" src="" alt=""/>
                <div>
                    <a class="name" href="">天才小熊猫</a> 评论了
                    <a class="title" href="">希尔顿酒店准备在纽约上市融资</a>
                </div>
                <p class="content">
                无言的秘密，美国收水，伊拉克开打不暴跌才怪呢。
                </p>
                <div>
                    <span class="time">2014年06月25日 06:03</span>
                    <a class="text-blue pull-right" href="" data-action="reply">回复</a>
                </div>
                </li>
            </ul>
        </div>
    </div>
</div>

<a id="show-sidebar" href="/livenews"></a>
<!-- main-content end -->
<aside id="sidebar">
    <a id="hide-sidebar" href=""></a>
    <h3 class="main-title">
        实时新闻
        <a class="more" href="/livenews">更多&gt;&gt;</a>
    </h3>
    <div id="side-livenews" class="nano">
        <ul class="nano-content">
            <li class="news">
                <span class="time">18:22</span>国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）
            </li>
            <li class="news">
                <span class="time">17:58</span>汇丰分析师：德债收益率或进一步下跌，接近1%，因欧洲央行很可能进一步采取包括QE在内的宽松政策。
            </li>
            <li class="news">
                <span class="time">17:39</span>路透援引目击者称，5-6辆装甲运兵车驶入乌克兰东部城市Slaviansk，带头车辆插有俄罗斯国旗。
            </li>
            <li class="news">
                <span class="time">17:31</span>人民币兑美元中间价报6.1589；昨日中间价报6.1571，昨日收盘报6.2220。
            </li>
            <li class="news">
                <span class="time">18:22</span>国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）
            </li>
            <li class="news">
                <span class="time">18:22</span>国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）
            </li>
            <li class="news">
                <span class="time">18:22</span>国土部：不动产统一登记试点城市确定消息不实，目前尚未启动不动产统一登记试点工作。（凤凰财经）
            </li>
        </ul>
    </div>
</aside>
<!-- sidebar end -->

<script type="text/javascript">
    var jiathis_config = {}
    function jiathis_share(title, url) {
        jiathis_config.title = title;
        jiathis_config.url = url;
        //console.log(jiathis_config);
    }
</script>
<!--分享参数代码结束-->
<!--分享功能代码统一放到页尾-->
<script type="text/javascript" src="http://v3.jiathis.com/code/jia.js?uid=1393984262901745" charset="utf-8"></script>
