<?
    $this->placeholder->block('title')->set($item->username."的评论-华尔街见闻");
    $this->placeholder->block('description')->set("欢迎来到".$item->username."的小屋。华尔街见闻——中国最专业的金融资讯平台；直播外汇、期货、黄金、债券、证券等金融领域的实时新闻。华人投资者可以在这里获得最快速、最精准、最深入的全球财经资讯和市场行情。");
    $this->placeholder->block('keywords')->set($item->username.",评论,用户中心,外汇,期货,大宗商品,贵金属,黄金,股市,行情,数据,金融,理财");
?>
<div id="main-content" class="columns-2">
    <div id="main" class="page-user">
        <div class="head">
            <?include('topinfo.phtml')?>
        </div>
        <div class="body">
            <?include('navmain.phtml')?>
            <div class="tab-content">
                <div class="tab-pane active">
                    <?=$this->tag->flashOutput()?>
                    <ul class="comments">
                        <?foreach($pager->items as $comment):?>
                        <li class="comment">
                            <a class="title" href="<?=$comment->thread->permalink?>"><?=$comment->thread->getTitle(); ?></a>
                            <p class="summary">
                                <?=$comment->content ?>
                            </p>
                            <div>
                                <span class="time"><?=date('Y年m月d日 H:i',$comment->createdAt) ?></span>
<!--                                <a class="text-blue pull-right" data-action="delete">删除</a>-->
                            </div>
                        </li>
                        <? endforeach ?>
                    </ul>
                </div>
            </div>
        </div>
        <div class="foot"></div>
    </div>
    <div id="rightbar">
        <?include('sidebar.phtml')?>
    </div>
    <!-- rightbar end -->
</div>
