<div id="main-content" class="columns-2">
    <div id="main" class="page-user">
        <div class="head">
            <?include('topinfo.phtml')?>
        </div>
        <div class="body">
            <?include('navmain.phtml')?>
            <div class="tab-content">
                <div class="tab-pane active">
                    <?=$this->tag->flashOutput()?>
                    <ul class="comments">
                        <?foreach($pager->items as $comment):?>
                        <li class="comment">
                            <a class="title" href="<?=$comment->thread->permalink?>"><?=$comment->thread->getTitle(); ?></a>
                            <p class="summary">
                                <?=$comment->content ?>
                            </p>
                            <div>
                                <span class="time"><?=date('Y年m月d日 H:i',$comment->createdAt) ?></span>
<!--                                <a class="text-blue pull-right" data-action="delete">删除</a>-->
                            </div>
                        </li>
                        <? endforeach ?>
                    </ul>
                </div>
            </div>
        </div>
        <div class="foot"></div>
    </div>
    <div id="rightbar">
        <?include('sidebar.phtml')?>
    </div>
    <!-- rightbar end -->
</div>
