<?
    $this->placeholder->block('title')->set("修改邮箱-".$item->username."的用户中心-华尔街见闻");
    $this->placeholder->block('description')->set("欢迎来到".$item->username."的小屋。华尔街见闻——中国最专业的金融资讯平台；直播外汇、期货、黄金、债券、证券等金融领域的实时新闻。华人投资者可以在这里获得最快速、最精准、最深入的全球财经资讯和市场行情。");
    $this->placeholder->block('keywords')->set($item->username.",修改邮箱,用户中心,外汇,期货,大宗商品,贵金属,黄金,股市,行情,数据,金融,理财");
?>
<div id="main-content" class="columns-2">
    <div id="main" class="page-user">
        <div class="head">
            <?include('topinfo.phtml')?>
        </div>
        <div class="body">
            <?include('navmain.phtml')?>
            <div class="tab-content">
                <div class="tab-pane active" id="user-info">
                    <?include('navuser.phtml')?>
                    <div class="main-content">
                        <?=$this->tag->flashOutput()?>
                        <h3 class="title">修改邮箱</h3>
                        <form method="POST" class="form-horizontal" data-validate  novalidate="novalidate">
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right">当前邮箱</label>
                                <div class="col-sm-9">
                                    <?=$item->email?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="email" class="col-sm-3 control-label no-padding-right">新邮箱</label>
                                <div class="col-sm-9">
                                    <input type="email" name="email" class="form-control" placeholder="" required
                                        data-parsley-trigger="blur change"
                                        data-parsley-remote="/register/check"
                                        data-parsley-remote-options='{ method: "GET", dataType: "json"}'
                                        data-parsley-remote-message="输入的邮箱已被占用"
                                    >
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-offset-3 col-sm-9">
                                    <button type="submit" class="btn btn-primary btn-block">修改邮箱</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
                <div class="tab-pane" id="user-endorse"></div>
            </div>
        </div>
        <div class="foot"></div>
    </div>
    <div id="rightbar">
        <?include('sidebar.phtml')?>
    </div>
    <!-- rightbar end -->
</div>
