<ul class="custom-nav-tabs">
    <li class="" data-active-url="^\/mine/(dashboard).*$">
    <a href="/mine/dashboard">个人中心</a>
    </li>
    <li class="" data-active-url="^\/mine/comments.*$">
    <a href="/mine/comments">我的评论</a>
    </li>
    <li class="" data-active-url="^\/mine/stars.*$">
    <a href="/mine/stars">我的收藏</a>
    </li>
    <!--
    <li class="" data-active-url="^\/mine/quotes.*$">
    <a href="/mine/quotes">自选行情</a>
    </li>
    -->
    <li class="" data-active-url="^\/mine/(profile|profile|password|email|oauth).*$">
    <a href="/mine/profile">个人资料</a>
    </li>
</ul>
