<?
    $this->placeholder->block('title')->set("帐号绑定-".$item->username."的用户中心-华尔街见闻");
    $this->placeholder->block('description')->set("欢迎来到".$item->username."的小屋。华尔街见闻——中国最专业的金融资讯平台；直播外汇、期货、黄金、债券、证券等金融领域的实时新闻。华人投资者可以在这里获得最快速、最精准、最深入的全球财经资讯和市场行情。");
    $this->placeholder->block('keywords')->set($item->username.",帐号绑定,用户中心,外汇,期货,大宗商品,贵金属,黄金,股市,行情,数据,金融,理财");
    $iconMapping = array(
    'tencent' => 'fa-qq',
    'weibo' => 'fa-weibo',
)?>
<div id="main-content" class="columns-2">
    <div id="main" class="page-user">
        <div class="head">
            <?include('topinfo.phtml')?>
        </div>
        <div class="body">
            <?include('navmain.phtml')?>
            <div class="tab-content">
                <div class="tab-pane active" id="user-info">
                    <?include('navuser.phtml')?>
                    <div class="main-content">
                        <?=$this->tag->flashOutput()?>
                        <h3 class="title">社交帐号绑定</h3>

                        <table class="table table-striped">
                            <?foreach($services as $key => $service):?>
                            <tr>
                                <td>
                                    <i class="fa <?=$iconMapping[$key]?>"></i> <?=$service['title']?>
                                </td>
                                <td>
                                    <?if(!empty($service['token'])):?>
                                    已绑定 <img src="<?=$service['token']['remoteImageUrl']?>" alt="" width="32" height="32" /> <?=$service['token']['remoteUserName']?>
                                    <?endif?>
                                </td>
                                <td class="text-right">
                                    <?if(!empty($service['token'])):?>
                                    <a href="/auth/remove/<?=$key?>/<?=strtolower($service['token']['version'])?>" class="btn btn-default btn-mini pull-right" data-action="unbind-token">解除绑定</a>
                                    <?else:?>
                                    <a href="/auth/request/<?=$key?>/<?=strtolower($service['version'])?>" class="btn btn-info btn-mini pull-right" data-action="bind-token" target="_blank">立即绑定</a>
                                    <?endif?>
                                </td>
                            </tr>
                            <?endforeach?>
                        </table>
                    </div>
                </div>
                <div class="tab-pane" id="user-endorse"></div>
            </div>
        </div>
        <div class="foot"></div>
    </div>
    <div id="rightbar">
        <?include('sidebar.phtml')?>
    </div>
    <!-- rightbar end -->
</div>
