<?$iconMapping = array(
    'tencent' => 'fa-qq',
    'weibo' => 'fa-weibo',
)?>
<div id="main-content" class="columns-2">
    <div id="main" class="page-user">
        <div class="head">
            <?include('topinfo.phtml')?>
        </div>
        <div class="body">
            <?include('navmain.phtml')?>
            <div class="tab-content">
                <div class="tab-pane active" id="user-info">
                    <?include('navuser.phtml')?>
                    <div class="main-content">
                        <?=$this->tag->flashOutput()?>
                        <h3 class="title">社交帐号绑定</h3>

                        <table class="table table-striped">
                            <?foreach($services as $key => $service):?>
                            <tr>
                                <td>
                                    <i class="fa <?=$iconMapping[$key]?>"></i> <?=$service['title']?>
                                </td>
                                <td>
                                    <?if(!empty($service['token'])):?>
                                    已绑定 <img src="<?=$service['token']['remoteImageUrl']?>" alt="" width="32" height="32" /> <?=$service['token']['remoteUserName']?>
                                    <?endif?>
                                </td>
                                <td class="text-right">
                                    <?if(!empty($service['token'])):?>
                                    <a href="/auth/token/<?=$key?>" class="btn btn-default" data-action="unbind-token">解除绑定</a>
                                    <?endif?>
                                </td>
                            </tr>
                            <?endforeach?>
                        </table>
                    </div>
                </div>
                <div class="tab-pane" id="user-endorse"></div>
            </div>
        </div>
        <div class="foot"></div>
    </div>
    <div id="rightbar">
        <?include('sidebar.phtml')?>
    </div>
    <!-- rightbar end -->
</div>
