<?
    $this->placeholder->block('title')->set("修改密码-".$item->username."的用户中心-华尔街见闻");
    $this->placeholder->block('description')->set("欢迎来到".$item->username."的小屋。华尔街见闻——中国最专业的金融资讯平台；直播外汇、期货、黄金、债券、证券等金融领域的实时新闻。华人投资者可以在这里获得最快速、最精准、最深入的全球财经资讯和市场行情。");
    $this->placeholder->block('keywords')->set($item->username.",修改密码,用户中心,外汇,期货,大宗商品,贵金属,黄金,股市,行情,数据,金融,理财");
?>
<div id="main-content" class="columns-2">
    <div id="main" class="page-user">
        <div class="head">
            <?include('topinfo.phtml')?>
        </div>
        <div class="body">
            <?include('navmain.phtml')?>
            <div class="tab-content">
                <div class="tab-pane active" id="user-info">
                    <?include('navuser.phtml')?>
                    <div class="main-content">
                        <h3 class="title">修改密码</h3>
                        <?=$this->tag->flashOutput()?>
                        <form action="" class="form-horizontal" method="POST"  novalidate="novalidate" data-validate>
                            <div class="form-group">
                                <label for="password" class="col-sm-3 control-label no-padding-right">当前密码</label>
                                <div class="col-sm-9">
                                    <input id="password" type="password" name="password" class="form-control"
                                        data-parsley-trigger="blur change"
                                        data-parsley-minlength="6"
                                        data-parsley-minlength-message="密码最短6位"
                                        maxlength="26"
                                        data-parsley-maxlength="26"
                                        data-parsley-max-length="密码最长26位"
                                    >
                                    <span class="help-block">通过社交帐号注册未填写密码请留空</span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="passwordNew" class="col-sm-3 control-label no-padding-right">新密码</label>
                                <div class="col-sm-9">
                                    <input id="passwordNew" type="password" name="passwordNew" class="form-control" required
                                        data-parsley-trigger="blur change"
                                        data-parsley-minlength="6"
                                        data-parsley-minlength-message="密码最短6位"
                                        maxlength="26"
                                        data-parsley-maxlength="26"
                                        data-parsley-max-length="密码最长26位"
                                    >
                                </div>
                            </div>

                            <div class="form-group">
                                <label id="passwordConfirm" for="passwordConfirm" class="col-sm-3 control-label no-padding-right">确认密码</label>
                                <div class="col-sm-9">
                                    <input type="password" name="passwordConfirm" class="form-control" required
                                        data-parsley-equalto="#passwordNew"
                                        data-parsley-equalto-message="两次输入不匹配"
                                    >
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-offset-3 col-sm-9">
                                    <button type="submit" class="btn btn-primary btn-block">修改密码</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
                <div class="tab-pane" id="user-endorse"></div>
            </div>
        </div>
        <div class="foot"></div>
    </div>
    <div id="rightbar">
        <?include('sidebar.phtml')?>
    </div>
    <!-- rightbar end -->
</div>
