<div id="main-content" class="columns-2">
    <div id="main" class="page-user">
        <div class="head">
            <?include('topinfo.phtml')?>
        </div>
        <div class="body">
            <?include('navmain.phtml')?>
            <div class="tab-content">
                <div class="tab-pane active" id="user-info">
                    <?include('navuser.phtml')?>
                    <div class="main-content">
                        <?=$this->tag->flashOutput()?>
                        <h3 class="title">基本资料</h3>
                        <?$profileForm = $form->getForm('profile');?>

                        <form class="form-horizontal">
                            <div class="form-group">
                                <?=$form->render('id', array(
                                    'placeholder' => 'ID',
                                    'class' => 'form-control input-sm'
                                ))?>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right">头像</label>
                                <div class="col-sm-9">
                                    <div class="input-medium">
                                        <div class="input-group">
                            <span class="profile-picture">
                                <?if($item->avatar):?>
                                <img src="<?=$item->avatar?>" id="" alt="" class="img-responsive">
                                <?else:?>
                                <img src="<?=$this->tag->gravatar($item->email, 200)?>" id="" alt="" class="img-responsive">
                                <?endif?>
                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="form-group">
                                <label for="form-field-first" class="col-sm-3 control-label no-padding-right">姓名</label>

                                <div class="col-sm-9">
                                    <div class="row">
                                        <div class="col-xs-3">
                                            <?=$form->render('lastName', array(
                                                'placeholder' => '姓',
                                                'class' => 'form-control',
                                            ))?>
                                        </div>
                                        <div class="col-xs-3">
                                            <?=$form->render('firstName', array(
                                                'placeholder' => '名',
                                                'class' => 'form-control',
                                            ))?>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="form-group">
                                <label for="birthday" class="col-sm-3 control-label no-padding-right">生日</label>
                                <div class="col-sm-9">
                                    <div class="input-medium">
                                        <div class="input-group">
                                            <?=$profileForm->render('birthday', array(
                                                'placeholder' => '如2014-01-31',
                                                'data-date-format' => 'yyyy-mm-dd',
                                                'class' => 'form-control input-medium date-picker',
                                            ))?>
                                            <span class="input-group-addon">
                                                <i class="icon-calendar"></i>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right">性别</label>

                                <div class="col-sm-9">
                                    <label class="inline">
                                        <input type="radio" class="ace" name="form-field-radio" value="male">
                                        <span class="lbl"> 男士</span>
                                    </label>
                                    &nbsp; &nbsp; &nbsp;
                                    <label class="inline">
                                        <input type="radio" class="ace" name="form-field-radio" value="female">
                                        <span class="lbl"> 女士</span>
                                    </label>
                                    &nbsp; &nbsp; &nbsp;
                                    <label class="inline">
                                        <input type="radio" class="ace" name="form-field-radio" value="other">
                                        <span class="lbl"> 其他</span>
                                    </label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="industry" class="col-sm-3 control-label no-padding-right">行业</label>
                                <div class="col-sm-9">
                                    <?=$profileForm->render('industry', array(
                                        'class' => 'form-control input-medium ',
                                    ))?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="country" class="col-sm-3 control-label no-padding-right">国家</label>
                                <div class="col-sm-9">
                                    <?=$profileForm->render('country', array(
                                        'class' => 'form-control input-medium ',
                                    ))?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="form-field-first" class="col-sm-3 control-label no-padding-right">所在地区</label>

                                <div class="col-sm-9">
                                    <div id="address" class="row">
                                        <div class="col-xs-4">
                                            <select class="prov form-control"></select>
                                        </div>
                                        <div class="col-xs-4">
                                            <select class="city form-control" disabled="disabled"></select>
                                        </div>
                                        <div class="col-xs-4">
                                            <select class="dist form-control" disabled="disabled"></select>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="address" class="col-sm-3 control-label no-padding-right">地址</label>
                                <div class="col-sm-9">
                                    <?=$profileForm->render('address', array(
                                        'class' => 'form-control input-medium ',
                                    ))?>
                                </div>
                            </div>

                            <h4 class="title">联系信息</h4>
                            <hr>

                            <div class="form-group">
                                <label for="phoneMobile" class="col-sm-3 control-label no-padding-right">联系电话</label>
                                <div class="col-sm-9">
                                    <?=$profileForm->render('phoneMobile', array(
                                        'class' => 'form-control input-medium ',
                                    ))?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="localIm" class="col-sm-3 control-label no-padding-right">QQ号码</label>
                                <div class="col-sm-9">
                                    <?=$profileForm->render('localIm', array(
                                        'class' => 'form-control input-medium ',
                                    ))?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="site" class="col-sm-3 control-label no-padding-right">个人主页</label>
                                <div class="col-sm-9">
                                    <?=$profileForm->render('site', array(
                                        'class' => 'form-control input-medium ',
                                    ))?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="bio" class="col-sm-3 control-label no-padding-right">自我介绍</label>
                                <div class="col-sm-9">
                                    <?=$profileForm->render('bio', array(
                                        'class' => 'form-control input-medium ',
                                    ))?>
                                </div>
                            </div>
 
                            <div class="form-group">
                                <div class="col-sm-offset-3 col-sm-9">
                                    <button type="submit" class="btn btn-primary btn-block">保存</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
                <div class="tab-pane" id="user-endorse"></div>
            </div>
        </div>
        <div class="foot"></div>
    </div>
    <div id="rightbar">
        <?include('sidebar.phtml')?>
    </div>
    <!-- rightbar end -->
</div>

