<div id="main-content" class="columns-2">
    <div id="main" class="page-user">
        <div class="head">
            <img class="avatar" src="/wscn/img/avatar-md.png" alt=""/>
            <div class="auth">
                <h3 class="title">
                    V 华尔街见闻认证
                </h3>
                <div class="info">华尔街见闻 美工</div>
                <a href="" class="handle">申请认证</a>
            </div>
            <div class="info">
                <h2 class="name">James </h2>
                <p class="signature">
                    站在设计师背后，很不道德，you can you up, no can no bb
                </p>
                <div class="meta">
                    <i class="icon glyphicon glyphicon-envelope"></i>JamesNgai@hotmail.com
                    <span class="edit" data-action="edit">
                        <i class="icon glyphicon glyphicon-pencil"></i> 修改
                    </span>
                </div>
                <div class="meta">
                    <i class="icon glyphicon glyphicon-map-marker"></i>上海 黄浦区
                    <span class="edit" data-action="edit">
                        <i class="icon glyphicon glyphicon-pencil"></i> 修改
                    </span>
                </div>
                <div class="meta">
                    <i class="icon glyphicon glyphicon-user"></i>巨蟹座 | 华尔街见闻
                    <span class="edit" data-action="edit">
                        <i class="icon glyphicon glyphicon-pencil"></i> 修改
                    </span>
                </div>
            </div>
        </div>
        <div class="body">
            <ul class="custom-nav-tabs">
                <li class="active">
                    <a data-toggle="tab" href="#user-info">个人资料</a>
                </li>
                <li class="">
                    <a data-toggle="tab" href="#user-comments">个人评论</a>
                </li>
                <li class="">
                    <a data-toggle="tab" href="#user-collect">文章收藏</a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="user-info">
                    <nav class="leftbar">
                    <h3 class="title">个人资料</h3>
                    <a class="link active" href="">基本资料</a>
                    <a class="link" href="">安全密码</a>
                    <a class="link" href="">语言设置</a>
                    <a class="link" href="">账号绑定</a>
                    </nav>
                    <div class="main-content">
                        <h3 class="title">基本资料</h3>
                        <?$profileForm = $form->getForm('profile');?>

                        <form class="form-horizontal">
                            <div class="form-group">
                                <?=$form->render('id', array(
                                    'placeholder' => 'ID',
                                    'class' => 'form-control input-sm'
                                ))?>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right">头像</label>
                                <div class="col-sm-9">
                                    <div class="input-medium">
                                        <div class="input-group">
                            <span class="profile-picture">
                                <?if($item->avatar):?>
                                <img src="<?=$item->avatar?>" id="" alt="" class="img-responsive">
                                <?else:?>
                                <img src="<?=$this->tag->gravatar($item->email, 200)?>" id="" alt="" class="img-responsive">
                                <?endif?>
                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="form-group">
                                <label for="form-field-first" class="col-sm-3 control-label no-padding-right">姓名</label>

                                <div class="col-sm-9">
                                    <div class="row">
                                        <div class="col-xs-3">
                                            <?=$form->render('lastName', array(
                                                'placeholder' => '姓',
                                                'class' => 'form-control',
                                            ))?>
                                        </div>
                                        <div class="col-xs-3">
                                            <?=$form->render('firstName', array(
                                                'placeholder' => '名',
                                                'class' => 'form-control',
                                            ))?>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="form-group">
                                <label for="birthday" class="col-sm-3 control-label no-padding-right">生日</label>
                                <div class="col-sm-9">
                                    <div class="input-medium">
                                        <div class="input-group">
                                            <?=$profileForm->render('birthday', array(
                                                'placeholder' => 'yyyy-mm-dd',
                                                'data-date-format' => 'yyyy-mm-dd',
                                                'class' => 'form-control input-medium date-picker',
                                            ))?>
                                            <span class="input-group-addon">
                                                <i class="icon-calendar"></i>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right">性别</label>

                                <div class="col-sm-9">
                                    <label class="inline">
                                        <input type="radio" class="ace" name="form-field-radio" value="male">
                                        <span class="lbl"> 男士</span>
                                    </label>
                                    &nbsp; &nbsp; &nbsp;
                                    <label class="inline">
                                        <input type="radio" class="ace" name="form-field-radio" value="female">
                                        <span class="lbl"> 女士</span>
                                    </label>
                                    &nbsp; &nbsp; &nbsp;
                                    <label class="inline">
                                        <input type="radio" class="ace" name="form-field-radio" value="other">
                                        <span class="lbl"> 其他</span>
                                    </label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="industry" class="col-sm-3 control-label no-padding-right">行业</label>
                                <div class="col-sm-9">
                                    <?=$profileForm->render('industry', array(
                                        'class' => 'form-control input-medium ',
                                    ))?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="country" class="col-sm-3 control-label no-padding-right">国家</label>
                                <div class="col-sm-9">
                                    <?=$profileForm->render('country', array(
                                        'class' => 'form-control input-medium ',
                                    ))?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="form-field-first" class="col-sm-3 control-label no-padding-right">所在地区</label>

                                <div class="col-sm-9">
                                    <div class="row">
                                        <div class="col-xs-4">
                                            <?=$profileForm->render('province', array(
                                                'placeholder' => '省',
                                                'class' => 'form-control',
                                            ))?>
                                        </div>
                                        <div class="col-xs-4">
                                            <?=$profileForm->render('city', array(
                                                'placeholder' => '市',
                                                'class' => 'form-control',
                                            ))?>
                                        </div>
                                        <div class="col-xs-4">
                                            <?=$profileForm->render('state', array(
                                                'placeholder' => '区',
                                                'class' => 'form-control',
                                            ))?>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="address" class="col-sm-3 control-label no-padding-right">地址</label>
                                <div class="col-sm-9">
                                    <?=$profileForm->render('address', array(
                                        'class' => 'form-control input-medium ',
                                    ))?>
                                </div>
                            </div>

                            <h4 class="title">联系信息</h4>
                            <hr>

                            <div class="form-group">
                                <label for="phoneMobile" class="col-sm-3 control-label no-padding-right">联系电话</label>
                                <div class="col-sm-9">
                                    <?=$profileForm->render('phoneMobile', array(
                                        'class' => 'form-control input-medium ',
                                    ))?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="localIm" class="col-sm-3 control-label no-padding-right">QQ号码</label>
                                <div class="col-sm-9">
                                    <?=$profileForm->render('localIm', array(
                                        'class' => 'form-control input-medium ',
                                    ))?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="site" class="col-sm-3 control-label no-padding-right">个人主页</label>
                                <div class="col-sm-9">
                                    <?=$profileForm->render('site', array(
                                        'class' => 'form-control input-medium ',
                                    ))?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="bio" class="col-sm-3 control-label no-padding-right">自我介绍</label>
                                <div class="col-sm-9">
                                    <?=$profileForm->render('bio', array(
                                        'class' => 'form-control input-medium ',
                                    ))?>
                                </div>
                            </div>
 
                            <div class="form-group">
                                <div class="col-sm-offset-3 col-sm-9">
                                    <button type="submit" class="btn btn-primary btn-block">保存</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
                <div class="tab-pane" id="user-endorse"></div>
            </div>
        </div>
        <div class="foot"></div>
    </div>
    <div id="rightbar">
        <div class="side-ad">
            <img src="/wscn/img/side-img-1.jpg" alt="">
        </div>
        <ul class="custom-nav-tabs custom-row">
            <li class="col-custom-6 active">
            <a data-toggle="tab" href="#side-day-rank-news"><strong>日排行</strong></a>
            </li>
            <li class="col-custom-6 ">
            <a data-toggle="tab" href="#side-week-rank-news"><strong>周排行</strong></a>
            </li>
        </ul>
        <ul class="tab-content">
            <li class="tab-pane active" id="side-day-rank-news">
            <?$pager = $this->tag->component('post', array('status' => 'published', 'limit' => 10, 'order' => '-count'));$posts = $pager->items;?>
            <ul class="news-list with-number">
                <?foreach($posts as $post):?>
                <li class="news">
                <a class="title" href="/node/<?=$post->id?>">
                    <strong><?=$post->title?></strong>
                </a>
                </li>
                <?endforeach?>
            </ul>
            </li>
            <?$pager = $this->tag->component('post', array('status' => 'published', 'limit' => 10, 'order' => '-sort_order'));$posts = $pager->items;?>
            <li class="tab-pane " id="side-week-rank-news">
            <ul class="news-list with-number">
                <?foreach($posts as $post):?>
                <li class="news">
                <a class="title" href="/node/<?=$post->id?>">
                    <strong><?=$post->title?></strong>
                </a>
                </li>
                <?endforeach?>
            </ul>
            </li>
        </ul>
        <div class="side-ad">
            <img src="/wscn/img/side-img-1.jpg" alt="">
        </div>
    </div>
    <!-- rightbar end -->
</div>
