<?
    $this->placeholder->block('title')->set($item->username."的收藏-华尔街见闻");
    $this->placeholder->block('description')->set("欢迎来到".$item->username."的小屋。华尔街见闻——中国最专业的金融资讯平台；直播外汇、期货、黄金、债券、证券等金融领域的实时新闻。华人投资者可以在这里获得最快速、最精准、最深入的全球财经资讯和市场行情。");
    $this->placeholder->block('keywords')->set($item->username.",收藏,用户中心,外汇,期货,大宗商品,贵金属,黄金,股市,行情,数据,金融,理财");
?>
<div id="main-content" class="columns-2">
    <div id="main" class="page-user">
        <div class="head">
            <?include('topinfo.phtml')?>
        </div>
        <div class="body">
            <?include('navmain.phtml')?>
            <div class="tab-content">
                <div class="tab-pane active">
                    <?=$this->tag->flashOutput()?>
                    <?$stars = $pager->items;?>
                    <?if($stars->count() > 0):?>
                    <ul class="news-list">
                    <?foreach($stars as $star):?>
                    <?$post = $star->post;?>
                    <?if($post):?>
                        <li class="news">
                        <div class="clearfix">
                            <a href="<?=$post->getUrl()?>">
                                <img class="lazy img" src="/wscn/img/bg-img.gif" data-original="<?=$post->image ? $this->tag->thumb($post->image, 'c_fill,h_120,w_200') : '/img/article.jpg'?>" alt=""/>
                            </a>
                            <div class="content">
                                <a class="title" href="<?=$post->getUrl()?>"><?=$post->title?><a>
                                <p class="summary">
                                <?if($post->summary):?>
                                    <?=$post->getSummaryHtml()?>
                                <?else:?>
                                    <?=\Eva\EvaEngine\Text\Substring::substrCn(strip_tags($post->getContentHtml()), 100);?>
                                <?endif?>
                                </p>
                            </div>
                        </div>
                        <div class="clearfix">
                            <span class="time"><?=$this->tag->datetime($post->createdAt)?></span>
                            <span class="collect active"></span>
                        </div>
                        </li>
                    <?endif?>
                    <?endforeach?>
                    </ul>
                    <?else:?>
                    <p>还没有收藏文章，<a href="/news">去看看</a></p>
                    <?endif?>
            <?$this->partial("partial/paginator", array(
                'pagerUrl' => '/mine/stars',
                'pager' => $pager,
            ))?>
                </div>
            </div>
        </div>
        <div class="foot"></div>
    </div>
    <div id="rightbar">
        <?include('sidebar.phtml')?>
    </div>
    <!-- rightbar end -->
</div>
