<img class="avatar" src="/wscn/img/avatar-md.png" alt=""/>
<div class="auth">
    <h3 class="title">
        V 华尔街见闻认证
    </h3>
    <div class="info">华尔街见闻 美工</div>
    <a href="" class="handle">申请认证</a>
</div>
<div class="info">
    <h2 class="name">James </h2>
    <p class="signature">
    站在设计师背后，很不道德，you can you up, no can no bb
    </p>
    <div class="meta">
        <i class="icon glyphicon glyphicon-envelope"></i>JamesNgai@hotmail.com
        <span class="edit" data-action="edit">
            <i class="icon glyphicon glyphicon-pencil"></i> 修改
        </span>
    </div>
    <div class="meta">
        <i class="icon glyphicon glyphicon-map-marker"></i>上海 黄浦区
        <span class="edit" data-action="edit">
            <i class="icon glyphicon glyphicon-pencil"></i> 修改
        </span>
    </div>
    <div class="meta">
        <i class="icon glyphicon glyphicon-user"></i>巨蟹座 | 华尔街见闻
        <span class="edit" data-action="edit">
            <i class="icon glyphicon glyphicon-pencil"></i> 修改
        </span>
    </div>
</div>
