<img class="avatar" src="<?=$this->tag->gravatar($item->email, 200)?>" alt=""/>
<div class="auth">
    <h3 class="title">
        华尔街见闻用户
    </h3>
    <?if(0):?>
    <div class="info">华尔街见闻</div>
    <a href="" class="handle">申请认证</a>
    <?endif?>
</div>
<div class="info">
    <h2 class="name"><?=$item->username?></h2>
    <p class="signature">
    <?if($item->profile && $item->profile->bio):?>
    <?=$item->profile->bio?>
    <?endif?>
    </p>
    <div class="meta">
        <i class="icon fa fa-envelope"></i><?=$item->email?>
        <a class="edit" data-action="edit" href="/mine/email">
            <i class="icon fa fa-pencil"></i> 修改
        </a>
    </div>
    <?if($item->profile && $item->profile->province):?>
    <div class="meta">
        <i class="icon fa fa-map-marker"></i>
        <?=$item->profile->province?>
        <?=$item->profile->city?>
        <?=$item->profile->state?>
        <a class="edit" data-action="edit" href="/mine/profile">
            <i class="icon fa fa-pencil"></i> 修改
        </a>
    </div>
    <?endif?>
    <?if(0 && $item->profile && $item->profile->birthday):?>
    <div class="meta">
        <i class="icon fa fa-user"></i>巨蟹座 | 华尔街见闻
        <a class="edit" data-action="edit" href="/mine/profile">
            <i class="icon fa fa-pencil"></i> 修改
        </a>
    </div>
    <?endif?>
</div>
