<ul class="news-list livenews-list">
    <li class="livenews">
    <a href="livenews.html">
        <i class="icon common"></i>
        <dl>
            <dd class="datetime">2014-07-07 09:30</dd>
            <dd class="content">新华网深圳3月23日电（记者 赵瑞西）23日，深圳市南山区西里医院的大楼</dd>
        </dl>
    </a>
    </li>
    <li class="livenews">
    <a href="">
        <i class="icon common"></i>
        <dl>
            <dd class="datetime">2014-07-07 09:30</dd>
            <dd class="content">新华网深圳3月23日电（记者 赵瑞西）23日，深圳市南山区西里医院的大楼</dd>
        </dl>
    </a>
    </li>
    <li class="livenews">
    <a href="">
        <i class="icon chart-column"></i>
        <dl>
            <dd class="datetime">2014-07-07 09:30</dd>
            <dd class="content">新华网深圳3月23日电（记者 赵瑞西）23日，深圳市南山区西里医院的大楼</dd>
        </dl>
    </a>
    </li>
    <li class="livenews">
    <a href="">
        <i class="icon chart-line"></i>
        <dl>
            <dd class="datetime">2014-07-07 09:30</dd>
            <dd class="content">新华网深圳3月23日电（记者 赵瑞西）23日，深圳市南山区西里医院的大楼</dd>
        </dl>
    </a>
    </li>
    <li class="livenews">
    <a href="">
        <i class="icon alert-news"></i>
        <dl>
            <dd class="datetime">2014-07-07 09:30</dd>
            <dd class="content">新华网深圳3月23日电（记者 赵瑞西）23日，深圳市南山区西里医院的大楼</dd>
        </dl>
    </a>
    </li>
    <li class="livenews">
    <a href="">
        <i class="icon warning-news"></i>
        <dl>
            <dd class="datetime">2014-07-07 09:30</dd>
            <dd class="content">新华网深圳3月23日电（记者 赵瑞西）23日，深圳市南山区西里医院的大楼</dd>
        </dl>
    </a>
    </li>
    <li class="livenews">
    <a href="">
        <i class="icon chart-line"></i>
        <dl>
            <dd class="datetime">2014-07-07 09:30</dd>
            <dd class="content">新华网深圳3月23日电（记者 赵瑞西）23日，深圳市南山区西里医院的大楼</dd>
        </dl>
    </a>
    </li>
    <li class="livenews">
    <a href="">
        <i class="icon alert-news"></i>
        <dl>
            <dd class="datetime">2014-07-07 09:30</dd>
            <dd class="content">新华网深圳3月23日电（记者 赵瑞西）23日，深圳市南山区西里医院的大楼</dd>
        </dl>
    </a>
    </li>
    <li class="livenews">
    <a href="">
        <i class="icon warning-news"></i>
        <dl>
            <dd class="datetime">2014-07-07 09:30</dd>
            <dd class="content">新华网深圳3月23日电（记者 赵瑞西）23日，深圳市南山区西里医院的大楼</dd>
        </dl>
    </a>
    </li>
    <li class="livenews">
    <a href="">
        <i class="icon chart-line"></i>
        <dl>
            <dd class="datetime">2014-07-07 09:30</dd>
            <dd class="content">新华网深圳3月23日电（记者 赵瑞西）23日，深圳市南山区西里医院的大楼</dd>
        </dl>
    </a>
    </li>
    <li class="livenews">
    <a href="">
        <i class="icon alert-news"></i>
        <dl>
            <dd class="datetime">2014-07-07 09:30</dd>
            <dd class="content">新华网深圳3月23日电（记者 赵瑞西）23日，深圳市南山区西里医院的大楼</dd>
        </dl>
    </a>
    </li>
    <li class="livenews">
    <a href="">
        <i class="icon warning-news"></i>
        <dl>
            <dd class="datetime">2014-07-07 09:30</dd>
            <dd class="content">新华网深圳3月23日电（记者 赵瑞西）23日，深圳市南山区西里医院的大楼</dd>
        </dl>
    </a>
    </li>
</ul>
<br/>
<div class="news-more row" data-action="show-info">
    <span class="news-font">加载更多</span>	
</div>	
<br/><br/>
