<?$livenews = $pager->items;?>
<ul class="news-list livenews-list">
    <?foreach($livenews as $news):?>
    <li class="livenews">
    <a href="/livenews/<?=$news->id?>">
        <i class="icon common"></i>
        <dl>
            <dd class="datetime"><?=$this->tag->datetime($news->createdAt)?></dd>
            <dd class="content"><?=$news->title?></dd>
        </dl>
    </a>
    </li>
    <?endforeach?>
</ul>
<br/>
<div class="news-more row" data-action="show-info">
    <span class="news-font">加载更多</span>	
</div>	
<br/><br/>
