<script type="text/javascript" src="/wscnm/gmu/zepto.js"></script>
<script type="text/javascript" src="/wscnm/gmu/gmu.js"></script>
<script type="text/javascript" src="/wscnm/js/nav.js"></script>
<script type="text/javascript">
    $(function ($) {
		$(".nav span").click(function(){
			//console.log("." + $(this).attr("data-target"));
			$(".content-wrapper > div").css("display","none");
			$("." + $(this).attr("data-target")).css("display","");
		})
	 }(Zepto));
</script>
