<div class="left-menu">

    <a href="/login"><img src="/wscnm/img/loginbig.png" class="person-icon" alt="登录" style="display:none"/></a>
    <ul>
        <li>
        <a href="/">
            <img src="/wscnm/img/news.png" alt="" />
            <span>新闻资讯</span>
        </a>
        </li>
        <li>
        <a href="/livenews">
            <img src="/wscnm/img/live.png" alt="" />
            <span>实时新闻</span>
        </a>
        </li>
        <li>
        <a href="/markets">
            <img src="/wscnm/img/market.png" alt="" />
            <span>全球行情</span>
        </a>
        </li>
        <li>
        <a href="/calendar">
            <img src="/wscnm/img/cal.png" alt="" />
            <span>财经日历</span>
        </a>
        </li>
        <li>
        <a href="/search">
            <img src="/wscnm/img/search.png" />
            <span>搜索&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
        </a>
        </li>
    </ul>

</div>
