<div class="toolbar">
    <!--<button class="menu-icon"></button>-->
    <a class="menu-indicator"><img src="<?=$this->url->getStatic('/wscnm/img/menu.png')?>"/></a>
    <a href="javascript:void(0)" class="home"><div class="home"><img src="<?=$this->url->getStatic('/wscnm/img/logo.png')?>"/></div></a>
    <a href="http://wallstreetcn.com/downloadapp.html" target="_blank">
		<div class="app-download">
			<span>下载APP</span>
		</div>
	</a>
</div>
