<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
        <li>
        <i class="icon-home home-icon"></i>
        <a href="/admin/dashboard">Home</a>
        </li>

        <li>
        <a href="/admin/appoption" class="active">Appoption List</a>
        </li>
    </ul><!-- .breadcrumb -->

    <div class="nav-search" id="nav-search">
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                <i class="icon-search nav-search-icon"></i>
            </span>
        </form>
    </div><!-- #nav-search -->
</div>

<div class="page-content">

    <div class="row">
        <div class="col-xs-12">
            <h3 class="header smaller lighter blue">
                Appoption List
                <a href="/admin/appoption/create" class="btn btn-sm"><i class="icon-pencil align-top bigger-125"></i> Create New</a>
            </h3>
            <div class="table-header">
                Showing <?=$pager->offset_start?> to <?=$pager->offset_end?> of <?=$pager->total_items?> Items 
            </div>

            <div class="table-responsive dataTables_wrapper">
                <table class="table table-striped table-bordered table-hover dataTable  table-sortable" id="post-grid" data-sortable-key="order" data-sortable-default="-created_at">
                    <thead>
                        <tr>
                            <th class="center">
                                ID
                            </th>
                            <th>Endpoint</th>
                            <th>Description</th>
                            <th>
                                <i class="icon-time bigger-110"></i>
                                Created At
                            </th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        <?foreach($pager->items as $item):?>
                        <tr>
                            <td>
                                <?=$item->id?>
                            </td>
                            <td class="hidden-480">
                                <?=$item->endpoint?>
                            </td>
                            <td>
                                <?=$item->description?>
                            </td>
                            <td>
                                <?=$this->tag->datetime($item->createdAt)?>
                            </td>
                            <td>
                                <div class="btn-group">
                                    <a class="btn btn-xs btn-info" href="/admin/appoption/edit/<?=$item->id?>">
                                        <i class="icon-edit bigger-120"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <?endforeach?>
                    </tbody>
                </table>

                <div class="row">
                    <div class="col-sm-6">
                        <div class="btn-group">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="dataTables_paginate">
                            <?$this->partial("partial/paginator", array(
                                'pagerUrl' => '/admin/appoption',
                                'pager' => $pager,
                            ))?>
                        </div>
                    </div>
                </div>

            </div><!--/table div-->

        </div><!-- /col-->
    </div><!--row end-->

</div><!-- /.page-content -->
