<!DOCTYPE html>
<html>
    <head>
        <title><?=$this->placeholder->block('title', '互联星空财经频道');?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
        <link href="favicon.ico" rel="shortcut icon" type="image/x-icon">
        <link rel="stylesheet" type="text/css" href="/vnet/gmu/reset.css" />
        <link rel="stylesheet" type="text/css" href="/vnet/gmu/gmu.css" />
        <link rel="stylesheet" type="text/css" href="/vnet/css/style.css" />
		<style type="text/css">
			#menu {
				/*background: transparent;*/
				border-width: 0;
				display: -webkit-box;
				-webkit-box-flex: 1;
			}
			#menu li a {
				/*color: #333;*/
			}

			#menu li.ui-state-active,
			#menu li.ui-state-hover {
				/*background: transparent;*/
			}
			#menu li.ui-state-active a,
			#menu li.ui-state-hover a{
				/*color: #e81459;*/
			}

			#menu .ui-scroller {
				position: relative;
			}
			#menu .bar {
				position: absolute;
				height: 2px;
				bottom: 0;
				overflow: hidden;
				-webkit-box-sizing:border-box;
				padding: 0 10px;
				-webkit-transition: left 200ms ease-out;
				display:none;
			}
			#menu .bar:after {
				content: '';
				display: block;
				height: 2px;
				background-color: #e81459;
			}
			#menu_wrap {
				display: -webkit-box;
			}
			#arrow {
				width: 30px;
				-webkit-box-flex: 0;
				-webkit-box-align: center;
				-webkit-box-pack: center;
				display: -webkit-box;
				background-color:#2773dc;
			}
			.ui-scroller {
				float: left;
			}
		</style>
    </head>
    <body>

        <div>
            <div class="toolbar" style="background-image:url(/vnet/img/bg.png);background-repeat: repeat;">
                <button class="menu-icon" style="display:none">打开菜单</button>
                <h3 class="title" style="display:none">互联星空财经频道</h3>
                <a href="/"><div class="home" style="top: 1px;left:0px"><img src="/vnet/img/logo.png"/></div></a>
                <a href="http://wallstreetcn.com/downloadapp.html" target="_blank" style="display:none"><div class="app-download"><img src="/vnet/img/app-download.png" /></div></a>
            </div>
			<div id="menu_wrap">
				<div id="menu">
					<ul>
						<li class="news"><a href="/">头条</a></li>
                        <li class="direct-tv"><a href="/direct">直播</a></li>
						<li class="livenews"><a href="/livenews">快讯</a></li>
						<li class="markets"><a href="/markets">行情</a></li>
						<li class="recommend"><a href="/recommend">推荐</a></li>
					</ul>
					<span class="bar"></span>
				</div>
				<a id="arrow"><span>&gt;</span></a>
			</div>
            <div class="content-wrapper">
                <?=$this->getContent()?>
            </div>

            



            <div class="gotop"></div>
            <div class="footerbar-placeholder">&nbsp;</div>
            <!--<div class="footerbar">广告</div>-->

        </div>
        <script type="text/javascript" src="/vnet/gmu/zepto.js"></script>
        <script type="text/javascript" src="/vnet/gmu/gmu.js"></script>
        <script type="text/javascript" src="/vnet/js/nav.js"></script>
        <script type="text/javascript" src="http://cdn.static.wallstreetcn.com/js/moment-with-langs.min.js"></script>
        <script type="text/javascript" src="http://cdn.static.wallstreetcn.com/js/art-template-3.0.0.js"></script>
        <script type="text/javascript" src="/vnet/js/marketlist.js"></script>
        <script type="text/javascript" src="/vnet/js/marketdetail.js" data-desc="depend on wscn_util.js & store.js"></script>
		<script type="text/javascript">

			(function () {
                $(document).on('click', '.news-more', function(){
                    var loader = $(this);
                    var link = $(this).attr('href');
                    $.ajax({
                        url : link,
                        success : function(response){
                                var newpage = $(response);
                                $(".content-wrapper ul").append(newpage.find('.content-wrapper ul').html());
                                loader.attr('href', newpage.find('a.news-more').attr('href'));
                        }
                    });
                    return false;
                });
                $('iframe').height(document.documentElement.clientHeight - 110);
				var bar = $('#menu span.bar'),
					left = $('#menu ul').offset().left;
				$('#menu').navigator({
					select: function( e, index, li ){
						bar.css({
							left: li.offsetLeft - left,
							width: li.childNodes[0].offsetWidth
						});
					},
					ready: function() {
						bar.appendTo($('#menu').find('.ui-scroller'));
					}
				});

				$('#arrow').on('click', function(){
					$('#menu').iScroll( 'scrollTo', 100, 0, 400, true );
				});

				
				$("#menu li").each(function(){
					$(this).removeClass("ui-state-active");
				});
				
				var url = document.location.href;
				if(url.indexOf("livenews") != -1){
					$("#menu .livenews").addClass("ui-state-active");
				}
				else if(url.indexOf("news") != -1){
					$("#menu .news").addClass("ui-state-active");
				}
				else if(url.indexOf("direct") != -1){
					$("#menu .direct-tv").addClass("ui-state-active");
				}
				else if(url.indexOf("markets") != -1){
					$("#menu .markets").addClass("ui-state-active");
				}
				else if(url.indexOf("recommend") != -1){
					$("#menu .recommend").addClass("ui-state-active");
				}

			})();
		</script>
<script type="text/javascript">
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-19303398-2']);
		_gaq.push(['_setDomainName', '.wallstreetcn.com']);
		_gaq.push(['_trackPageview']);

		(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();
	</script>    
	<script>
		var _hmt = _hmt || [];
		(function() {
			var hm = document.createElement("script");
			hm.src = "//hm.baidu.com/hm.js?c9477ef9d8ebaa27c94f86cc3f505fa5";
			var s = document.getElementsByTagName("script")[0]; 
			s.parentNode.insertBefore(hm, s);
		})();
	</script>
    </body>
</html>

