<div>
    <?=$this->partial('partial/top')?>
    <div class="content-wrapper">
        <form action="/search" method="get">
            <div class="search">
                <div class="search-input"><input type="text" id="searchInput" name="q" value="<?=isset($keyword) ? $keyword : ''?>"></div>
                <div class="search-button"><input type="submit" value="&nbsp;&nbsp;搜&nbsp;索&nbsp;&nbsp;"></div>
            </div>
        </form>
        <?if(!empty($tags)):?>
        <div class="tagcloud">
            <h2 class="hot-word-title">热门搜索</h2>
            <div id="tagcloud">
                <?foreach($tags as $tag):?>
                <a href="/search/?q=<?=$tag->tagName?>" class="tagc2"><?=$tag->tagName?></a>
                <?endforeach?>
            </div>
        </div>
        <?endif?>
        <?if(!empty($hits)):?>
        <ul class="news-list">
            <? foreach ($hits['hits'] as $hit): ?>
            <? $post = json_decode(json_encode($hit['_source'])); ?>
            <li class="news">
            <a href="/node/<?=$post->id?>">
                <img src="<?=$post->image ? $this->tag->thumb($post->image, 'c_fill,h_60,w_75') : '/img/article.jpg'?>"/>
                <dl>
                    <dd class="content"><?=isset($hit['highlight']['title']) ? $hit['highlight']['title'][0] : $post->title?></dd>

                    <dd class="source"><?=$this->tag->datetime($post->createdAt)?></dd>
                </dl>
            </a>
            </li>
            <?endforeach;?>
        </ul>
        <br/>
        <a class="news-more" data-action="show-info" href="/search?q=<?=$keyword?>&amp;page=<?=$pager->next?>">
            <span class="news-font">加载更多</span>	
        </a>	
        <br/><br/>
        <?endif?>
    </div>
    <?=$this->partial('partial/leftmenu')?>
    <?=$this->partial('partial/footer')?>
</div>
<?=$this->partial('partial/js')?>

<script type="text/javascript" src="/wscnm/js/tagcloud.js"></script>
<script type="text/javascript">
    $(function ($) {
            $('#searchInput').suggestion({
                    source: "/search/suggestion"
            });
            var tagCloud = new TagCould("tagcloud",{radius:parseInt(window.innerWidth)/2 - 20});
            tagCloud.start();
    }(Zepto));
</script>
