<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title><?=$this->placeholder->block('title', '华尔街见闻');?></title>

    <!-- Bootstrap -->
    <link href="/wscn/css/bootstrap.min.css" rel="stylesheet">
    <!-- for ie mobile content-width bug -->
    <script>
        if (navigator.userAgent.match(/IEMobile\/10\.0/)) {
            var msViewportStyle = document.createElement('style');
            msViewportStyle.appendChild(
                    document.createTextNode(
                            '@-ms-viewport{width:auto!important}'
                    )
            );
            document.querySelector('head').appendChild(msViewportStyle);
        }
    </script>
    <!-- nanoScroller -->
    <link href="/vendor/js/nano-scroller/nanoscroller.css" rel="stylesheet">
    <!--  -->
    <link href="/wscn/css/style.css" rel="stylesheet">
    <!-- grunt watch for live reload  -->
    <script src="//localhost:35729/livereload.js"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<!-- -->
<header id="header">
    <div class="container">
        <nav class="navbar" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">
                    <h1 class="hidden">Wallstreet</h1>
                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#">新闻资讯</a></li>
                    <li><a href="#">实时新闻</a></li>
                    <li><a href="#">实时行情</a></li>
                    <li><a href="#">财经日历</a></li>
                    <li><a href="#">见闻早餐</a></li>
                    <li><a href="#">黄金头条</a></li>
                    <li><a href="#">贵金属吐槽台</a></li>
                    <li><a href="#">App下载</a></li>
                </ul>

                <form class="search-form navbar-form navbar-right" role="search">
                    <div class="form-group has-feedback">
                        <input type="text" class="search-field" placeholder="Search">
                        <span class="glyphicon glyphicon-search form-control-feedback"></span>
                    </div>
                </form>

                <!--
                <form class="navbar-form navbar-left navbar-right" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>

                <form id="search-form" action="" role="search">
                    <input type="text" class="search-field" placeholder="Search">
                </form>
                -->
            </div><!-- /.navbar-collapse -->

        </nav>
    </div>
    <a id="breaking-news" href="">
        <div class="container">
            <h2 class="title">中证报评论：“微刺激”加码，稳增长措施有望进一步出台，下半年经济有望企稳，但下行压力依然存在。
                <span class="glyphicon glyphicon-remove" data-action="close"></span>
            </h2>
        </div>
    </a>
</header>

<div id="content">
    <?=$this->getContent()?>
    <!-- qr code -->
    <a id="qrcode" class="hidden-xs hidden-xxs" href="http://wallstreetcn.com/app/index.html">
        <img src="/wscn/img/qrcode.png" alt=""/>
    </a>
    <!-- qr code end -->
    <!-- postbar -->
    <aside id="postbar" class="hidden-xs hidden-xxs">
        <a class="item suggest"></a>
        <a class="item wechat"></a>
        <a class="item up" href="#"></a>
    </aside>
    <!-- postbar ebd -->
</div>



<footer id="footer">
    <div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-lg-3"></div>
                <div class="col-md-2 col-sm-3 col-xs-6">
                    <h2 class="foot-title">相关信息</h2>
                    <ul class="list">
                        <li class="item">关于华尔街见闻</li>
                        <li class="item">使用条款</li>
                        <li class="item">版权声明</li>
                    </ul>
                </div>
                <div class="col-md-2 col-sm-3 col-xs-6">
                    <h2 class="foot-title">联系我们</h2>
                    <ul class="list">
                        <li class="item">广告投放</li>
                        <li class="item">商业合作</li>
                        <li class="item">意见反馈</li>
                    </ul>
                </div>
                <div class="col-md-2 col-sm-3 col-xs-6">
                    <h2 class="foot-title">关注我们</h2>
                    <ul class="list">
                        <li class="item">微博@华尔街见闻</li>
                        <li class="item">腾讯微博</li>
                        <li class="item">邮件订阅</li>
                        <li class="item">RSS订阅</li>
                    </ul>
                </div>
                <div class="col-md-2 col-sm-3 col-xs-6">
                    <h2 class="foot-title">加入我们</h2>
                    <ul class="list">
                        <li class="item">全职岗位</li>
                        <li class="item">实习岗位</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>


<!-- Modal -->
<div id="user-modal" class="custom-modal size-sm " tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
    <div class="wrapper">
        <div id="user-modal-carousel" class="carousel slide" data-ride="carousel" data-interval="false">
            <!-- Indicators
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            -->
            <!-- Wrapper for slides -->
            <ol class="carousel-inner">
                <li class="item ">
                    <table>
                        <tbody>
                        <tr>
                            <td>
                                <div class="custom-modal-content">
                                    <div class="custom-modal-header">
                                        <button type="button" class="close" data-toggle="custom-modal" data-target="#user-modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                        重新设置密码
                                    </div>
                                    <div class="custom-modal-body">
                                        <form action="/session/forgot"  method="POST" novalidate="novalidate">
                                            <div class="form-group has-feedback">
                                                <label >请输入注册邮箱</label>
                                                <input type="email" name="email" class="form-control" placeholder="注册邮箱" required>
                                                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                                            </div>
                                            <div class="form-footer">
                                                <button type="submit" class="custom-button pull-right">发送确认邮件</button>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="custom-modal-footer">
                                        <a class="link-left"  data-target="#user-modal-carousel" data-slide-to="1">返回登录</a>
                                        <a class="link-right" data-target="#user-modal-carousel" data-slide-to="2">注册</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </li>
                <!--  -->
                <li class="item active">
                    <table>
                        <tbody>
                        <tr>
                            <td>
                                <div class="custom-modal-content">
                                    <div class="custom-modal-header">
                                        <button type="button" class="close" data-toggle="custom-modal" data-target="#user-modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                        登录华尔街见闻
                                    </div>
                                    <div class="custom-modal-body">
                                        <form action="/login"  method="POST" novalidate="novalidate">
                                            <div class="form-group has-feedback">
                                                <input type="text" name="username" class="form-control" placeholder="用户名或邮箱" required>
                                                <span class="glyphicon glyphicon-user form-control-feedback"></span>
                                            </div>
                                            <div class="form-group has-feedback">
                                                <input type="password" name="password" class="form-control password-previewer" placeholder="密码" required>
                                                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                                            </div>
                                            <div class="form-footer">
                                                <div class="checkbox pull-left" style="width: 100px;">
                                                    <label>
                                                        <input type="checkbox"> 记住密码
                                                    </label>
                                                </div>
                                                <button type="submit" class="custom-button pull-right">登录</button>
                                            </div>
                                        </form>
                                        <div class="br-title">
                                            <span class="text">使用社交账号登录</span>
                                        </div>
                                        <div class="custom-row">
                                            <div class="custom-span-left" style="">
                                                <a class="custom-button size-fluid type-weibo" href="/auth/request/weibo/oauth2" target="_blank">
                                                    <i class="icontext icontext-weibo-md">微博帐号</i>
                                                </a>
                                            </div>
                                            <div class="custom-span-right" style="">
                                                <a class="custom-button size-fluid type-qq" href="/auth/request/tencent/oauth2" target="_blank">
                                                    <i class="icontext icontext-qq-md">QQ帐号</i>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="custom-modal-footer">
                                        <a class="link-left"  data-target="#user-modal-carousel" data-slide-to="0">忘记密码</a>
                                        <a class="link-right" data-target="#user-modal-carousel" data-slide-to="2">注册</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </li>
                <!--  -->
                <li class="item">
                    <table>
                        <tbody>
                        <tr>
                            <td>
                                <div class="custom-modal-content">
                                    <div class="custom-modal-header">
                                        <button type="button" class="close" data-toggle="custom-modal" data-target="#user-modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                        注册华尔街见闻
                                    </div>
                                    <div class="custom-modal-body">
                                        <form action="/register"  method="POST" novalidate="novalidate" role="form">
                                            <div class="form-group has-feedback">
                                                <label>使用邮箱注册</label>
                                                <input type="email" name="email" class="form-control" placeholder="邮箱" required
                                                    data-parsley-trigger="blur change"
                                                    data-parsley-remote="/register/check"
                                                    data-parsley-remote-options='{ method: "GET", dataType: "json"}'
                                                    data-parsley-remote-message="输入的邮箱已被占用"
                                                >
                                                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                                            </div>
                                            <div class="form-group has-feedback">
                                                <input type="text" name="username" class="form-control" placeholder="用户名" required
                                                    data-parsley-trigger="blur change"
                                                    data-parsley-type="alphanum"
                                                    maxlength="24"
                                                    data-parsley-minlength="4"
                                                    data-parsley-minlength-message="用户名最短4个字符"
                                                    data-parsley-maxlength="24"
                                                    data-parsley-pattern="^(?![0-9]+$)"
                                                    data-parsley-pattern-message="请不要使用纯数字作为用户名"
                                                    data-parsley-remote="/register/check"
                                                    data-parsley-remote-options='{ method: "GET", dataType: "json"}'
                                                    data-parsley-remote-message="输入的用户名已被占用"
                                                >
                                                <span class="glyphicon glyphicon-user form-control-feedback"></span>
                                            </div>
                                            <div class="form-group has-feedback">
                                                <input type="password" name="password" class="form-control password-previewer" placeholder="密码" required
                                                    data-parsley-trigger="blur change"
                                                    data-parsley-minlength="6"
                                                    data-parsley-minlength-message="密码最短6位"
                                                    maxlength="26"
                                                    data-parsley-maxlength="26"
                                                    data-parsley-max-length="密码最长26位"
                                                >
                                                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                                            </div>
                                            <div class="form-footer">
                                                <div class="checkbox pull-left" style="width: 150px;">
                                                    <label>
                                                        <input type="checkbox" name="agree" checked="checked" required> 同意<a href="/page/terms" class="text-blue">使用条款</a>
                                                    </label>
                                                </div>
                                                <button type="submit" class="custom-button pull-right">注册</button>
                                            </div>
                                            <div class="br-title">
                                                <span class="text">使用社交账号注册</span>
                                            </div>
                                            <div class="custom-row">
                                                <div class="custom-span-left" style="">
                                                    <a class="custom-button size-fluid type-weibo" href="/auth/request/weibo/oauth2" target="_blank">
                                                        <i class="icontext icontext-weibo-md">微博帐号</i>
                                                    </a>
                                                </div>
                                                <div class="custom-span-right" style="">
                                                    <a class="custom-button size-fluid type-qq" href="/auth/request/tencent/oauth2" target="_blank">
                                                        <i class="icontext icontext-qq-md">QQ帐号</i>
                                                    </a>
                                                </div>
                                            </div>

                                        </form>
                                    </div>
                                    <div class="custom-modal-footer">
                                        <a class="link-left"  data-target="#user-modal-carousel" data-slide-to="1">返回登录</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
                </li>
                <!--  -->
            </ol>
        </div>
        <!--  -->
    </div>
    <!-- modal wrapper end -->
</div>


<!--[if lt IE 9]>
<script type="text/javascript" src="/vendor/js/jquery-1.11.1.min.js"></script>
<![endif]-->

<!--[if gt IE 8]><!-->
<script type="text/javascript" src="/vendor/js/jquery-2.1.1.min.js"></script>
<!--<![endif]-->

<!--  -->
<script src="/vendor/js/nano-scroller/jquery.nanoscroller.js"></script>
<script src="/vendor/js/parsley.js"></script>
<script src="/vendor/js/parsley.remote.js"></script>
<script src="/vendor/js/parsley.i18n.zh_cn.js"></script>
<script src="/vendor/js/jquery.blockUI.js"></script>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/wscn/js/bootstrap.min.js"></script>
<!--  -->
<script src="/wscn/js/main.js"></script>

<script>
$(document).ready(function(){
    //form validation
    $('form').parsley({
        successClass: "has-success",
        errorClass: "has-error",
        classHandler: function(el) {
            return el.$element.closest(".form-group");
        },

        errorsWrapper: "<span class='help-block' style='margin:0;'></span>",
        errorTemplate: "<span></span>"
    });

    $('form').on('focus change blur keyup', '.password-previewer', function(){
            var passwordInput = $(this);
            var helper = passwordInput.closest('.form-group').find('.form-control-feedback');
            if(passwordInput.val() !== '') {
                    helper.removeClass('glyphicon-lock').addClass('glyphicon-eye-open').css('cursor', 'pointer');
            } else {
                    helper.removeClass('glyphicon-eye-open glyphicon-eye-close').addClass('glyphicon-lock').css('cursor', 'default');
            }

            var inited = passwordInput.data('password-preview-inited');
            if(inited) {
                return;
            }
            passwordInput.closest('.form-group').on('click', '.form-control-feedback', function(){
                var icon = $(this);
                if(icon.hasClass('glyphicon-eye-open')) {
                    passwordInput.attr('type', 'text');
                    icon.toggleClass('glyphicon-eye-open glyphicon-eye-close');
                } else if(icon.hasClass('glyphicon-eye-close')) {
                    passwordInput.attr('type', 'password');
                    icon.toggleClass('glyphicon-eye-open glyphicon-eye-close');
                }
            });

            passwordInput.data('password-preview-inited', true); 
    });

});
</script>
</body>
</html>

