<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="zh-CN" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="zh-CN" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="zh-CN" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="zh-CN" class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta property="qc:admins" content="2540516740124067144342554366375747716" />
    <title><?=$this->placeholder->block('title', '华尔街见闻');?></title>

    <!-- Bootstrap -->
    <link href="/wscn/css/bootstrap.min.css" rel="stylesheet">
    <!-- for ie mobile content-width bug -->
    <script>
        if (navigator.userAgent.match(/IEMobile\/10\.0/)) {
            var msViewportStyle = document.createElement('style');
            msViewportStyle.appendChild(
                    document.createTextNode(
                            '@-ms-viewport{width:auto!important}'
                    )
            );
            document.querySelector('head').appendChild(msViewportStyle);
        }
    </script>
    <!-- font-awesome -->
    <link href="/wscn/css/font-awesome.min.css" rel="stylesheet">
    <!-- nanoScroller -->
    <link href="/vendor/js/nano-scroller/nanoscroller.css" rel="stylesheet">
    <!--  -->
    <link href="/wscn/css/style.css" rel="stylesheet">
    <!-- grunt watch for live reload  -->
    <!--<script src="//127.0.0.1:35729/livereload.js"></script>-->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- for img-box loading
    <script type="text/javascript">
        function img_loading(element){
            element.style.display = 'block';
        }
    </script>
    -->
</head>
<body>

<!-- -->
<header id="header">
    <div class="container">
        <nav class="navbar" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">
                    <h1 class="hidden">Wallstreet</h1>
                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a class="link" data-active-url="^\/news.*$" href="/news"><span class="text">新闻资讯</span></a></li>
                    <li><a class="link" data-active-url="^\/livenews.*$" href="/livenews"><span class="text">实时新闻</span></a></li>
                    <li><a class="link" data-active-url="^\/markets.*$" href="http://markets.<?=$this->config->domain?>" target="_blank"><span class="text">实时行情</span></a></li>
                    <li><a class="link" data-active-url="^\/calendar.*$" href="http://calendar.<?=$this->config->domain?>" target="_blank"><span class="text">财经日历</span></a></li>
                    <li><a class="link" href="http://www.goldtoutiao.com/" target="_blank"><span class="text">贵金属</span></a></li>
                    <li><a class="link" data-active-url="^\/broker.*$" href="http://broker.<?=$this->config->domain?>" target="_blank"><span class="text">交易商</span></a></li>
                    <li><a class="link" data-active-url="^\/app.*$" href="http://wallstreetcn.com/app/index.html" target="_blank"><span class="text">App下载</span></a></li>
                </ul>

                <div class="navbar-right relative">
                    <form class="search-form navbar-form" action="/news" role="search" novalidate="novalidate">
                        <div class="form-group has-feedback">
                            <input type="text" class="search-field" name="q" placeholder="请按回车键立即搜索">
                            <span class="fa fa-search form-control-feedback"></span>
                        </div>
                    </form>
                    <span class="user-control">
                        <a class="icon fa fa-user" href="/login"></a>
                        <a class="avatar" href="/mine/dashboard">
                            <img src="/wscn/img/avatar-md.png" alt=""/>
                        </a>
                        <div class="control">
                            <nav class="content">
                            <a class="item" href="/mine/stars">我的收藏</a>
                            <a class="item" href="/mine/comments">我的评论</a>
                            <a class="item" href="/mine/profile">用户资料</a>
                            <a class="item" href="/mine/password">
                                密码安全
                                <span class="icon-inactive">未激活</span>
                            </a>
                            <hr class="line" />
                            <a class="item" href="/logout">退出登录</a>
                            </nav>
                        </div>
                    </span>
                </div>

                <!--
                <form class="navbar-form navbar-left navbar-right" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>

                <form id="search-form" action="" role="search">
                    <input type="text" class="search-field" placeholder="Search">
                </form>
                -->
            </div><!-- /.navbar-collapse -->

        </nav>
    </div>
    <a id="breaking-news" href="">
        <div class="container">
            <h2 class="title">中证报评论：“微刺激”加码，稳增长措施有望进一步出台，下半年经济有望企稳，但下行压力依然存在。
                <span class="fa fa-times" data-action="hide-breaking-news"></span>
            </h2>
        </div>
    </a>
</header>
<div class="container">
    <img class="main-ad" src="/wscn/img/ad/main-ad.png" alt=""/>
</div>
<div id="content" class="container">
    <?=$this->getContent()?>
    <!-- qr code -->
    <a id="qrcode" class="hidden-xs hidden-xxs" href="http://wallstreetcn.com/app/index.html">
        <img src="/wscn/img/qrcode.png" alt=""/>
    </a>
    <!-- qr code end -->
</div>



<footer id="footer">
    <div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-lg-3">
                    <a href="/">
                        <img class="logo" src="/wscn/img/footer-logo.png" alt="logo"/>
                    </a>
                    <img class="qrcode" src="/wscn/img/footer-qrcode.png" alt="二维码"/>
                    <div class="icon-group text-center">
                        <a href="" class="icon icon-tencent pull-left"></a>
                        <a href="" class="icon icon-wechat"></a>
                        <a href="" class="icon icon-weibo pull-right"></a>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-sm-3 col-xs-6">
                            <h2 class="foot-title">相关信息</h2>
                            <ul class="list">
                                <li class="item">关于华尔街见闻</li>
                                <li class="item">使用条款</li>
                                <li class="item">版权声明</li>
                            </ul>
                        </div>
                        <div class="col-sm-3 col-xs-6">
                            <h2 class="foot-title">联系我们</h2>
                            <ul class="list">
                                <li class="item">广告投放</li>
                                <li class="item">商业合作</li>
                                <li class="item">意见反馈</li>
                            </ul>
                        </div>
                        <div class="col-sm-3 col-xs-6">
                            <h2 class="foot-title">关注我们</h2>
                            <ul class="list">
                                <li class="item">微博@华尔街见闻</li>
                                <li class="item">腾讯微博</li>
                                <li class="item">邮件订阅</li>
                                <li class="item">RSS订阅</li>
                            </ul>
                        </div>
                        <div class="col-sm-3 col-xs-6">
                            <h2 class="foot-title">加入我们</h2>
                            <ul class="list">
                                <li class="item">全职岗位</li>
                                <li class="item">实习岗位</li>
                            </ul>
                        </div>
                    </div>
                    <p class="friend-links">
                        <span class="title">财经</span>
                        <a class="link" href="">Hao123</a> |
                        <a class="link" href="">新浪财经</a> |
                        <a class="link" href="">腾讯财经</a> |
                        <a class="link" href="">和讯财经</a> |
                        <a class="link" href="">财经网</a> |
                    </p>
                    <p class="friend-links">
                        <span class="title">财经</span>
                        <a class="link" href="">Hao123</a> |
                        <a class="link" href="">新浪财经</a> |
                        <a class="link" href="">腾讯财经</a> |
                        <a class="link" href="">和讯财经</a> |
                        <a class="link" href="">财经网</a> |
                    </p>
                    <p class="friend-links">
                        <span class="title">财经</span>
                        <a class="link" href="">Hao123</a> |
                        <a class="link" href="">新浪财经</a> |
                        <a class="link" href="">腾讯财经</a> |
                        <a class="link" href="">和讯财经</a> |
                        <a class="link" href="">财经网</a> |
                    </p>
                    <p class="friend-links">
                        <span class="title">财经</span>
                        <a class="link" href="">Hao123</a> |
                        <a class="link" href="">新浪财经</a> |
                        <a class="link" href="">腾讯财经</a> |
                        <a class="link" href="">和讯财经</a> |
                        <a class="link" href="">财经网</a> |
                    </p>
                </div>
                <div class="col-xs-12">
                    <p class="copyright">
                        &copy; 2010 - 2014 华尔街见闻 Wallstreetcn.com 沪 ICP 备 13019121 号
                    </p>
                </div>
            </div>
            <!-- postbar -->
            <aside id="postbar" class="hidden-xs hidden-xxs">
                <a class="item suggest"></a>
                <a class="item wechat"></a>
                <a class="item up" href="#"></a>
            </aside>
            <!-- postbar ebd -->
        </div>
    </div>

</footer>


<!-- Modal -->
<div id="user-modal" class="custom-modal size-sm " tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
    <div class="wrapper">
        <div id="user-modal-carousel" class="carousel slide" data-ride="carousel" data-interval="false">
            <!-- Indicators
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            -->
            <!-- Wrapper for slides -->
            <ol class="carousel-inner">
                <li id="user-modal-reset" class="item centerbox">
                    <div class="custom-modal-content">
                        <div class="custom-modal-header">
                            <button type="button" class="close" data-action="close-custom-modal" data-target="#user-modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            重新设置密码
                        </div>
                        <div class="custom-modal-body">
                            <form data-validate action="/session/forgot"  method="POST" novalidate="novalidate">
                                <label >请输入注册邮箱</label>
                                <div class="form-group has-feedback">
                                    <input type="email" name="email" class="form-control" placeholder="注册邮箱" required>
                                    <span class="fa fa-envelope form-control-feedback"></span>
                                </div>
                                <div class="form-footer">
                                    <button type="submit" class="custom-button pull-right">发送确认邮件</button>
                                </div>
                            </form>
                        </div>
                        <div class="custom-modal-footer">
                            <a class="link-left"  data-target="#user-modal-carousel" data-slide-to="1">返回登录</a>
                            <a class="link-right" data-target="#user-modal-carousel" data-slide-to="2">注册</a>
                        </div>
                    </div>
                </li>
                <!--  -->

                <li id="user-modal-login" class="item centerbox active">
                    <div class="custom-modal-content">
                        <div class="custom-modal-header">
                            <button type="button" class="close" data-action="close-custom-modal" data-target="#user-modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            登录华尔街见闻
                        </div>
                        <div class="custom-modal-body">
                            <form data-validate action="/login"  method="POST" novalidate="novalidate">
                                <div class="form-group has-feedback">
                                    <input type="text" name="identify" class="form-control" placeholder="用户名或邮箱" required
                                        data-parsley-trigger="blur change"
                                        maxlength="24"
                                        data-parsley-minlength="4"
                                        data-parsley-minlength-message="用户名最短4个字符"
                                        data-parsley-pattern="^(?![0-9]+$)"
                                        data-parsley-pattern-message="不支持纯数字用户名"
                                    >
                                    <span class="fa fa-user form-control-feedback"></span>
                                </div>
                                <div class="form-group has-feedback">
                                    <input type="password" name="password" class="form-control password-previewer" placeholder="密码" required
                                        data-parsley-trigger="blur change"
                                        data-parsley-minlength="6"
                                        data-parsley-minlength-message="密码最短6位"
                                        maxlength="26"
                                        data-parsley-maxlength="26"
                                        data-parsley-max-length="密码最长26位"
                                    >
                                    <span class="fa fa-lock form-control-feedback"></span>
                                </div>
                                <div class="form-footer">
                                    <div class="checkbox pull-left" style="width: 100px;">
                                        <label>
                                            <input type="checkbox" name="remember"> 记住密码
                                        </label>
                                    </div>
                                    <button type="submit" class="custom-button pull-right">登录</button>
                                </div>
                            </form>
                            <div class="br-title">
                                <span class="text">使用社交账号登录</span>
                            </div>
                            <div class="custom-row">
                                <div class="custom-span-left" style="">
                                    <a class="custom-button size-fluid type-weibo login-social-btn" href="/auth/request/weibo/oauth2" target="_blank">
                                        <i class="icontext icontext-weibo-md">微博帐号</i>
                                    </a>
                                </div>
                                <div class="custom-span-right" style="">
                                    <a class="custom-button size-fluid type-qq login-social-btn" href="/auth/request/tencent/oauth2" target="_blank">
                                        <i class="icontext icontext-qq-md">QQ帐号</i>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="custom-modal-footer">
                            <a class="link-left"  data-target="#user-modal-carousel" data-slide-to="0">忘记密码</a>
                            <a class="link-right" data-target="#user-modal-carousel" data-slide-to="2">注册</a>
                        </div>
                    </div>
                </li>
                <!--  -->
                <li id="user-modal-register" class="item centerbox">
                    <div class="custom-modal-content">
                        <div class="custom-modal-header">
                            <button type="button" class="close" data-action="close-custom-modal" data-target="#user-modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            注册华尔街见闻
                        </div>
                        <div class="custom-modal-body">
                            <form data-validate action="/register"  method="POST" novalidate="novalidate" role="form">
                                <label>使用邮箱注册</label>
                                <div class="form-group has-feedback">
                                    <input type="email" name="email" class="form-control" placeholder="邮箱" required
                                        data-parsley-trigger="blur change"
                                        data-parsley-remote="/register/check"
                                        data-parsley-remote-options='{ method: "GET", dataType: "json"}'
                                        data-parsley-remote-message="输入的邮箱已被占用"
                                    >
                                    <span class="fa fa-envelope form-control-feedback"></span>
                                </div>
                                <div class="form-group has-feedback">
                                    <input type="text" name="username" class="form-control" placeholder="用户名" required
                                        data-parsley-trigger="blur change"
                                        data-parsley-type="alphanum"
                                        maxlength="24"
                                        data-parsley-minlength="4"
                                        data-parsley-minlength-message="用户名最短4个字符"
                                        data-parsley-maxlength="24"
                                        data-parsley-pattern="^(?![0-9]+$)"
                                        data-parsley-pattern-message="请不要使用纯数字作为用户名"
                                        data-parsley-remote="/register/check"
                                        data-parsley-remote-options='{ method: "GET", dataType: "json"}'
                                        data-parsley-remote-message="输入的用户名已被占用"
                                    >
                                    <span class="fa fa-user form-control-feedback"></span>
                                </div>
                                <div class="form-group has-feedback">
                                    <input type="password" name="password" class="form-control password-previewer" placeholder="密码" required
                                        data-parsley-trigger="blur change"
                                        data-parsley-minlength="6"
                                        data-parsley-minlength-message="密码最短6位"
                                        maxlength="26"
                                        data-parsley-maxlength="26"
                                        data-parsley-max-length="密码最长26位"
                                    >
                                    <span class="fa fa-lock form-control-feedback"></span>
                                </div>
                                <div class="form-footer">
                                    <div class="checkbox pull-left" style="width: 150px;">
                                        <label>
                                            <input type="checkbox" name="agree" checked="checked" value="yes" required> 同意<a href="/page/terms" class="text-blue" target="_blank">使用条款</a>
                                        </label>
                                    </div>
                                    <button type="submit" class="custom-button pull-right">注册</button>
                                </div>
                                <div class="br-title">
                                    <span class="text">使用社交账号注册</span>
                                </div>
                                <div class="custom-row">
                                    <div class="custom-span-left" style="">
                                        <a class="custom-button size-fluid type-weibo login-social-btn" href="/auth/request/weibo/oauth2" target="_blank">
                                            <i class="icontext icontext-weibo-md">微博帐号</i>
                                        </a>
                                    </div>
                                    <div class="custom-span-right" style="">
                                        <a class="custom-button size-fluid type-qq login-social-btn" href="/auth/request/tencent/oauth2" target="_blank">
                                            <i class="icontext icontext-qq-md">QQ帐号</i>
                                        </a>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="custom-modal-footer">
                            <a class="link-left" data-target="#user-modal-carousel" data-slide-to="1">返回登录</a>
                        </div>
                    </div>
                </li>
                <!--  -->
                <li id="user-modal-connect-login" class="item centerbox">
                    <div class="custom-modal-content" style="width: 600px;">
                        <div class="custom-modal-header">
                            <button type="button" class="close" data-action="close-custom-modal" data-target="#user-modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            使用社交帐号登录
                        </div>
                        <div class="custom-modal-body" style="border-radius: 0 0 10px 10px;">
                            <ul class="custom-nav-tabs">
                                <li >
                                    <a href="" data-target="#user-modal-carousel" data-slide-to="4">
                                        <i class="fa fa-user"></i> 初次注册
                                    </a>
                                </li>
                                <li class="active">
                                    <a href="" data-target="#user-modal-carousel" data-slide-to="3">
                                        <i class="fa fa-link"></i> 已有账号
                                    </a>
                                </li>
                            </ul>
                            <form data-validate action="/auth/login" class="clearfix" method="POST" novalidate="novalidate">
                                <div class="custom-row">
                                    <div class="custom-span-1">
                                        <h3 class="form-title"><span data-auth-site></span>帐号</h3>
                                        <div class="text-center">
                                            <img class="form-avatar" src="" alt="" data-auth-avatar/>
                                            <br/>
                                            <div class="form-label" data-auth-user></div>
                                        </div>
                                    </div>
                                    <div class="custom-span-2"></div>
                                    <div class="custom-span-3">
                                        <h3 class="form-title">华尔街见闻</h3>
                                        <div class="form-group has-feedback size-sm">
                                            <input type="text" name="identify" class="form-control" placeholder="用户名或邮箱" required
                                                data-parsley-trigger="blur change"
                                                maxlength="24"
                                                data-parsley-minlength="4"
                                                data-parsley-minlength-message="用户名最短4个字符"
                                                data-parsley-pattern="^(?![0-9]+$)"
                                                data-parsley-pattern-message="不支持纯数字用户名"
                                            >
                                            <span class="fa fa-user form-control-feedback"></span>
                                        </div>
                                        <div class="form-group has-feedback size-sm">
                                            <input type="password" name="password" class="form-control" placeholder="密码" required
                                                data-parsley-trigger="blur change"
                                                data-parsley-minlength="6"
                                                data-parsley-minlength-message="密码最短6位"
                                                maxlength="26"
                                                data-parsley-maxlength="26"
                                                data-parsley-max-length="密码最长26位"
                                            >
                                            <span class="fa fa-lock form-control-feedback"></span>
                                        </div>
                                        <label class="form-label">请验证需要绑定的帐号信息</label>
                                    </div>
                                </div>
                                <hr class="form-hr"/>
                                <button type="submit" class="custom-button pull-right">登录并绑定</button>
                            </form>
                        </div>
                    </div>
                </li>
                <!--  -->
                <li id="user-modal-connect-register" class="item centerbox">
                    <div class="custom-modal-content" style="width: 560px">
                        <div class="custom-modal-header">
                            <button type="button" class="close" data-action="close-custom-modal" data-target="#user-modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            使用社交帐号注册
                        </div>
                        <div class="custom-modal-body" style="border-radius: 0 0 10px 10px;">
                            <ul class="custom-nav-tabs">
                                <li class="active">
                                    <a href="" data-target="#user-modal-carousel" data-slide-to="4">
                                        <i class="fa fa-user"></i> 初次注册
                                    </a>
                                </li>
                                <li >
                                    <a href="" data-target="#user-modal-carousel" data-slide-to="3">
                                        <i class="fa fa-link"></i> 已有账号
                                    </a>
                                </li>
                            </ul>
                            <form data-validate action="/auth/register" class="clearfix" method="POST" novalidate="novalidate" role="form">
                                <div class="custom-row custom-row-2">
                                    <div class="vr-line"></div>
                                    <div class="custom-span-4" style="margin-top: -8px;">
                                        <span data-auth-icon></span><span data-auth-site></span>帐号
                                    </div>
                                    <div class="custom-span-5">
                                        <img class="form-avatar" src="" alt="" data-auth-avatar />
                                        <br/>
                                        <div class="form-label"  data-auth-user></div>
                                    </div>
                                    <div class="custom-span-4">
                                        邮箱
                                    </div>
                                    <div class="custom-span-5">
                                        <div class="form-group has-feedback size-sm">
                                            <input id="connected-register-form-email" type="email" name="email" class="form-control" placeholder="邮箱" required
                                                   data-parsley-trigger="blur change"
                                                   data-parsley-remote="/register/check"
                                                   data-parsley-remote-options='{ method: "GET", dataType: "json"}'
                                                   data-parsley-remote-message="输入的邮箱已被占用"
                                                    >
                                            <span class="fa fa-envelope form-control-feedback"></span>
                                        </div>
                                    </div>
                                    <div class="custom-span-4">
                                        用户名
                                    </div>
                                    <div class="custom-span-5">
                                        <div class="form-group has-feedback size-sm">
                                            <input type="text" name="username" class="form-control" placeholder="用户名" required
                                                   data-parsley-trigger="blur change"
                                                   data-parsley-type="alphanum"
                                                   maxlength="24"
                                                   data-parsley-minlength="4"
                                                   data-parsley-minlength-message="用户名最短4个字符"
                                                   data-parsley-maxlength="24"
                                                   data-parsley-pattern="^(?![0-9]+$)"
                                                   data-parsley-pattern-message="请不要使用纯数字作为用户名"
                                                   data-parsley-remote="/register/check"
                                                   data-parsley-remote-options='{ method: "GET", dataType: "json"}'
                                                   data-parsley-remote-message="输入的用户名已被占用"
                                                    >
                                            <span class="fa fa-user form-control-feedback"></span>
                                        </div>
                                        <label for="connected-register-form-email" class="form-label">请填写邮箱及用户名确保账号不会丢失</label>
                                    </div>
                                </div>
                                <hr class="form-hr"/>
                                <button type="submit" class="custom-button pull-right">注册</button>
                            </form>
                        </div>
                    </div>
                </li>
                <!--  -->
            </ol>
        </div>
        <!--  -->
    </div>
    <!-- modal wrapper end -->
</div>


<!--[if lt IE 9]>
<script type="text/javascript" src="/vendor/js/jquery-1.11.1.min.js"></script>
<![endif]-->

<!--[if gt IE 8]><!-->
<script type="text/javascript" src="/vendor/js/jquery-2.1.1.min.js"></script>
<!--<![endif]-->

<!--  -->
<script src="/vendor/js/nano-scroller/jquery.nanoscroller.js"></script>
<script src="/vendor/js/parsley.js"></script>
<script src="/vendor/js/parsley.remote.js"></script>
<script src="/vendor/js/parsley.i18n.zh_cn.js"></script>
<script src="/vendor/js/jquery.blockUI.js"></script>
<script src="/wscn/js/jquery.cityselect.js" type="text/javascript"></script>
<script src="/vendor/js/jquery.lazyload.js" type="text/javascript"></script>
<!-- 图片延时加载 -->
<script type="text/javascript">
    $("img.lazy").lazyload();
    /*
    $(window).on('click', '[data-trigger=lazyload]', function(e){
        console.log('trigger lazyload');
        $(window).trigger('resize.lazyload');
    });
    */
</script>
<script src="/vendor/js/moment.min.js"></script>
<script type="text/javascript">
    moment.lang('zh-cn', {
        months : "一月_二月_三月_四月_五月_六月_七月_八月_九月_十月_十一月_十二月".split("_"),
        monthsShort : "1月_2月_3月_4月_5月_6月_7月_8月_9月_10月_11月_12月".split("_"),
        weekdays : "星期日_星期一_星期二_星期三_星期四_星期五_星期六".split("_"),
        weekdaysShort : "周日_周一_周二_周三_周四_周五_周六".split("_"),
        weekdaysMin : "日_一_二_三_四_五_六".split("_"),
        longDateFormat : {
            LT : "Ah点mm",
            L : "YYYY-MM-DD",
            LL : "YYYY年MMMD日",
            LLL : "YYYY年MMMD日LT",
            LLLL : "YYYY年MMMD日ddddLT",
            l : "YYYY-MM-DD",
            ll : "YYYY年MMMD日",
            lll : "YYYY年MMMD日LT",
            llll : "YYYY年MMMD日ddddLT"
        },
        meridiem : function (hour, minute, isLower) {
            var hm = hour * 100 + minute;
            if (hm < 600) {
                return "凌晨";
            } else if (hm < 900) {
                return "早上";
            } else if (hm < 1130) {
                return "上午";
            } else if (hm < 1230) {
                return "中午";
            } else if (hm < 1800) {
                return "下午";
            } else {
                return "晚上";
            }
        },
        calendar : {
            sameDay : function () {
                return this.minutes() === 0 ? "[今天]Ah[点整]" : "[今天]LT";
            },
            nextDay : function () {
                return this.minutes() === 0 ? "[明天]Ah[点整]" : "[明天]LT";
            },
            lastDay : function () {
                return this.minutes() === 0 ? "[昨天]Ah[点整]" : "[昨天]LT";
            },
            nextWeek : function () {
                var startOfWeek, prefix;
                startOfWeek = moment().startOf('week');
                prefix = this.unix() - startOfWeek.unix() >= 7 * 24 * 3600 ? '[下]' : '[本]';
                return this.minutes() === 0 ? prefix + "dddAh点整" : prefix + "dddAh点mm";
            },
            lastWeek : function () {
                var startOfWeek, prefix;
                startOfWeek = moment().startOf('week');
                prefix = this.unix() < startOfWeek.unix()  ? '[上]' : '[本]';
                return this.minutes() === 0 ? prefix + "dddAh点整" : prefix + "dddAh点mm";
            },
            sameElse : 'LL'
        },
        ordinal : function (number, period) {
            switch (period) {
                case "d":
                case "D":
                case "DDD":
                    return number + "日";
                case "M":
                    return number + "月";
                case "w":
                case "W":
                    return number + "周";
                default:
                    return number;
            }
        },
        relativeTime : {
            future : "%s内",
            past : "%s前",
            s : "几秒",
            m : "1分钟",
            mm : "%d分钟",
            h : "1小时",
            hh : "%d小时",
            d : "1天",
            dd : "%d天",
            M : "1个月",
            MM : "%d个月",
            y : "1年",
            yy : "%d年"
        },
        week : {
            // GB/T 7408-1994《数据元和交换格式·信息交换·日期和时间表示法》与ISO 8601:1988等效
            dow : 1, // Monday is the first day of the week.
            doy : 4  // The week that contains Jan 4th is the first week of the year.
        }
    });
    //
    moment.lang('zh-cn');
</script>
<script src="/vendor/js/art-template-native-3.0.0.js"></script>
<script src="/vendor/wscn/js/wscn_util.js"></script>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/wscn/js/bootstrap.min.js"></script>
<script src="/wscn/js/usermanager.js"></script>
<script src="/wscn/js/login-ui.js"></script>
<script src="/wscn/js/userlogin.js"></script>

<!--  -->
<script src="/wscn/js/fcl.js"></script>
<script src="/wscn/js/main.js"></script>
<script src="/wscn/js/leftbar.js"></script>
<script src="/wscn/js/livenews.js"></script>

<script>

$(document).ready(function(){
    UserLogin.getInstance();
    //form validation
    $('form[data-validate]').parsley({
        successClass: "has-success",
        errorClass: "has-error",
        classHandler: function(el) {
            return el.$element.closest(".form-group");
        },

        errorsWrapper: "<span class='help-block' style='margin-bottom: 0;'></span>",
        errorTemplate: "<span></span>"
    });

    $('form[data-validate]').on('focus change blur keyup', '.password-previewer', function(){
            var passwordInput = $(this);
            var helper = passwordInput.closest('.form-group').find('.form-control-feedback');
            if(passwordInput.val() !== '') {
                    helper.removeClass('fa-lock').addClass('fa-eye').css('cursor', 'pointer');
            } else {
                    helper.removeClass('fa-eye fa-eye-slash').addClass('fa-lock').css('cursor', 'default');
            }

            var inited = passwordInput.data('password-preview-inited');
            if(inited) {
                return;
            }
            passwordInput.closest('.form-group').on('click', '.form-control-feedback', function(){
                var icon = $(this);
                if(icon.hasClass('fa-eye')) {
                    passwordInput.attr('type', 'text');
                    icon.toggleClass('fa-eye fa-eye-slash');
                } else if(icon.hasClass('fa-eye-slash')) {
                    passwordInput.attr('type', 'password');
                    icon.toggleClass('fa-eye fa-eye-slash');
                }
            });

            passwordInput.data('password-preview-inited', true); 
    });



});
</script>
</body>
</html>

