<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title><?=$this->placeholder->block('title', '华尔街见闻');?></title>

    <!-- Bootstrap -->
    <link href="/wscn/css/bootstrap.min.css" rel="stylesheet">
    <!-- for ie mobile content-width bug -->
    <script>
        if (navigator.userAgent.match(/IEMobile\/10\.0/)) {
            var msViewportStyle = document.createElement('style');
            msViewportStyle.appendChild(
                    document.createTextNode(
                            '@-ms-viewport{width:auto!important}'
                    )
            );
            document.querySelector('head').appendChild(msViewportStyle);
        }
    </script>
    <!-- nanoScroller -->
    <link href="/vendor/js/nano-scroller/nanoscroller.css" rel="stylesheet">
    <!--  -->
    <link href="/wscn/css/style.css" rel="stylesheet">
    <!-- grunt watch for live reload  -->
    <script src="//localhost:35729/livereload.js"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<!-- -->
<header id="header">
    <div class="container">
        <nav class="navbar" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">
                    <h1 class="hidden">Wallstreet</h1>
                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#">新闻资讯</a></li>
                    <li><a href="#">实时新闻</a></li>
                    <li><a href="#">实时行情</a></li>
                    <li><a href="#">财经日历</a></li>
                    <li><a href="#">见闻早餐</a></li>
                    <li><a href="#">黄金头条</a></li>
                    <li><a href="#">贵金属吐槽台</a></li>
                    <li><a href="#">App下载</a></li>
                </ul>

                <form class="search-form navbar-form navbar-right" role="search">
                    <input type="text" class="search-field" placeholder="Search">
                </form>

                <!--
                <form class="navbar-form navbar-left navbar-right" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>

                <form id="search-form" action="" role="search">
                    <input type="text" class="search-field" placeholder="Search">
                </form>
                -->
            </div><!-- /.navbar-collapse -->

        </nav>
    </div>
    <a id="breaking-news" href="">
        <div class="container">
            <h2 class="title">中证报评论：“微刺激”加码，稳增长措施有望进一步出台，下半年经济有望企稳，但下行压力依然存在。
                <span class="glyphicon glyphicon-remove" data-action="close"></span>
            </h2>
        </div>
    </a>
</header>

<div id="content">
<?=$this->getContent()?>
</div>

<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-lg-3"></div>
            <div class="col-md-2 col-sm-3 col-xs-6">
                <h2 class="foot-title">相关信息</h2>
                <ul class="list">
                    <li class="item">关于华尔街见闻</li>
                    <li class="item">使用条款</li>
                    <li class="item">版权声明</li>
                </ul>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-6">
                <h2 class="foot-title">联系我们</h2>
                <ul class="list">
                    <li class="item">广告投放</li>
                    <li class="item">商业合作</li>
                    <li class="item">意见反馈</li>
                </ul>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-6">
                <h2 class="foot-title">关注我们</h2>
                <ul class="list">
                    <li class="item">微博@华尔街见闻</li>
                    <li class="item">腾讯微博</li>
                    <li class="item">邮件订阅</li>
                    <li class="item">RSS订阅</li>
                </ul>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-6">
                <h2 class="foot-title">加入我们</h2>
                <ul class="list">
                    <li class="item">全职岗位</li>
                    <li class="item">实习岗位</li>
                </ul>
            </div>
        </div>
    </div>
</footer>


<!--[if lt IE 9]>
<script type="text/javascript" src="/vendor/js/jquery-1.11.1.min.js"></script>
<![endif]-->

<!--[if gte IE 9]>
<script type="text/javascript" src="/vendor/js/jquery-2.1.1.min.js"></script>
<![endif]-->

<!--[if !IE]><!-->
<script type="text/javascript" src="/vendor/js/jquery-2.1.1.min.js"></script>
<!--<![endif]-->

<!--  -->
<script src="/vendor/js/nano-scroller/jquery.nanoscroller.js"></script>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/wscn/js/bootstrap.min.js"></script>
<!--  -->
<script src="/wscn/js/main.js"></script>
</body>
</html>

