<div>
    <?=$this->partial('partial/top_single')?>
    <div class="content-wrapper">

        <div class="login-form" style="display:">
            <section id="loginSection" class="login-section">
            <form name="loginForm" data-validate action="/login"  method="POST">
                <h1>华尔街见闻帐号登录</h1>
                <div>
                    <input type="text" name="identify" class="username" placeholder="用户名或邮箱" required>
                </div>
                <div>
                    <input type="password" name="password" class="password" placeholder="密码" required>
                </div>
                <div>
                    <input type="submit" value="登录" />
                </div>
            </form><!-- form -->
            <div class="nav">
                <span class="left" data-target="reset-password-form">忘记密码?</span>
                <span class="right" data-target="register-form">注册</span>

            </div><!-- button -->
            </section><!-- content -->
        </div><!-- container -->

        <div class="register-form" style="display:none">
            <section id="registerSection" class="register-section">
            <form name="registerForm" data-validate action="/register"  method="POST">
                <h1>新用户注册</h1>
                <div>
                    <input type="text" name="email" class="email" placeholder="邮箱" required
                    data-parsley-trigger="blur change"
                    data-parsley-remote="/register/check"
                    data-parsley-remote-options='{ method: "GET", dataType: "json"}'
                    data-parsley-remote-message="输入的邮箱已被占用" >
                </div>
                <div>
                    <input type="text" name="username" class="username" placeholder="用户名" required
                    data-parsley-trigger="blur change"
                    data-parsley-type="alphanum"
                    maxlength="24"
                    data-parsley-minlength="4"
                    data-parsley-minlength-message="用户名最短4个字符"
                    data-parsley-maxlength="24"
                    data-parsley-pattern="^(?![0-9]+$)"
                    data-parsley-pattern-message="请不要使用纯数字作为用户名"
                    data-parsley-remote="/register/check"
                    data-parsley-remote-options='{ method: "GET", dataType: "json"}'
                    data-parsley-remote-message="输入的用户名已被占用" >
                </div>
                <div>
                    <input type="password" name="password" class="password" placeholder="密码" required
                    data-parsley-trigger="blur change"
                    data-parsley-minlength="6"
                    data-parsley-minlength-message="密码最短6位"
                    maxlength="26"
                    data-parsley-maxlength="26"
                    data-parsley-max-length="密码最长26位" >
                </div>
                <div>
                    <input type="submit" value="注册" />
                </div>
            </form><!-- form -->
            <div class="nav">
                <span class="left" data-target="login-form">返回登录</span>
            </div><!-- button -->
            </section><!-- content -->
        </div><!-- container -->

        <div class="reset-password-form" style="display:none">
            <section id="resetPasswordSection" class="reset-password-section">
            <form name="resetPasswordForm" data-validate action="/reset"  method="POST">
                <h1>重置密码</h1>
                <div>
                    <input type="text" name="email" class="email" placeholder="注册邮箱" required>
                </div>
                <div>
                    <input type="submit" value="发送确认邮件" />
                </div>
            </form><!-- form -->
            <div class="nav">
                <span class="left" data-target="login-form">返回登录</span>
                <span class="right" data-target="register-form">注册</span>
            </div><!-- button -->
            </section><!-- content -->
        </div><!-- container -->

    </div>
	<!--
	<div id="dlgLoginTip" title="登陆提示">
        <p>用户名和密码不能为空</p>
    </div>
	-->
	<div id="dlgLoginErrorTip" title="登陆提示">
        <p>用户名或者密码不正确</p>
    </div>
    <?=$this->partial('partial/footer')?>
</div>
<?=$this->partial('partial/js')?>
<!--<script type="text/javascript" src="/vendor/js/parsley.js"></script>-->
<script type="text/javascript">
    (function ($) {
            $(".nav span").click(function(){
                    $(".content-wrapper > div").css("display","none");
                    $("." + $(this).attr("data-target")).css("display","");
            })

            //$('form[data-validate]').parsley({
            //});
			
			$('#dlgLoginErrorTip').dialog({
				autoOpen: false,
				closeBtn: false,
				buttons: {
					'确定': function(){
						this.close();
					}
				}
			}).dialog('this')._options['_wrap'].addClass('login-dialog');

    }(Zepto));
</script>
